### ISSUE TITLE
Нужен ли sleep?

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#11]
Я решил с Вами посоветоваться все ж - мне кажется, нужен тут слип, т.к. внешний while ограничивает время ожидания генерала (ов). Без него цикл быстро прогонится, а какой-нить медленный гена не успеет доплыть. Я исходил из расчета 300 циклов на 30 сек слипы. Но похоже обсчитался - надо на 3 сек слип заменить - это как раз 3*300 = 900 сек или 15 мин для непрокачанных автобусов, к примеру
 
```
	while ($i < 300)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) Then
				$fl = 1
				ExitLoop
			Else
				If (zvezdamovepolzunokdown(1) = 0) then
					; zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
					ExitLoop
				EndIf
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(30000 * $tormoza)
	Wend

```

**Comment by jemxx** [comment]
Слип нужен, тормоза не нужны. Иначе нет смысла от слипа, если его можно изменить. Мне кажется тут должно быть не изменяемое значение слипа.
Sleep(30000 * $tormoza) заменить на Sleep(30000). Ну и 30 секунд много.

**Comment by ghost** [comment]
а, все, тогда я Вас не понял. Согласен, будете сливать замените на Sleep(3000). Это 15 минут, если я верно посчитал. Там на самом деле еще один if лишний, я вычитал, что в автоите можно юзать множественный exitloop  и тогда будет так

```
while ($i < 300)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) Then
				$fl = 1
				ExitLoop 2 ; дождались активного гену и выходим из всех циклов 
			Else
				If (zvezdamovepolzunokdown(1) = 0) then
					ExitLoop
				EndIf
			EndIf
		WEnd
		; If ($fl = 1) Then ExitLoop этот if не нужен, т.к. есть ExitLoop 2
		$i = $i + 1
		Sleep(3000)
	Wend
```

**Comment by jemxx** [comment]
Я уже слил, замена не вошла) Поправлю отдельным комитом

**Comment by jemxx** [comment]
3 секунды наверно тоже мало. Не вижу смысла так часто проверять. 10-15 секунд может быть. Просто уменьшить количество циклов до 90, например, что бы были те же  900 секунд

**Comment by ghost** [comment]
вы наверное не ходите ботом на скорость, да?)) Иногда в проходе каждая секунда на вес золота, 10-15 секунд, даже может 20 секунд - это как раз время разворачивания лагеря

**Comment by jemxx** [comment]
Хорошо, пусть остается 3 секунды
