### ISSUE TITLE
ЖдемПобеду

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#15]
Я кстати разобрался, почему не всегда срабатывает команда ЖдемПобеду. Эти одаренные разработчики сделали разный фон для генералов в звезде и наверху в всплывающем окошке с его действиями. Более того, этот информер частично прозрачный. Видна часть береговой линии

![Screenshot_4](https://user-images.githubusercontent.com/64967268/90137616-8bd79280-dd7e-11ea-8055-3f6e49b1f3df.png)

Один из выходов - перескринить всех генералов не из звезды, а с этого информера и проверить, будут ли такие скрины работать в других случаях (Наборы, переезды и атаки). Если нет, то продублировать скрины генералов скринами из информера и расширить конфиг.

**Comment by jemxx** [comment]
Лучше наверно сразу отдельными скринами делать.

**Comment by ghost** [comment]
Со скринами тоже есть нюансы. Если включена обсерва, там звезда появляется справа в углу. Это значит что скринить надо часть конки генерала. Дальше надо проверять влияет или нет фон под геной - вода, песок или здания. Кто-то в чате писал, что не сработала ЖдемКартинку. 
Я поэтому и выделил в отдельную задачу, что нужно проверять много. И с наскока не получилось, как хотелось

**Comment by ghost** [comment]
Я в очередной раз победил эту проблему, но нужно тестирование на всех генах. 

Нужно заменить в globalfunc sleepwhile2 на ту, что ниже

```
func sleepwhile2($img, $time, $flag)
	local $i = 0, $tolerance = 30, $fl_win = 0
	while ($i < $time)
		If ((haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1)) Then
			$fl_win = 1
			Exitloop
		EndIf
		sleep(1000)
		$i = $i + 1
	wend
	if ($fl_win = 1) or ($flag = 1) then
		Return 1
	else
		Return 0
	endif
endfunc
```

Заодно убрать из sleepwhile тормоза
```
func sleepwhile($img, $tolerance, $time)
	local $i = 0
	while (haveimage($img, $tolerance) = 0) and ($i < ($time * 2))
		sleep (500)
		$i = $i + 1
	wend
	if $i < ($time * 2) then
		Return 1
	else
		Return 0
	endif
endfunc
```

А при функцию чтения параметров генерала getGeneralData заменить на следующую

```
Func getGeneralData($general)
	Local $i = 0
	Local $generalData[4]
	Local $specialists = getDataGroupSpecialists("generals")

	While 1
		$generalName = Json_Get($specialists, '[' & $i & '].name')

		If @error Then ExitLoop
		If $general = $generalName Then
			$generalData[0] = "media\" & Json_Get($specialists, '[' & $i & '].img_active')
			$generalData[1] = Json_Get($specialists, '[' & $i & '].max_capacity')
			$generalData[2] = "media\" & Json_Get($specialists, '[' & $i & '].img_noactive')
			$generalData[3] = "media\" & "sp" & Json_Get($specialists, '[' & $i & '].img_active')
			ExitLoop
		EndIf

		$i += 1
	WEnd

	if ($generalData[0] = "") Then
		MsgBox(0, "Внимание!", "Неправильный параметр типа Генерала")
		Return 0
	Else
		Return $generalData
	EndIf
EndFunc
``` 

По аналогии как я сделал всплывающее изображение ($generalData[3]), можно сделать и No_gena ($generalData[2]) и упростить конфиг-файл. Но это уже на Ваше усмотрение. И наконец весь нужный контент в папку медиа я добавил в zip-архив. На всякий случай перескринил картинку gen_win.bmp. Как-то нестабильно работала
[media.zip](https://github.com/jemxx/autobot/files/5106009/media.zip)


В общем, все, я на этом прекращаю что-то глобальное делать и буду тестировать. Хорошо бы выпускать релиз и отдавать народу на тестирование.

**Comment by jemxx** [comment]
> В общем, все, я на этом прекращаю что-то глобальное делать и буду тестировать. Хорошо бы выпускать релиз и отдавать народу на тестирование.

Соберу сегодня все в кучу и завтра будет релиз. Я тоже потихоньку доделываю группу генералов.

**Comment by ghost** [comment]
о, это было бы суперски тогда. Спасибо!

**Comment by jemxx** [comment]
>По аналогии как я сделал всплывающее изображение ($generalData[3]), можно сделать и No_gena ($generalData[2]) и упростить конфиг-файл.

Не. не стоит. По хорошему и ваши бы картинки в конфиг добавить. Кто будет добавлять сам генералов не узнает что нужны еще картинки с именем sp*.bmp. Плюс с моим вариантом название картинок может быть любым.  В вашем же варианте только определенное вами название))

**Comment by ghost** [comment]
Я Вам открою страшную тайну)) Этот json файл кроме Вас и меня вообще никто не будет открывать скорее всего, т.к. у него не пойми какое разрешение)))) я с этим уже столкнулся "а где ген-то прописывать? а чем этот файл открыть? Блокнотом? не, не пробовал, а че можно было?". И чем больше свободы давать пользователю, тем меньше будет переносимость текстовиков, поэтому я против самодеятельности) Кстати, я так и не понял в чем именно, но иконки ген в звезде и в сплеш-окне разные, и дело не в фоне и прозрачности.

**Comment by jemxx** [comment]
Я же вам говорю, кто не соображает, тот пусть ждет когда все будет добавлено. Для тех кто может разобраться все должно быть понятно без лишних вопросов. И наверное что бы все по феншую было добавлю это в конфиг-файл. Дел то на 5 минут.
