### ISSUE TITLE
НабратьИперенести

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#16]
Я сделал и проверил на простой и элитной армии, не проверял на атаке с 1юнитом, т.к. н юзаю этот функционал, но думаю все будет работать.
Проблема с пул реквестом. У меня какая-то кривая версия сорсов лежит в моей ветке, видимо я залил свои упражнения с изменением отправки ген, поэтому боюсь, как бы чего лишнего между локальной и гитхабной версиями не смержилось.
Я тут два куска кода вставлю лучше, а Вы добавите в нужные юниты.
Один кусок в главный юнит - по сути это копия куска с НабратьИатаковать с заменой последней функции atakaotkritimgenoynoini() в каждом из условий на новую функцию perenosotkritimgenoynoini()
А сама функция perenosotkritimgenoynoini() это копия atakaotkritimgenoynoini() с заменой картинки атаки (мечи) на картинку переноса (трубы) описана в globalfuncWAR

**autoit.au3**
```
		Case "НабратьИперенести"
			$centrovat = 1
			Local $perebor = 1
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd

			$generalData = getGeneralData($parametr[1])
			$gena = $generalData[0]
			$full = $generalData[1]

			If openzvezdap() = 1 Then
				If selecttabatzvezda("specialisti", 1) = 1 Then
					If generali($gena, $parametr[2]) = 1 Then
						If $parametr[3] = "Э" Then
							While apply_elitnoy_army($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $full, 0) <> 1
								zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
								openzvezdap()
								selecttabatzvezda("specialisti", 1)
								generali($gena, $parametr[2])
							WEnd
							$gluksnaboromarmii = 0
							Return perenosotkritimgenoynoini($parametr[11], $parametr[12], $userDIR & $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17])
						EndIf
						If $parametr[3] = "1" Then
							If haveimage("media\1.bmp", 20) = 1 Then
								Return perenosotkritimgenoynoini($parametr[13], $parametr[14], $userDIR & $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19])
							Else
								While applyarmy($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $parametr[11], $parametr[12], $full, 0) <> 1
									zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
									openzvezdap()
									selecttabatzvezda("specialisti", 1)
									generali($gena, $parametr[2])
								WEnd
								$gluksnaboromarmii = 0
								Return perenosotkritimgenoynoini($parametr[13], $parametr[14], $userDIR & $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19])
							EndIf
						EndIf
						If $parametr[3] = "П" Then
							While applyarmy($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $parametr[11], $parametr[12], $full, 0) <> 1
								zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
								openzvezdap()
								selecttabatzvezda("specialisti", 1)
								generali($gena, $parametr[2])
							WEnd
							$gluksnaboromarmii = 0
							Return perenosotkritimgenoynoini($parametr[13], $parametr[14], $userDIR & $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19])
						Else
							Return 0
						EndIf
					EndIf
				EndIf
			EndIf

```

**globalfuncWAR.au3**

```
Func perenosotkritimgenoynoini($kudax, $kuday, $img, $k_x, $k_y, $else_x, $else_y)
	Local $tx = 0, $ty = 0, $search = 0, $i = 0
	zmemsmennuyukartinku("media\truba.bmp", 50, "media\truba_.bmp", 50)
	$i = 0
	If ($centrovat = 0) AND (_imagesearch($img, 1, $tochka_sektora_x, $tochka_sektora_y, read_ini(1)) = 1) Then
		If (200 < ($tochka_sektora_x + $kudax)) AND (($tochka_sektora_x + $kudax) < (@DesktopWidth - 200)) Then
			If (200 < ($tochka_sektora_y + $kuday)) AND (($tochka_sektora_y + $kuday) < (@DesktopHeight - 200)) Then
				$centrovat = 1
			Else
				$centrovat = 1
				If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
			EndIf
		Else
			$centrovat = 1
			If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
		EndIf
	Else
		$centrovat = 1
		If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
	EndIf
	sleepwhile("media\Otmena.bmp", 30, 10)
	$kudax = $tochka_sektora_x + $kudax
	$kuday = $tochka_sektora_y + $kuday
	While (_imagesearch("media\Otmena.bmp", 1, $tx, $ty, 20) = 1) AND ($i < 6)
		MouseMove($kudax, $kuday, 10 * $tormoza)
		Sleep(700 * $tormoza)
		MouseClick("left", $kudax, $kuday, 1)
		Sleep(300 * $tormoza)
		go5()
		$i = $i + 1
	WEnd
	If $i = 6 Then
		Return 0
	Else
		Return 1
	EndIf
EndFunc

```

**Comment by ghost** [comment]
Формат команды аналогичен НабратьИатаковать

НабратьИперенести
Набирает армию в генерала и переносит его в указанную позицию.

Написание для простых войск: НабратьИатаковать=Генерал, Порядок_генерала_в_звезде, Тип_войск, НОВОБРАНЦЫ, ОПОЛЧЕНИЕ, СОЛДАТЫ, Э_СОЛДАТЫ, Лучнии, Д_Лучники, Арбы, Кавалерия, Канониры, Куда_X, Куда_Y, Картинка_привязки, Куда_центровать_Х, Куда_центровать_Y, Если_вне_экрана_X, Если_вне_экрана_Y, [Опционально: НеЦентровать]
или для элитных: НабратьИатаковать=Генерал, Порядок_генерала_в_звезде, Тип_войск, МАСТЕРОСАДЫ, КС, СТРЕЛКИ, СБ, РЫЦАРИ, КМ, МЕЧНИКИ, Куда_X, Куда_Y, Картинка_привязки, Куда_центровать_Х, Куда_центровать_Y, Если_вне_экрана_X, Если_вне_экрана_Y, [Опционально: НеЦентровать]

Значения: 

Генерал - Название генерала, допустимые значения: Майор, Ветеран, Нинзя, Дракул, Генеральша, Золотой, Защитник, Жнец, Простой, Нусала, Варгус, Анслем, Медик, Ученый, Борис, Малец, Близнец, Сильвана, Стойкая, Скрытный
Порядок_генерала_в_звезде - каким по счёту находится генерал ДАННОГО типа в звездном меню. 
ВАЖНО!!! 
1) Указываем именно номер генерала данного типа, в 99% случаев это будет 1. Если, скажем, Нинзя звездном меню десятый по счёту, то указываем 1, ибо это первый ИМЕННО Нинзя.
2) Отсчёт начинаем с первого АКТИВНОГО генерала, Мёртвый, или на марше (серый) генерал не учитывается. Смотрим на примере Пиратов.
3) -1 означает последнего активного генерала
Тип_войск - П - простые, Э - элитные, 1 - проверяет наличие 1 ЛЮБОГО юнита и, если его нет, набирает 1 новобранца.
Имя_войска - сколько юнитов данного типа нужно набрать. Число 3000 - техническое и означает что указанных юнитов нужно добить до максимума. Действует только при максимальной прокачке на вместимость.
Куда_X,Куда_Y - координаты куда перенести генерала.
Картинка_привязки - скрин точки привязки в media/users в формате .bmp
Куда_центровать_Х,Куда_центровать_Y - позиция точки привязки в игровой зоне.
Если_вне_экрана_X,Если_вне_экрана_Y - как смещать карту в поиске картинки для привязки, например, если она не влезает в видимую область монитора. Не рекомендуется оставлять оба значения нулём.
НеЦентровать - Дополнительная (не обязательная) команда. Позволяет не перемещать точку привязки на координаты Куда_центровать_Х,Куда_центровать_Y, а переносить по текущему положению карты. Если точка переноса или точка привязки не видны, то данная команда не учитывается.

**Comment by jemxx** [comment]
Куда именно в файлах вставили? вставлю в теже места, что бы потом проблем при слияния веток не было

**Comment by ghost** [comment]
После набратьиатаковать и после атакалагеря
