### ISSUE TITLE
Wiki справка

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#17]
В своей Вики расширил описание нового автобота и добавил статьи в MySettlers на случай падения сайта.

**Comment by Marsik-A** [comment]
Перенесите, пож-та, мою вики-справку в основную ветку, и тогда я смогу прибить свою.

**Comment by ghost** [comment]
В прикрепленном архиве все файлы из моей вики-справки, включая нужные картинки. Если есть желание - обновите Вики в основной ветке, свою я прибиваю, тк неадекваты считают, что я веду свой "личный" проект с потыренными у всех идеями, которые я еще и криво кодирую.  

[Wiki.zip](https://github.com/jemxx/autobot/files/5340181/Wiki.zip)

**Comment by ghost** [comment]
Вики справка будет обновлена? или можно все это добро смело удалять?
