### ISSUE TITLE
Правки в релиз

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#21]
Я постараюсь сегодня к вечеру свести в один пост все правки к последнему релизу, чтобы ничего не забыть.

**Comment by jemxx** [comment]
Я то по мере появления добавлял все в код. За исключением отправки генералов. Я то делаю группу генералов.

**Comment by ghost** [comment]
Просто сверьте правки, чтобы ничего не забыть.

1. Из старого media\army_values вытащить файлы close.bmp и gotohome.bmp.
2. В конфиг добавить новых спецов и флаги для разведчиков на поиск приклов.
3. В коде поправить путь для набора одного юнита с media\1.bmp на  media\army_values\1.bmp
4. Поправить отправку по флагу 2 при наличии в генерале одного юнита.
5. Картинки с тикки tikki_in_zvezda.bmp и tikki_open.bmp перенести из media\ в media\users
6. Заменить функцию отправки разведчиков и обработку команды отправки
7. Заменить функцию отправки генералов в прикл
8. Заменить код функции отправки гены домой - старая не передергивает звезду  на начало. 
9. Подправить changelog (новые спецы, новый флаг для разведчиков) и справку по командам (добавить описание новой отправки разведов) - прикреплю архив чуть позже
[help.zip](https://github.com/jemxx/autobot/files/5182435/help.zip)

**Comment by jemxx** [comment]
1 +
2 +
3 +
4 +
5 +
6 +
7 +
8 +
9 +
10 +
11 +

**Comment by ghost** [comment]
Новые changelog и дополненная справка по командам в архиве к посту со списком.

**Comment by ghost** [comment]
10. Заменить частично функцию отправки геологов  
11. Возникла идея дополнить проверку слива на слив усилками. Я поскринил все усилки на тесте и нашел одно общее слово. Предлагаю заменить строчку в 
globalfuncWAR.au3 
в proverkasliva()

вот это 

`If _imagesearcharea("media\friend_atak.bmp", 1, $ax, 0, $ax + 300, $ay + 700, $tx, $ty, 30) = 1  Then
`

на это 

`If (_imagesearcharea("media\friend_atak.bmp", 1, $ax, 0, $ax + 300, $ay + 700, $tx, $ty, 30) = 1) or (_imagesearcharea("media\razgromili.bmp", 1, $ax, 0, $ax + 300, $ay + 700, $tx, $ty, 30) = 1) Then
`

скрин в аттаче
[razgromili.zip](https://github.com/jemxx/autobot/files/5190086/razgromili.zip)

И на этом прекратить)

**Comment by ghost** [comment]
И еще момент - обсуждаем в джаббере с одним из игроков команду ЖдемПобеду, у него не отработала она. Предлагаю для тестирования этой команды оставить вот такой текст с Tip-ом
Если окажется, что всплыващие окошки индивидуальны - придется команду убирать

```
func sleepwhile2($img, $time, $flag)
	local $i = 0, $tolerance = 30, $fl_win = 0
	while ($i < $time)
		If ((haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1)) Then
			$fl_win = 1
			TrayTip("", "Генерал победил", 0)
			Exitloop
		EndIf
		sleep(1000)
		$i = $i + 1
	wend
	if ($fl_win = 1) or ($flag = 1) then
		Return 1
	else
		Return 0
	endif
endfunc

```

**Comment by jemxx** [comment]
Остановитесь, хватит))

**Comment by ghost** [comment]
да все, это конец)) Тем более майсетлерс уже упал за неуплату)

И вообще мне кажется, если этим релизом можно зафиналить. А то дальше уже пошли такие хотелки-свистелки от тех, что глаза на лоб лезут. При этом "да, я далек от программирования, и не понимаю как это все устроено")
Спасибо Вам огромное, что подняли все это добро из руин!

ах, да! 
12. Вики из моей ветки перенесите еще в свою! и в ченжлог ссылку на вики-справку уже пора, раз сайт упал

**Comment by jemxx** [comment]
Вас я то же хочу поблагодарить. Вы сделали для бота очень много Больше чем я). Надеюсь наше дело будет жить и дальше...

**Comment by ghost** [comment]
Нене, Вы сделали самое главное - запустили эту музыку и прикрутили ко всему этому конфиг! Я так и не смог - раза 4 подступал и никак. Ну и направляли меня по тонкостям автоита

**Comment by LEKALA** [comment]
Я так понял, что это финальный релиз и дальнейшая разработка бота прекращена?

**Comment by ghost** [comment]
А чего Вам еще не хватает в боте? принципиально новых команд никто не обещал, новых спецов можно вносить через конфиг - для этого правка кода не нужна

**Comment by LEKALA** [comment]
Я в курсе, что новых команд никто не обещал. Конфиг спецов - это победа выше крыши!)) Но Вы не ответили на вопрос - разработка бота прекращена?
Команды не принципиально новые... Есть допустим команда набрать по коордам, есть команда атаковать по коордам, есть команда перенести по коордам... Но отсутствуют быстрые команды - набрать с поля и атаковать, набрать с поля и перенести, набрать с поля и отправить... Я думаю, вполне можно воспользоваться кусками кода автора для слияния их в каждую из желаемых команд...
Новой командой можно считать только команду - НажатьКнопку...
Но если никому это не нужно, то я готов и в будущем работать с этой финальной версией. Спасибо)

**Comment by LEKALA** [comment]
и да... Вы меня знаете, как ник Андрей)

**Comment by ghost** [comment]
Я вам на все это отвечал еще когда был жив майсетлерс) Те команды, которые Вы хотите - это как раз принципиально новые команды, их аналогов сейчас нет. Просто "воспользоваться кусками кода автора" нельзя - я Вам это тоже пытался объяснить. У автора зачастую для простого, казалось бы действия, использована целая цепочка команд, иногда даже рекурентная. Плюс у автора, на мой взгляд, очень нестандартная логика! Чтобы добавить простой флаг 2 для отправки гены в прикл, мне пришлось перепахать 4 или 5 функций, чтобы добраться до нужной, где этот флаг сработал.
Кстати у автора есть две недокументированные, но реализованные команды - Нажать 0 и ЗвездаВниз кажется, ЗвездаВниз=0 листает на одну строку, ЗвездаВниз=1 листает на целый экран (3 строки). 
Когда Jemxx брался за доработку бота, он вообще обещал только новых спецов добавлять, даже без конфига. Поэтому за эти 2.5 месяца бот "заметно похорошел" (с), не без помощи карантина и моего отпуска, ну и желания доделать то, чего лично мне очень сильно не хватало или что на мой взгляд старого программиста работало очень криво - например отправка за артами. Зафигом сначала жать на поиск сокровищ, а потом перепрыгивать на поиск артов!!! Это капец какой-то.
НажатьКнопку может сделаю в ближайшее время, тем более заготовка есть, надо слегка ее допилить. А вот для реализации тех команд, которые Вы хотите нужно сильно погружаться в код и логику автора, и сейчас у меня на это времени нет. Я не спорю, команды нужные, но не первоочередные.

**Comment by LEKALA** [comment]
Принято. Я считаю эту версию финальной. Работа Ваша и конечно jemxx выше всяких похвал!!! )) Это реально полный респект!)
Я просто писатель текстов, я просто пользуюсь функциями бота, которые прописаны... и готов и дальше пользоваться тем набором, что есть. Но согласитесь, что для того, чтобы набрать гену с поля и отправить в атаку, на этой версии нужно задать две команды... Набрать по коордам, атаковать по коордам... Обе этих команды кликнут в коорды, сделают своё и закроют окно гены. На этой процедуре мы теряем как минимум 3 сек на команду, 6 сек на две... Если их в прикле 10, то мы теряем от 30 сек до минуты... А можно поступать иначе, можно делать быстрее. И мне нравится делать логично и быстро) Как это делает человек... Вы же об этом думали, когда пытались писать код под отправку ген из таблички прикла?

**Comment by ghost** [comment]
Мне тоже нравится делать логично и быстро, и не множить код лишними строками) Поэтому все что можно было ускорить быстро и не особо ковыряя и вникая в код автора - все было ускорено. Как то - отправка разведов и геологов, отправка в прикл набранного гены одной командой, а не 2мя или 3мя, как было раньше и было подсмотрено у Вас же, отправка ген через окошко прикла (сейчас это делается в два раза быстрее, т.к. ищет сразу в 4х полях, а не в 2х, как было в исходном боте), еще мелкие улучшения кода. 
Я почти всегда слежу за тем, как работает бот - по крайней мере на первых нескольких проходах, чтобы понимать, где идет потеря времени, и я прекрасно понял, зачем Вам нужны новые команды. Это будут именно новый команды, а не можификация старых, как было с НабратьИперенести, т.к. в НаборПоКоординатам - это только набор и все, а АтакаПоКоординатам это тоже только атака и все. Плюс еще есть такой момент - НабратьИАтаковать при неуспешном наборе (зависшие песочные часы) выдаст ошибку. А вот НабратьПоКоординатам если зависнет на наборе, просто через какое-то время закроет гену, и значит следующая команда АтакаПоКоординатам будет атаковать тем составом, который был - а это слив. Т.е. по-хорошему и в НаборПоКоординатам и в НаборИАтакПокоординатам нужно добавлять проверку успешности набора, а это совсем другой функционал у этой команды, чем предусмотрено автором.         

Про код отправки из окна прикла - это все уже было у автора, просто у него было криво реализовано - самый первый раз гены искались в 1й и второй строках - 4 поля, а потом окно отправки листалось вниз на одну строку!!!! а искалось снова в 1й и 2й строках, а это бессмысленно, т.к. при пролистывании на **одну** строку, 2я строка становилась первой, а значит смысла снова в ней искать нет! Это логическая ошибка автора, которую я исправил!

**Comment by LEKALA** [comment]
Кстати сам факт использования для процедуры - набрать с поля и закрыть окно, потом открыть окно с поля и атаковать, нас, как юзеров бота, палит перед юбисофт... Живой человек так не поступает... и омрис вполне может выдвинуть нам обвинения по стабильному использованию именно таких действий в приклах... используя журнал сервера...
А у нас же нет цели спалиться перед юбисофт?

**Comment by ghost** [comment]
если Вы и здесь будете писать про Биги и Омриса, я перестану Вам отвечать!!!! 

Сайт mysettlers.ru был забанен в ру-зоне!! Поэтому кому надо - знают про бота, но ничего сделать с этим не могут. Не пишите чуши!

**Comment by LEKALA** [comment]
Я думаю Вы нагнетаете, это не в обиду! Проверка статуса конечно важна - она залог стабильности кода и радости юзера))
Но фишка в том, что бот автора предполагает полный набор операций с геной только из звезды... А мне нравится этот набор с поля. По двум причинам - так поступает человек, это быстрее и эффективнее. Второе - не нужно двигать карту! ваще не нужно никогда! Ибо двигать её приходится только из-за выбора гены в звезде (когда карта центруется на гену)
Норм текст на прикл должен выглядеть так: первая команда после перейти в прикл и всех манипуляций, предусмотренных ботом при переходе, д.б. - ЖмемПоКоординатам, чем и центруем карту
А потом работаем с генами только с поля! Не двигая карту вообще!!! Живые люди именно так и поступают.
Что касается омриса и биги, то это просто опасение, что версию этого бота тоже забанят во всех антивирусах... юбисофт легко заплатит лимоны баксов, чтобы такая опция в игре отсутствовала... а омрису и биги просто премия в 200 евро за бдительность))

**Comment by ghost** [comment]
Вы пишете полную херню про бан бота, что мешает внести бота в исключения? даже для проги активации Винды это можно, а не что с каким-то левым ботом - это раз! Два я уже писал, что майсетлерс забанен в ру зоне - попробуйте послать хоть кому-то ссылку на mysettlers.ru - адресат получит *** и не более. Поднимать все логи, чтобы вычислить ботоюзера - это слишком хлопотно, ТП даже мультов ловит по стуку, а там куда как проще отследить бафы и торги между акками, поэтому давайте завязывайте уже с этой паранойей. 

По поводу "как делает человек", увы, но бот НЕ человек! Очень похоже, что Вы очень далеки от программирования, поэтому погуглите известный программисткий анекдот - каков будет алгоритм набора воды в чайник и кипячения его, очень удивитесь.
И я не нагнетаю, у меня "на руках" анализ стопов бота за 2 года активной работы с ним, поэтому я знаю о чем пишу.
Именно что для человека дело полсекунды, боту надо 3-5-10 секунд, чтобы сделать какую-то рутину именно потому что человек анализирует что видит мгновенно, и чуть меняет порядок своих действий, а бот так не умеет - он **не видит** ошибки, если его этому не научить. Вот и сейчас с поля он умеет только набирать и атаковать, все!!! Хотите - берите код, он же вот есть у Джемхх-а и учите бота чему хотите!

PS если Вы во всех местах напишите, как было бы удобно, чтобы бот работал с генами из поля, бот этому не научится! Вы итак написали уже везде где можно, и тут в трех сообщениях. Зачем?

**Comment by LEKALA** [comment]
Да. ничего не стоит)) только это нужно объяснить подруге) И самое главное объяснить зачем! )) Она очень боится вирусни ибо торгует на биржах... Вот я и трачу вечера, отдаю все свои зубы, чтобы подруга решилась использовать некий .ехе, который и микрософт и гугля щитают вирусом...( а то, что юзер вместо mysettlers.ru получит три звёздочки (***) я знаю) и этот бан точно так же угрожает и этому боту... важен стукачок в юбисофт... 
Ваш финальный абзац я понял. С ботом покончено. Далее я сам буду ковыряться в коде исходников. Может и получится)
Вы правы только в одном - я не умею писать код) По простой причине - не изучал синтаксис и пунктуацию. Но вовсе не факт, что не найду времени изучить) А вот логика у меня есть, и не злитесь, пжлста, на этот факт? А у кого есть логика, тот вполне может справиться с кодом... Это не трудно, просто требует времени. И да! лучше этим заниматься с людьми, которые этого хотят..
А написал я затем, что Вы так бодро упираетесь, что возникает впечатление, что Вы не заинтересованы в эффективной работе бота...

**Comment by ghost** [comment]
тьфу! Я понял, что Вы не читатель а писатель. Если бы я бодро упирался, хрен бы Вы получили бОльшую часть кода нового бота, можете спросить Джема! 
Успехов Вам в ковырянии исходников!

**Comment by LEKALA** [comment]
А Вам всё равно благодарность!)) То, в какое состояние Вы привели эту прогу (бота), просто потрясает! Я реально благодарен Вам за усилия и потраченное время)) Результат очень хорош и впечатляет! Мало того он стал значительно юзабельнее!)) Спасибо Вам и **jemxx** !!! Отличная работа! ))

**Comment by jemxx** [comment]
Активная часть разработки завершена, но это не значит, что Автобот заброшен. Я как минимум буду добавлять новых спецов, что вы и без меня можете делать. Что касается новых функций, то можно добавить если это действительно нужно, а не различные хотелки типа мне это нужно. Прошу понять что мы тратим на это свое время и делаем если только хотим. Код открыт, делайте форки, добавляйте что хотите

**Comment by ghost** [comment]
Блин, вымораживает, когда такие вот "я ни разу не программист"-ы и те, кто кода в глаза не видел - начинают рассказывать, как легко добавить новый функционал.
Один буковки хотел перед армой, потому что ему так удобнее. Второй советовал "А зачем знать, чем юзер слился, достаточно факта, что слился", третий вот "это не трудно, просто требует времени". Я хз как Jemxx, но я до фига потратил времени, чтобы хотя бы частично понять, что именно думал автор, когда писал **_ТАКОЙ_** код. При том, что я и программист с 35ти летним активным стажем, и в игре и ботоюзерстве не один год. И это я еще не лез примерно в половину команд бота, в тот же набор армы. Спасибо Джему - это тупое поведение с 0 исправлено.
А еще больше вымораживает, что несмотря на то, что ссылка на гитхаб давно была указана в ченжлоге, все сидели и ждали, пока новость на майсетлерс появится, а потом еще и ссылку на облако мейл-ру просили, т.к. не сохранили. А щас все, майсетлерс лег, а у меня желания жевать и класть в рот готовое все меньше и меньше.      
Автор выдал бота as is, и когда еще эпизодически появлялся на сайте и общался с юзерами, на все мои просьбы типа "а сделайте автопанду/автосвадьбу или набратьИперенести - это же 10 мин дел" отвечал "а зачем? юзайте жмем/ждем/жмемиждем картинки, все же итак работает да криво, да с лишними кликами, но работает же".

**Comment by LEKALA** [comment]
Это Вы мне? или просто жалуетесь на жизнь, Marsik-A ? Чем я Вас так задел? Вроде же написал, что ощущаю полный респект к тому, как бот, Вашими усилиями выглядит сейчас. Я допустил бестактность? Прошу меня извинить за это, но всё на что Вы пожаловались Вам писали другие люди...
