### ISSUE TITLE
Команда "НаборИатакаПоКоординатам"

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#23]
Если кому-то тут интересны новые юзерские команды для бота, то вот накалякал тут одну)) Называется "НаборИатакаПоКоординатам". Суть её в том, чтобы найти гену на карте прикла по координатам, кликнуть в него, зарядить и отправить в атаку на координаты врага. Команда аналогична "Набрать и атаковать", только гена берётся не из звезды, а с поля боя. Примеры команд для разных типов войск:
НаборИатакаПоКоординатам=Генеральша,Э,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,0,168,0,0,0,3000,0,-292,194,НеЦентровать
НаборИатакаПоКоординатам=Генеральша,1,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,1,0,0,0,0,0,0,0,0,-292,194,НеЦентровать
НаборИатакаПоКоординатам=Генеральша,П,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,3000,0,0,0,0,0,0,0,0,-292,194,НеЦентровать
Для этого пришлось накалякать новую функцию в файле globalfuncWAR.au3 - openGenaOnpxp($img, $k_x, $k_y, $else_x, $else_y, $otkudax, $otkuday). Эта функция почти аналогична функции от Vasuta - clickOnCoordinates($img, $k_x, $k_y, $else_x, $else_y, $kudax, $kuday), только в неё добавлено ожидание картинки "media\Ataka.bmp".
Скомпилированный файл Autobot.exe находится тут: https://drive.google.com/file/d/1TzFrX9bCtHAePjkw2U4uzL-Xy1f9aD1w/view?usp=sharing
Переименуйте свой Autobot.exe, а потом скопируйте в папку с последней версией автобота мой файлик и попробуйте его потестировать. Жду ваших отзывов и замечаний))
Да! Забыл доложить - я ессна протестировал эту функцию у себя в юдабе, во всех режимах. У меня всё работает, как и задумывалось) 😏

**Comment by ghost** [comment]
Ну мы здесь постим код, который потом Jemxxa добавляет в основную ветку, а не тестируем екзешники)
У меня, допустим, есть куча лично мне нужных фич в моей версии, поэтому не вижу смысла отказываться от них и юзать чужой екзешник. А вот добавить в свою версию Ваш код и проверить как работает - почему бы и нет. 

PS clickOnCoordinates не моя команда, а Jemxxa-а
PPS и по Вашей ссылке выдает вот так, кстати 

![image](https://user-images.githubusercontent.com/64967268/94431002-6c18f400-019d-11eb-80ef-cdba435e0034.png)

**Comment by LEKALA** [comment]
Просто хотел выяснить интерес к данной функции. Очевидно, что интерес присутствует.) 
### **Теперь здесь представлена финальная версия кода**
с последней согласованной разработчиками версией синтаксиса,
с изменённым таймингом в цикле ожидания с 10 сек на 6 сек в функции openGenaOnpxp.
Поэтому: Добавить новую функцию в файл globalfuncWAR.au3

```
Func openGenaOnpxp($img, $k_x, $k_y, $else_x, $else_y, $otkudax, $otkuday)
	Local $tx = 0, $ty = 0, $i = 0

	Sleep(500 * $tormoza)

	If ($centrovat = 0) AND (_imagesearch($img, 1, $tochka_sektora_x, $tochka_sektora_y, read_ini(1)) = 1) Then
		If (200 < ($tochka_sektora_x + $otkudax)) AND (($tochka_sektora_x + $otkudax) < (@DesktopWidth - 200)) Then
			If (200 < ($tochka_sektora_y + $otkuday)) AND (($tochka_sektora_y + $otkuday) < (@DesktopHeight - 200)) Then
				$centrovat = 1
			Else
				$centrovat = 1
				If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
			EndIf
		Else
			$centrovat = 1
			If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
		EndIf
	Else
		$centrovat = 1
		If find_sektor($img, $k_x, $k_y, $else_x, $else_y) = 0 Then Return 0
	EndIf

	$otkudax = $tochka_sektora_x + $otkudax
	$otkuday = $tochka_sektora_y + $otkuday

	While (_imagesearch("media\zadacha_geni.bmp", 1, $tx, $ty, 20) = 0) AND ($i < 20)
		MouseMove($otkudax, $otkuday, 10 * $tormoza)
		Sleep(200 * $tormoza)
		MouseClick("left", $otkudax, $otkuday, 1)
		go5()
		sleepwhile("media\Truba.bmp", 30, 6)
		$i = $i + 1
	WEnd
	If $i = 20 Then
		Return 0
	EndIf
	
	Return 1
EndFunc
```

а этот код добавить  в обработку команд:

```
Case "НаборИатакаПоКоординатам"
			$centrovat = 1
			Local $perebor = 1
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd
			
			$generalData = getGeneralData($parametr[1])
			$gena = $generalData[0]
			$full = $generalData[1]
			
			If openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8]) = 1 Then
				If $parametr[11] = "Э" Then
					While apply_elitnoy_army($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return atakalageraotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
				EndIf
				If $parametr[11] = "1" Then
					If haveimage("media\army_values\1.bmp", 20) = 1 Then
						Return atakalageraotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
					Else
						While applyarmy($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19], $parametr[20], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
						WEnd
						$gluksnaboromarmii = 0
						Return atakalageraotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
					EndIf
				EndIf
				If $parametr[11] = "П" Then
					While applyarmy($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19], $parametr[20], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return atakalageraotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
				EndIf
			Else
				Return 0
			EndIf	
```

А с гуглодиском да... буду разбираться, в чём проблема...

**Comment by jemxx** [comment]
> А с гуглодиском да... буду разбираться, в чём проблема...

Видимо название файла не нравится. У меня там тоже удалялись файлы, поэтому стали на мыло заливать.

**Comment by LEKALA** [comment]
Да. Я тоже это заподозрил. Название файла по-прежнему находится в чёрных списках у гугля...(((
Проверял свой файл злым антивирем, который ессна ничего не нашёл... а гугля паникует((
Попробую просто назвать файл вместо autobot.exe например karakalpak.exe и посмотрю на реакцию гуглодиска. Спасибо за инфу.)

**Comment by ghost** [comment]
Открою вам большой секрет - "гугля паникует" на любой exe-шник! Пакуйте его винраром к примеру.

И код бы оформить аккуратнее, а то не видно, где начало где конец

**Comment by LEKALA** [comment]
Я и паковал раром... Вы какой файл обнаружили, нарушающим политику гугли, по моей ссылке? Разве не .rar?
Код оформлял средствами местного чата - выбрал иконку "insert code" и вставил между апострофами весь кусок кода, скопированного из нотепада++.... Почему мотор чата так распихал строки кода, мне не ведомо((

**Comment by ghost** [comment]
я не знаю, какой файл - я нажал на ссылку, и увидел картинку, которую и выложил сюда. Я хз че там было-то

Ну значит неаккуратно затегали, что часть кода вышла "из-под контроля"

А почему последний Return 1 закоментарен?

**Comment by LEKALA** [comment]
он не нужен типа... функция и так возвращает единицу, когда дождётся картинки атака.бмп
кстати, тут я наверное не прав, если гена пустой, то эта картинка возможно и не появится... завтра заменю её на труба.бмп.

**Comment by ghost** [comment]
Я понял почему код так криво вставился - надо вставить пустые строки 
`
Case "НаборИатакаПоКоординатам"
`

Где апострофы - теги кода, добавьте по пустой строке, и тогда все норм будет

**Comment by LEKALA** [comment]
т.е. копировать из нотепада с пустыми строками сверху и снизу?

**Comment by ghost** [comment]
Да копировать можно без них, просто добавить по одной пустой строке сверху и снизу,  а потом только обрамлять тегами кода

**Comment by ghost** [comment]
Проще заново код вставить)

**Comment by LEKALA** [comment]
вставил по строке... ентером... не помогло((

**Comment by ghost** [comment]
заново вставьте код с пустыми строками и затежьте

**Comment by LEKALA** [comment]
ОК, щас попробую...

**Comment by LEKALA** [comment]
О! похоже, что получилось! ))

**Comment by ghost** [comment]
Ну да, так гораздо лучше)

Как мне кажется, последний закоменченый return должен быть с 0 под else . Eсли команда

```
If openGenaOnpxp.... 

else Return 0
endif

```
не выполнится, то должна вывалиться ошибка

**Comment by LEKALA** [comment]
так я думал, что ошибка обрабатывается этим нулём:

```
    Else
	   Return 0
    EndIf
EndIf	
;Return 1	
```
я не прав? Помогите сделать правильно, пжлста?

**Comment by LEKALA** [comment]
или тогда вообще убрать

```
Else
       Return 0
```
оставить просто так?
 ```
        EndIf
EndIf	
Return 0

```

**Comment by ghost** [comment]
> так я думал, что ошибка обрабатывается этим нулём:
> 
> ```
>     Else
> 	   Return 0
>     EndIf
> EndIf	
> ;Return 1	
> ```
> 
> я не прав? Помогите сделать правильно, пжлста?

не, этот else обработается если не выполнится условие 
```
If $parametr[2] = "П" Then

```
т.к. он только к нему. Его скорее надо убрать, и оставить финальный  else с Return 0
Он обработается, если команда открытия гены не сработает

Но у ней у вас нет варианта, когда она не сработала, и вернулся 0. Там тоже закоментено Return 0
А нет, сорьк, есть. 20 кликов и если не открылся, то вывалится ошибка. А вот эта самая ошибка нигде в основной ветке не обрабатывается


```
If openGenaOnpxp ...
...
Else	
    Return 0
EndIf

```

Мне кажется, вот так правильнее будет. Если гена не открылся по опенГена, то вывалится ошибка

**Comment by LEKALA** [comment]
Вот так?

                                Return atakalageraotkritimgenoynoini($parametr[19], $parametr[20], $userDIR & $parametr[3], $parametr[4], 
                                $parametr[5], $parametr[6], $parametr[7])
				EndIf
                        Else
				Return 0
		        EndIf

**Comment by ghost** [comment]
да, наверное так самое верное.
Return atakalageraotkritimgenoynoini вернет 0, если атака не удалась, а значит все if-ы вида If $parametr[2] = "..." будут обработаны корректно, а финальный else закроет неуспешное открытие гены по корам

**Comment by LEKALA** [comment]
Спасибо) Завтра исправлю, скомпилирую и погоняю в прикле.

**Comment by ghost** [comment]
можно проверить так - попробуйте выполнить эту команду на гене, который еще не доехал до места $otkudax, $otkuday, тогда должна вывалиться ошибка

**Comment by LEKALA** [comment]
я наоборот сделал 20 кликов, чтобы гена успел доехать)) это формально подменяет команду ЖдемГенерала...
чтобы проверить обработку этой ошибки нужно поставить 5 кликов или даже 3...

**Comment by ghost** [comment]
я сейчас не про успешность выполнения команды, а про правильность обработки ошибки.

**Comment by LEKALA** [comment]
Я понял.)

**Comment by ghost** [comment]
> я наоборот сделал 20 кликов, чтобы гена успел доехать)) это формально подменяет команду ЖдемГенерала...
> чтобы проверить обработку этой ошибки нужно поставить 5 кликов или даже 3...

ЖдемГенералапоКорам тоже теперь легко реализовать - вызывайте openGenaOnpxp() в цикле до появления картинки тех же мечей или труб

**Comment by LEKALA** [comment]
Именно такого подхода и придерживаюсь. На базе openGenaOnpxp() ещё планирую сделать почти идентичный кейс НаборИпереносПоКоординатам, чуть другой кейс НаборПоКординатамИотправка и совсем простой ОтступитьПоКоординатам (ВыбратьПоКоординатамИотступить)..

**Comment by jemxx** [comment]
В сообщении выше итоговый код команды?

**Comment by ghost** [comment]
LEKALA должен проверить, как работает. и по-моему нет, не финальный, без учета последних коментов по Return 1/0

**Comment by jemxx** [comment]
Я тестировать эту команду не буду. Не вижу ей применение. Даже сложно представить ситуацию когда она действительно нужна.

**Comment by ghost** [comment]
ну LEKALA хочет чтобы бот как человек кликал по генам на карте, а не из звезды. Теоретически, если бы такая команда была бы раньше, то может и нашлось бы ей применение в тех случаях, когда ген воюет больше двух одинаковых, например, две Сильваны. И тогда каждая била бы свои лагеря напрямую, а не через звезду. Но сейчас когда все основные проходы написаны я тоже не вижу смысла переписывать боевку и логистику. Тем более, что первое, на мой взгляд, с чего надо было бы начать - это аналог команды НаМесте - проверка, дошел ли гена до нужного места. А так "запасные 20 кликов" это костыли под свои тайминги, а не универсальная команда для всех.

**Comment by jemxx** [comment]
> А так "запасные 20 кликов" это костыли под свои тайминги, а не универсальная команда для всех.

Ну если LEKALA допилит команду для всех, можно будет ее добавить. Пригодится кому-нибудь.

**Comment by ghost** [comment]
Нужна команда ЖдемГенералапоКоординатам  по аналогии ЖдемГенерала в звезде, но я не увидел такой команды в планах   LEKALA.

**Comment by LEKALA** [comment]
Проверил работу на своей финальной версии кода. Опубликовал код в своём втором сообщении в этой теме.

**jemxx,**
> Я тестировать эту команду не буду. Не вижу ей применение. Даже сложно представить ситуацию когда она действительно нужна.

Применение аналогично применению команды из звезды НабратьИатаковать. Без этой команды сейчас бот находит на карте нужного гену, кликает в него, выбирает войска, заряжает войска, применяет, закрывает окно гены (это команда НоаборГеныПодАтаку), потом немного ждёт, снова находит на карте этого же гену, кликает в него, открывает окно гены, выбирает кнопку с мечами (окно гены закрывается), бот наводит мечи на лагерь врага, бот кликает...
С данной командой бот пропускает: закрытие окна гены после набора, секундный слип, новый поиск гены, клик в гену, открытие окна гены, на чём экономит не менее ТРЁХ секунд.) Если таких действий в прикле 10-20, то на использовании данной команды имеем экономию времени от 30 до 60 секунд. Вот поэтому эта команда мне и нужна. По аналогии можете обмыслить вариант, если бы не было команды НабратьИатаковать, а вместо неё приходилось бы пользоваться командами Набрать (в звезде) и Атаковать (из звезды), и допустим в случае, когда бот в звезде под набор выбрал одну генеральшу, а в это время вернулась допустим третья... 

**Marsik-A,**
> Нужна команда ЖдемГенералапоКоординатам по аналогии ЖдемГенерала в звезде, но я не увидел такой команды в планах LEKALA.

Дело в том, что ожидание гены по координатам предстаёт перед нами в двух ипостасях. Нам нужно ждать гену из переноса - т.е., когда он придёт на координаты и успеет построиться и стать активным.... (окно гены при этом от клика не открывается) И нам нужно ждать гену из атаки, когда окно гены при клике открывается, но висит табличка или атака, или возвращение, и кнопки действий не активны.
Предложенная команда как раз и решает обе эти задачи - кликает в коорды ещё не построенного гены с задержкой в 10 сек целых 20 раз (итого 200 секунд, возможно стоит снизить ожидание между кликами до 6 сек)
и вторую задачу - кликает в коорды атакующего гены, открывается окно гены и бот ждёт, пока кнопки действий станут активными. Цикл с этим ожиданием в коде уже представлен... Возможно я просто не уловил Вашу мысль, чего именно Вы ждёте от предложенной Вами команды ЖдемГенералапоКоординатам? Какого именно поведения от бота Вы ждёте с этой командой?
На этом видео можно посмотреть, как в прикле работает моя команда и поведение бота и ожидания:
https://c2n.me/49gLId0

**Comment by ghost** [comment]
LEKALA Вы уже 4 раза написали в разных местах, как Вам нужна реализованная команда, зачем было писать 5й?))))))

Дальше по логике написания прохода. Если Вы хотите чтобы бот играл как человек. Как играет человек, ну или хорошо, возможно я один такой тупой, но руками я играю так: жду, когда генерал придет в нужную точку, неважно откуда - из переноса или вернется из боя, загружаю его нужной армой и если это не отвал, шлю его в бой, так?
Как мы это реализуем средствами бота - ЖдемГенерала (в звезде, больше нигде бот не умеет ждать), НабираемПоКорам, и АтакуемПоКорам. Да, Ваша команда сливает две команды в одну, но с чего Вы взяли, что у вас интервал между кликами 10 секунд?
Вот Ваша команда ожидания что гена готов для действий.

```
While (_imagesearch("media\zadacha_geni.bmp", 1, $tx, $ty, 20) = 0) AND ($i < 20)
		MouseMove($otkudax, $otkuday, 10 * $tormoza)
		Sleep(200 * $tormoza)
		MouseClick("left", $otkudax, $otkuday, 1)
		go5()
		sleepwhile("media\Truba.bmp", 30, 10)
		$i = $i + 1
WEnd
```
Откуда Вы взяли про 200 секунд?

MouseMove($otkudax, $otkuday, 10 * $tormoza) - третий аргумент, это скорость с которой переместится курсор мыши.
Sleep(200 * $tormoza), 200 это время в **мили**секундах, причем умноженный на параметр тормоза, у меня он равен 0.3. Значит по этой функции время между кликом мыши и ожиданием труб  200*0.3 = 60 милисекунд
И счетчик похоже никогда не нарастится, т.к. стоит функция sleepwhile("media\Truba.bmp", 30, 10) - т.е. пока картинка труб не будет активной, следующая команда не выполнится. А как только она будет активной, бот выйдет из этого while. Т.е. по сути у Вас бот всегда ждет пока гена может что-то делать.

**Comment by ghost** [comment]
Ну и мой внутренний зануда говорит, что логичнее вместо 
НаборИатакаПоКоординатам=Генеральша,Э,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,0,168,0,0,0,3000,0,-292,194,НеЦентровать

было бы писать

НаборИатакаПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,-292,194,НеЦентровать


т.е. состав армы после указания ее типа

**Comment by ghost** [comment]
```
While (_imagesearch("media\Truba.bmp", 1, $tx, $ty, 20) = 0) AND ($i < 20)
		MouseMove($otkudax, $otkuday, 10 * $tormoza)
		Sleep(200 * $tormoza)
		MouseClick("left", $otkudax, $otkuday, 1)
		go5()
		$i = $i + 1
WEnd
```

Вот такой код будет кликать до 20 раз с интервалом 200 миллисек*тормоза до появления активной картинки с трубами

**Comment by LEKALA** [comment]
> LEKALA Вы уже 4 раза написали в разных местах, как Вам нужна реализованная команда, зачем было писать 5й?))))))

**jemxx** не понимает зачем и почему эта команда полезна, вот я и пытался объяснить уважаемому человеку, с рекламными выкладками)
Вам удалось посмотреть видео?
Я так понял, что в синтаксисе функции sleepwhile("media\Truba.bmp", 30, 10) последняя цифра это 10 секунд, без тормозов.
и у меня в коде прирост счётчика $i как раз после этих 10 сек

**Comment by LEKALA** [comment]
Насчет синтаксиса... В команде много параметров, я боялся и боюсь в них запутаться. С учётом того, что команда начинается с вызова функции openGenaOnpxp, и выставил параметры этой функции первыми (с 3-го по 9-й). По моему вполне логично и в части писания кода удобнее и проще.
Если состав войск будет указан до параметров функции openGenaOnpxp, то при разном кол-ве параметров состава для Э и П (7 и 9) номера параметров функции openGenaOnpxp будут меняться, а это сильно усложнит код...

**Comment by ghost** [comment]
Вы Jemxx-у это уже объясняли в прошлые разы, зачем еще раз-то?
Если он не пользуется набором с карты, а Вы пользуетесь - то у вас явно разная логика написания проходов.
По поводу 10 секундного ожидания, да пожалуй я не прав. Там через 10 сек счетчик нарастится и снова зайдет в цикл while-а
А по синтаксису Вы же все равно вызываете openGenaOnpxp в соответствующем условии для Э, П и 1 с разными параметрами по порядку, написать на листочке и пронумеровать, и тогда не запутаетесь. Просто для Вас так проще - не запутаться в коде, а для тех кто будет юзать эту команду с 0, ни фига не проще - тип армии в начале, а состав в конце, да еще и между двумя парами координат - откуда и куда. Присмотритесь - у вас идет картинка привязки, потом пара куда центровать, пара куда двигать, пара координат откуда, состав армии, пара координат куда.

**Comment by ghost** [comment]
А как ведет себя Ваш код, если генерал только переезжает на нужные координаты?

**Comment by LEKALA** [comment]
Если гена идёт на координаты, с которых эта команда будет его открывать и набирать и отправлять в атаку, то пока гены нет на координатах, бот будет кликать 20 раз в эту позицию с задержкой приблизительно 10 сек, т.е. имитировать ожидание.
Мы же вроде уже это обсуждали? или я не правильно понял Ваш вопрос... Готов сделать видео, и Вы там всё можете увидеть.

**Comment by ghost** [comment]
да я уже по коду разобрался

**Comment by LEKALA** [comment]
Поменял, по совету разработчиков, код с целью реализации более дружественного для юзера синтаксиса. Теперь синтаксис выглядит так:
НаборИатакаПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-292,194,1,1,0,0,0,0,0,0,0,0,НеЦентровать
НаборИатакаПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-561,75,-292,194,Э,0,168,0,0,0,3000,0,НеЦентровать
Проверил правильную работу в игре - всё ОК.))
Дополнительно в функции openGenaOnpxp изменил тайминг в цикле ожидания с 10 сек на 6 сек.
