### ISSUE TITLE
Прога съема координат

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#24]
По наводке одного из участников чата в дисмейле декомпилировал прогу съема кор, чтобы заменить пути с точками привязок (army_values) на актуальные (users). Но после обратно компильнуть этот код уже не удалось. Планирую, как разгребусь - перенести нужные куски кода в новый проект и сделать уже нормальную прогу съема, без костылей. И тогда можно будет добавить в папку с полным архивом бота.

**Comment by jemxx** [comment]
> Но после обратно компильнуть этот код уже не удалось

Какие проблемы возникли? Тоже была такая идея...

**Comment by ghost** [comment]
Не хочет - пишет кучу ошибок, я пару потер да и пока плюнул, времени нет. Проще в новый проект нужное вставить, там гуи и две команды всего. Ну и одна функция поиска картинки

**Comment by jemxx** [comment]
Будет желание, пишите ошибки, помогу, чем смогу, разобраться

**Comment by ghost** [comment]
Да ошибки там в необъявленных функциях, сидеть тупо и тереть лишнее скучно, проще взять нужное и вставить в новый файл. Просто после декомпиляции там все в кучу же в один au3 файл. Хотите, скину декомпилированный au3?

**Comment by jemxx** [comment]
Мне кажется, все функции по съему координаторов есть в коде автобота (Наводку даю), Не думаю, что автор что то бы новое там придумал. Нужно только интерфейс нарисовать.  Мы же каждый раз работаем с функцией которая возвращает координаты.

**Comment by ghost** [comment]
да я даже примерно понимал, как он ищет точку привязки с повышением шага для tolerance на 5 до успешного или неуспешного нахождения, просто время надо на это все. 
А щас и гуи есть и все функции в декомплилированном файле

**Comment by ghost** [comment]
Все, вычистил. В архиве исходник, иконка и экзешник. Теперь картинку точки привязки ищет в папке media\users. Для работы нужна Globalfunc.dll. Можно помещать экзешник в общий архив с ботом.
[Coords.zip](https://github.com/jemxx/autobot/files/5306183/Coords.zip)
