### ISSUE TITLE
Новая команда "НаборИпереносПоКоординатам"

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#25]
Эта команда написана в полной аналогии с командой "НаборИатакаПоКоординатам". В коде используется вызов функции **openGenaOnpxp**, а вывод заменён на вызов функции **perenosotkritimgenoynoini** вместо **atakalageraotkritimgenoynoini**
Пример синтаксиса:
НаборИпереносПоКоординатам=Генеральша,Э,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,0,168,0,0,0,3000,0,-561,75,НеЦентровать

Этот код добавить в обработку команд:

```
Case "НаборИпереносПоКоординатам"
			$centrovat = 1
			Local $perebor = 1
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd
			
			$generalData = getGeneralData($parametr[1])
			$gena = $generalData[0]
			$full = $generalData[1]
			
			If openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8]) = 1 Then
				If $parametr[11] = "Э" Then
					While apply_elitnoy_army($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
				EndIf
				If $parametr[11] = "1" Then
					If haveimage("media\army_values\1.bmp", 20) = 1 Then
						Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
					Else
						While applyarmy($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19], $parametr[20], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
						WEnd
						$gluksnaboromarmii = 0
						Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
					EndIf
				EndIf
				If $parametr[11] = "П" Then
					While applyarmy($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $parametr[19], $parametr[20], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
				EndIf
			Else
				Return 0
			EndIf	
```

**Comment by Marsik-A** [comment]
И снова у Вас неверный синтаксис, где-то пропущен параметр типа армии П, Э или 1

**Comment by ghost** [comment]
Аналогичное замечание по синтаксису 
Не НаборИпереносПоКоординатам=Генеральша,Э,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,0,168,0,0,0,3000,0,-561,75,НеЦентровать

а 

НаборИпереносПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать

**Comment by jemxx** [comment]
Полностью согласен по синтаксису. Вариант Marsik-A более дружелюбен.

**Comment by ghost** [comment]
Тут дело не в боязни запутаться, а в "логике" автора исходного бота. Команда - калька с команды НаборГеныПодАтаку.
И там тоже аналогичный синтаксис: тип армы, инфа по т.п. и корам гены, состав армы. И  т.к. число войск в простой и элитной арме разное, то инфу по точке привязки, центровке и паре если_вне_экрана перенести в конец, то надо писать два разных блока. Как альтернативу, можно предложить такой синтаксис
НаборИпереносПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,Э,0,168,0,0,0,3000,0,НеЦентровать
Тогда правки кода будут минимальными, но потеряется единообразие с командой НаборГеныПодАтаку

**Comment by LEKALA** [comment]
**Marsik-A**, Вы абсолютно правы!) Я честно, когда только начинал работать над командой "НаборИатакаПоКоординатам"
хотел использовать удобный и понятный для юзера синтаксис, типа НаборИпереносПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать.
Но как раз и столкнулся с проблемой разного количества параметров для случаев Э и П, что очень мешало использованию такого синтаксиса. Автор бота вообще для решения этого парадокса написал три функции...))
Ваш последний вариант синтаксиса действительно не потребует изменений кода, только перенумеровать параметры, и это совсем не трудно сделать.) Этот синтаксис действительно более дружелюбен к юзеру? Стоит менять код под этот синтаксис? Я готов для обеих команд - "НаборИатакаПоКоординатам" и "НаборИпереносПоКоординатам"))

**Comment by jemxx** [comment]
Меняйте конечно и затем я смогу добавить ваши команды в основную ветку

**Comment by LEKALA** [comment]
Хорошо. Завтра поменяю код.)

**Comment by LEKALA** [comment]
Поменял, по совету разработчиков, код с целью реализации более дружественного для юзера синтаксиса. Теперь синтаксис выглядит так:
НаборИпереносПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,Э,0,168,0,0,0,3000,0,НеЦентровать
НаборИпереносПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,П,20,0,0,0,0,0,0,0,0,НеЦентровать
В реальном прикле в игре проверил правильность работы. Всё ОК))

**Comment by jemxx** [comment]
Уже лучше)) но немного не то)

**Comment by LEKALA** [comment]
Что не так? Где затыки?

**Comment by ghost** [comment]
Я тоже думал над этим всем, в идеале надо бы переписать все ж под 
такой формат 
НаборИпереносПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать
НаборИАтакаПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать

А для совместимости с оригинальной версией бота переписать команду НаборГеныПодАтаку под новый формат, но назвать ее
НаборПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,НеЦентровать

для этого слегка переписать код
Вместо

```
If openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8]) = 1 Then
	If $parametr[11] = "Э" Then
		While apply_elitnoy_army($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 0) <> 1
			zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
			openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
		WEnd
			$gluksnaboromarmii = 0
		Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
        EndIf
	If $parametr[11] = "П" Then


	If $parametr[11] = "1" Then

	
EndIf
	
```


Написать три таких блока с нужными номерами параметров

```
If $parametr[11] = "Э" Then
    If openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8]) = 1 Then
		While apply_elitnoy_army($parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 0) <> 1
			zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
			openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
		WEnd
			$gluksnaboromarmii = 0
			Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])
    EndIf
EndIf




```

**Comment by LEKALA** [comment]
Написать три блока?!! Как это и сделал автор исходного бота? И вы это называете упрощением кода?...
Разве финальный не работает? и он не красив? 
Вам перестало нравиться Ваше последнее предложение по синтаксису?
НаборИпереносПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,Э,0,168,0,0,0,3000,0,НеЦентровать
Зачем Вы тогда его предлагали? Чисто погонять засранца? (((

**Comment by ghost** [comment]
Вы не поняли, я не говорю об упрощении кода, я говорю об упрощении написания команд для бота пользователями.
Да как автор три ифа, только по-человечески, а не на отъ...сь, т.к. "мне лень нормально описать все параметры, а юзер схавает все"

Все три условия никуда не денутся, просто поменяются местами проверка на тип армии (будет идти первой) и проверка открыл ли гена по корам (будет идти 2й). 

У меня код еще проще - я вынес вот эти две команды за иф-ы и все работает

```
$gluksnaboromarmii = 0
Return perenosotkritimgenoynoini($parametr[9], $parametr[10], $userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6])

```

Мое предложение мне и раньше не нравилось, и даже в исходной версии бота, т.к. этот синтаксис НЕ очевиден для пользователя. Я предложил его как вариант с минимальными правками кода и как сходный по написанию с уже имеющейся командой НаборГеныПодАтаку, которая тоже кривая по синтаксису

**Comment by ghost** [comment]
Вот  пример дружественного пользователю кода

```

		Case "НаборИатакаПоКоординатам"
			$centrovat = 1
			Local $perebor = 1
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd
			$generalData = getGeneralData($parametr[1])
			$gena = $generalData[0]
			$full = $generalData[1]
			If $parametr[2] = "Э" Then
				If stoitligenaopen($userDIR & $parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16]) = 1 Then
					While apply_elitnoy_army($parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						stoitligenaopen($userDIR & $parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16])
					WEnd
					$gluksnaboromarmii = 0
					Return perenosotkritimgenoynoini($parametr[17], $parametr[18], $userDIR & $parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14])
				Else
					Return 0
				EndIf
			EndIf
			If $parametr[2] = "1" Then
				If stoitligenaopen($userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18]) = 1 Then
					If haveimage("media\army_values\1.bmp", 20) = 0 Then
						While applyarmy(1, 0, 0, 0, 0, 0, 0, 0, 0, $full, 0) <> 1
							zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
							stoitligenaopen($userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18])
						WEnd
						Return perenosotkritimgenoynoini($parametr[19], $parametr[20], $userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16])
					EndIf
				Else
					Return 0
				EndIf
			EndIf
			If $parametr[2] = "П" Then
				If stoitligenaopen($userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18]) = 1 Then
					While applyarmy($parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $parametr[11], $full, 0) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						stoitligenaopen($userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18])
					WEnd
				EndIf
					$gluksnaboromarmii = 0
					Return perenosotkritimgenoynoini($parametr[19], $parametr[20], $userDIR & $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16])
				Else
					Return 0
			EndIf

``` 

У меня функция проверки и открытия гены по координатам называется stoitligenaopen

**Comment by LEKALA** [comment]
И как ведёт себя Ваш код, 1. если гена ещё не пришёл на координаты? 2. если гена ещё не вернулся из атаки?

**Comment by ghost** [comment]
Так же как и Ваш и исходный

Порядок условий абсолютно не имеет значения
Проверять ли какую арму набираем, а потом стоит ли гена  на позиции, или сначала проверить стоит ли гена, а потом проверить какую арму грузим в него

По команде 
If $parametr[2] = "П/Э/1" Then

бот ничего не делает кроме проверки, какая разница когда это сделать?

**Comment by LEKALA** [comment]
Я могу вместо Вашей **stoitligenaopen** воткнуть свою **openGenaOnpxp** и проверить Ваш код? Или мне нужно будет втыкать именно вашу функцию?

**Comment by ghost** [comment]
Можете канешн только порядковые номера параметров проверьте аккуратно, чтобы я нигде не ошибся.

НаборИпереносПоКоординатам=Генеральша,Э,0,168,0,0,0,3000,0,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать.

НаборИпереносПоКоординатам=Генеральша,П,Н,О,С,Э,Л,ДЛ,А,Кав,Пш,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,-561,75,НеЦентровать.

Вот синтаксис под этот код

**Comment by LEKALA** [comment]
Это понятно... Постараюсь завтра попробовать.

**Comment by ghost** [comment]
Сейчас я код подправлю, налажал с закрытием цикла и условий.

И по условию $parametr[2] = "1" надо подправить набор армии на applyarmy(1, 0, 0, 0, 0, 0, 0, 0, 0, $full, 0)

**Comment by ghost** [comment]
Проверил в Нордике новый формат команды НаборИАтакаПоКоординатам
У меня все работает. Но я перед набором проверяю активность нужного гены командой ЖдемГенерала, без нее работоспособность не проверял.
