### ISSUE TITLE
Новая команда "ВыбратьПоКоординатамИотступить"

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#26]
Для команды нужна новая графика (картинки кнопки с белым флагом), которую нужно положить в папку media с именами othod.bmp и othod_.bmp.
http://c2n.me/49j1qyR.bmp
http://c2n.me/49j1rb8.bmp
Команда работает на основе функции clickOnCoordinates (открывает окно гены) и потом просто нажатии сменяемой картинки с белым флагом. Поскольку кнопка с белым флагом становится активной только тогда, когда гена идёт в атаку, то в иных случаях команда выдаст ошибку. Сам код команды корректно обрабатывает за 4 попытки все видимые мной ошибки - не попадание кликом в гену, не открытие окна гены из-за фризов, отсутствие активной кнопки с белым флагом.
Пример синтаксиса:
ВыбратьПоКоординатамИотступить=Ali_1_sektor.bmp,900,100,-150,-10,-561,75,НеЦентровать

```
Case "ВыбратьПоКоординатамИотступить"
			$centrovat = 1
			Local $perebor = 1, $i = 0
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd
			
			If clickOnCoordinates($userDIR & $parametr[1], $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7]) = 1 Then
				Sleep(600 * $tormoza)
				While (haveimage("media\zadacha_geni.bmp", 20) = 0) AND ($i < 3)
					sleepwhile("media\othod.bmp", 30, 2)
					zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
					clickOnCoordinates($userDIR & $parametr[1], $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7])
					$i = $i + 1
				WEnd
				If $i = 3 Then
				Return 0
				EndIf
				zmemsmennuyukartinku("media\othod.bmp", 30, "media\othod_.bmp", 30)
			Else
				Return 0	
			EndIf
			Return 1
```
Этой команды очень не хватало юзерам, которые хотели бы написать тексты на основе гайдов с отступлением.) И само её использование в текстах потребует расширения команды ЖдемПобеды до уровня ЖдёмПромежуточнойПобеды, например с помощью флага.

**Comment by ghost** [comment]
Команда ЖдемПобеды очень ненадежна. К примеру у меня на разъездном нетбуке не работает, хотя на домашнем и рабочем стацинарнике работала на ура! Но никто не мешает юзать команду ЖдемКартинку и отскринить всплывашку с промежуточной победой нужного гены.

**Comment by LEKALA** [comment]
Понял Вас. Значит пока что, так и будем поступать.

**Comment by LEKALA** [comment]
**Marsik-A**, по поводу стабильности и надёжности работы Вашей команды "ЖдемПобеды" хотел бы поделиться своими наблюдениями. Табличка с графикой победы гены выскакивает не моментально, скорость фадинга зависит от мощи проца (возможно Ваш нетбук) для обработки флэша, скорости тырнета, тупизны в игре... и т.п.
Ваш код функции sleepwhile2 начинается с:

```
Func sleepwhile2($img, $time, $flag)
	local $i = 0, $tolerance = 30, $fl_win = 0
	while ($i < $time)
		If ((haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1)) Then
			$fl_win = 1
			TrayTip("", "Генерал победил", 0)
			Exitloop
```
Т.е. мы уверены что имеем картинку из строки:

`If ((haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1)) Then`

а это может быть совсем не так. Я это испытал на себе, прямо при отладке кода обсуждаемой в топике команды.

```
If clickOnCoordinates($userDIR & $parametr[1], $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7]) = 1 Then
				Sleep(600 * $tormoza)
				While (haveimage("media\zadacha_geni.bmp", 20) = 0) AND ($i < 3)
```
Команда сбоила, особенно при повышении нагрузки (запуск в одном браузере игры и тестового), пока я не включил строку: Sleep(600 * $tormoza). Проблема сразу снялась. Попробуйте тоже вставить строку со слипом перед вызовом haveimage и проверить это на нетбуке. Возможно проблема именно в отсутствии такой задержки?

**Comment by ghost** [comment]
У Вас совсем другая логика - вот эта строка While (haveimage("media\zadacha_geni.bmp", 20) = 0) AND ($i < 3)   ждет появления картинки задача_гены.
А Ваш Иф обрабатывается так же как и мой, и там слип не играет. По сути слип просто добавляет лишнюю ненужную задержку.

```
	while ($i < $time)
		If ((haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1)) Then
			$fl_win = 1
			TrayTip("", "Генерал победил", 0)
			Exitloop
		EndIf
		sleep(1000)
		$i = $i + 1
	wend

```

По коду, если картинок на экране нет, то бот засыпает на 1 секунду, наращивает счетчик и снова проверяет нет ли картинок  с мордой гены и текстом о победе, а если обе картинки есть, то выходит из цикла и работает дальше

**Comment by LEKALA** [comment]
Мой Иф не о том... он о получении 1 от функции clickOnCoordinates....
и да, я не жду картинки, а оперирую с уже имеющейся. Чтобы она имелась и нужен слип. А вы точно уверены, что в Вашем цикле код проверяет наличие картинки?

**Comment by ghost** [comment]
Если интересно, пришлось перескринить картинку gen_win, видно старая осталась с отпуска. Ну и опять же если интересно, то прога съема координат  отлично справляется с проверкой, видит ли бот нужную картинку или нет. Достаточно любым вьером открыть ее поверх браузера с игрой (чтобы была видна иконка книги заданий), ввести ее имя в окно с файлом точки привязки и нажать F5, а если хочется узнать параметр графики, с которым видится эта картинка, то F8

**Comment by ghost** [comment]
> Мой Иф не о том... он о получении 1 от функции clickOnCoordinates....
> и да, я не жду картинки, а оперирую с уже имеющейся. Чтобы она имелась и нужен слип. А вы точно уверены, что в Вашем цикле код проверяет наличие картинки?

Абсолютно, и Вам пишу, в чем отличия между моим в Вашим кодом

**Comment by LEKALA** [comment]
хорошо. я Вас понял.
Значит опять самому придётся писать команду ЖдемПобеду... а заодно и ЖдемНедоПобеду...
Спасибо.

**Comment by ghost** [comment]
Ну Вы пишите бота под себя))))  т.к. большинству пользователей хватает даже старого функционала, судя по всему)

**Comment by LEKALA** [comment]
У Вас имеется полис ото всех пользователей? На то, чтобы решать, чего им хватает?

**Comment by ghost** [comment]
> У Вас имеется полис ото всех пользователей? На то, чтобы решать, чего им хватает?

Я читаю майсетлерс, ВК и дисмейл, и не вижу там запросов на те команды, которые пишите Вы. Этого мало?

**Comment by LEKALA** [comment]
Мало. Ибо никто не спрашивал и не предлагал. А я вот решил предложить, а не решать за них, что им нужно.

**Comment by ghost** [comment]
> Этой команды очень не хватало юзерам, которые хотели бы написать тексты на основе гайдов с отступлением.)

Дык Вы определитесь, это нужно юзерам, коих мало, или все же ВАм

>  А я вот решил предложить, а не решать за них, что им нужно.

**Comment by LEKALA** [comment]
Единственный достоверный вывод, который можно сделать из Ваших реплик - это только то, что мои команды не нужны лично Вам. А остальное - Ваши домыслы.

**Comment by ghost** [comment]
Они нужны лично Вам поэтому Вы ими и занялись. Только почему-то Вы решили что это плохо)
