### ISSUE TITLE
Новая команда "НаборИотправкаПоКоординатам"

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#27]
Эта команда кликает в гену на поле боя (если его там нет пока, то ждёт 20 циклов по 8 сек), затем набирает нужным количеством войск и отправляет из прикла домой. Примеры синтаксисов:
НаборИотправкаПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,1,1,0,0,0,0,0,0,0,0,НеЦентровать
НаборИотправкаПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,П,20,0,0,0,0,0,0,0,0,НеЦентровать
НаборИотправкаПоКоординатам=Генеральша,Ali_1_sektor.bmp,900,100,-150,-10,-621,51,Э,0,168,0,0,0,3000,0,НеЦентровать
Гену, заряженного одним любым юнитом (нубом, лучником, КМ, КС и т.д.) отправляет домой без перезарядки на нуба (в случае первого синтаксиса).

Этот код добавить в обработку команд:

```
Case "НаборИотправкаПоКоординатам"
			$centrovat = 1
			Local $perebor = 1
			$parametr = StringSplit($komanda[2], ",")
			$komand_na_massiv = UBound($parametr)
			While $perebor < $komand_na_massiv
				If $parametr[$perebor] = "НеЦентровать" Then
					$centrovat = 0
					ExitLoop
				EndIf
				$perebor = $perebor + 1
			WEnd
			
			$generalData = getGeneralData($parametr[1])
			$gena = $generalData[0]
			$full = $generalData[1]
			
			If openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8]) = 1 Then
				If $parametr[9] = "Э" Then
					While apply_elitnoy_army($parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $full, 2) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return 1
				EndIf
				If $parametr[9] = "1" Then
					If haveimage("media\army_values\1.bmp", 20) = 1 Then
					zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
					zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
						Return 1
					Else
						While applyarmy($parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 2) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
						WEnd
						$gluksnaboromarmii = 0
						Return 1
					EndIf
				EndIf
				If $parametr[9] = "П" Then
					While applyarmy($parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 2) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
					WEnd
					$gluksnaboromarmii = 0
					Return 1
				EndIf
			Else
				Return 0
			EndIf	
```
В коде команды использован трюк **Marsik-A** с флагом 2 для команды "Набрать")) За что ему бесконечный респект! ))
Это похоже моя последняя из команд для боёвки, хочу сначала переписать свои тексты под новые возможности бота, а потом заняться Запуском форпоста, обси и погоды ботом... Но то таке...
Ещё бы с помощью **Marsik-A** отшлифовать команды "ЖдемПобеду" и ЖдемГенерала" - было бы ваще кульно!!! )))

**Comment by ghost** [comment]
А что не так со ЖдемГенерала? Если Вы не заметили, но неактивные близнецы имеют одинаковую картинку, поэтому ЖдемВсехГенералов=любой из близнецов по сути будет ждать, пока будут активны все близнецы и старший и младший. По другому никак, в случае одиночного ожидания гены задержки минимальны.

А по ЖдемПромежуточнуюПобеду - заскриньте текст с промежуточной победой, и поправьте мой код с заменой ожидания картинки gen_win.bmp на скрин с текстом о промежуточной победе.

**Comment by LEKALA** [comment]
Ну и зачем нам всем две разных команды на почти одно и то-же? Возможно имеет таки смысл ограничиться одной командой, а варианты победы регулировать флагом? С перспективой контроля за вернувшимся и готовым к бою геной.

**Comment by LEKALA** [comment]
Ну и зачем нам всем две разных команды на почти одно и то-же? Возможно имеет таки смысл ограничиться одной командой, а варианты победы регулировать флагом? С перспективой контроля за вернувшимся и готовым к бою геной.

**Comment by ghost** [comment]
не нам, а Вам) Так у Вас все есть, успехов!)

Давайте я еще раз попробую разъяснить свою позицию, если Вы захотите меня услышать.
Зачем я писал команду ЖдемПобеду с таймером. В случае если нужно поймать победу генерала, чаще всего это означает расчистку сектора и возможность начать переезд, и в некоторых случаях экономит несколько минут, что критично при использовании поста. В принципе, можно было использовать команду ЖдемКартинку, если бы не одно но - в случае, когда таймер на Ждемкартинку истекал, а картинка НЕ появилась, бот стопался, а при отлове события о победе гены это неверное поведение, поэтому вариантов было два - переписать ЖдемКартинку так, чтобы бот не стопался по истечении таймера, или написать другую команду. Я выбрал 2е. Итак, резюме, если вдруг бот "прозевал" событие Гена победил, то по истечении таймера бот продолжит нормальную работу.
Теперь рассмотрим предлагаемый Вами вариант отлова промежуточной победы для реализации команды Отступить. Итак, бот "прозевал" промежуточную победу гены, и гена пошел воевать дальше и слился. Дальше продолжать?
Тут и вариант через ЖдемКартинку тоже плохой вариант, т.к. в любом случае при провале гена сольется. Хорошо, если Вы арму берете по минимуму в прикл, а если взяли с запасом да и зациклили на ночь, то к утру получили эпичный слив.
Возможно, у Вас игра (и бот) работают как часы без каких-либо сливов и стопов, но далеко не у всех это так. Многие даже отвлечения в боте не используют, чтобы не попасть на лаги.    
Ну и чтобы 2 раза не вставать, по каким-то мистическим причинам на нетбуке у меня отлично заработали в ЖдемПобеду морды ген из звезды, хотя до этого все лето я бился с этой проблемой и не мог победить - пришлось скринить морды с всплывашек. А Вы хотите универсальное решение.

**Comment by LEKALA** [comment]
А что-то по сути предложенной к обсуждению команды Вы сказать можете? Вашим отказом развивать свою же функцию я уже успел насладиться...

**Comment by ghost** [comment]
По сути читайте выше. Вам Jemxx уже один раз написал, что каждый делает тут то, что ему интересно и в свое свободное время Спасибо ему, что оживил дохлый проект, на который даже автор давно забил и на все хотелки-перделки отвечал "а зачем".  Т.е. здесь не бюро заказов, куда копать - я Вам рассказал, берите и делайте. Вы же сделали нужные Вам команды

**Comment by LEKALA** [comment]
Процитирую сам себя: 
> А что-то по сути предложенной к обсуждению команды Вы сказать можете?

Я имел ввиду, если Вам интересно..., данный топик, в котором к обсуждению предложена команда "НаборИотправкаПоКоординатам".

Ваши соображения по поводу слива при отступлении после полупобеды мне вполне близки. И Ваше нежелание развивать то, что Вас и так устраивает тоже понятно. 
Но вот тупым юзерам, которые так и норовят Вас "выморозить" своими хотелками нужны дружелюбные команды с дружественным синтаксисом. Не так ли?
Команда ЖдемПолуПобеду тупым юзерам очевидно не нужна?

**Comment by ghost** [comment]
> Но вот тупым юзерам, которые так и норовят Вас "выморозить" своими хотелками нужны дружелюбные команды с дружественным синтаксисом. Не так ли?
> Команда ЖдемПолуПобеду тупым юзерам очевидно не нужна?

Не надо передергивать) Тем более, что дружелюбный синтаксис по итогу сделал я, а не Вы))) Не так ли? (с)

Переписал все три команды НаборПоКоординатам, НаборИАтакаПоКоординатам и НаборИпереносПоКоординатам с учетом мной же предложенного синтакиса. Притом, что сам лично пользуюсь пока только полутора из них: НаборПоКоординатам и подправил текстовик на Нордик под использование НаборИАтакаПоКоординатам для будущего ивента.

**Comment by LEKALA** [comment]
> Не надо передергивать) Тем более, что дружелюбный синтаксис по итогу сделал я, а не Вы))) Не так ли? (с)

Вот и хорошо, что Вы проговорились! (( Ваш дружественный тупому юзеру синтаксис и код для него я проверил. Всё работает, как задумывалось. (обработку ошибок ещё не успел проверить). Поздравляю!!! Теперь можете публиковать это всё  **под своим авторством!!!** И плевать! что двумя неделями ранее тупым юзерам весь этот бесполезный набор команд был совершенно не нужен...(((
А насчёт команды НаборПоКоординатам хотел спросить. Как то забылось, что когда начиналась работа над переделкой бота, был договор, что все работающие команды не трогаем? Чтобы не канули в лету ранее написанные тексты. Так и что теперь - команда НаборГеныПодАтаку исчезла из Вашей **Авторской публикации**?

**Comment by ghost** [comment]
> Вот и хорошо, что Вы проговорились!

Проговорился о чем?)))) о том, что сам предложил дружественный интерфейс и сам его сделал? так вроде как и не тайна) Ничего публиковать под своим авторством я не буду, т.к. этот функционал мало кому нужен, захочет Jemxx включить это все в основную версию - пусть включает. У меня много чего сделано для личного пользования, например работа с клиентом Сирриса - там другой заголовок у окна, и оригинальный бот и бот Jemxx-a с клиентом Сирриса не работает. Вы меня укорили, что мой код с поменянными местами if-ами не будет работать, а т.к. я привык делать все хорошо - то проверил, что все работает, как и задумывалось, поэтому и оставил в своей редакции, раз уже поправил код, то зачем вычеркивать. Все-тки время потрачено, параметры любовно пронумерованы и аккуратно пересчитаны. Да и пару ошибок нашел, на что Вам честно указал. 

> Так и что теперь - команда НаборГеныПодАтаку исчезла из Вашей **Авторской публикации**?

Какая авторская публикация?)) вы бредите?))))) Команда НаборПоКоординатам сделана не **вместо** команды НаборГеныПодАтаку а **вместе** с ней, именно поэтому она и названа именно так, по аналогии с АтакаПоКоординатам, НаборИатакаПоКоординатам, чтобы не надо было лезть в файл помощи каждый раз, чтобы писать текстовик, а все команды были унифицированы и интуитивно понятны. Если не видите разницы - то это не ко мне. Итак по началу намучался, пока писал первые текстовки.

**Comment by LEKALA** [comment]
Наслаждайтесь! Как изящно разули лошка... ((( Апплодисменты АВТОРУ!!! (((

Если **Jemxx** окажется порядочным человеком, то ничего из обсуждаемых здесь статей он в релиз включать не будет. А на mysettlers я сам опубликую весь набор придуманных мною команд.
А Вам дальнейших успехов ....

**Comment by ghost** [comment]
а в чем обувание-то?) Что я указал Вам, как будет красивее? или я спер Ваш код и выдал за свой?) Я Вам даже на ошибки с обработкой указал, так что скорее Вы меня развели на помощь и на реализацию не особо нужного мне контента)))))  
Я могу Вам даже показать свою функцию stoitligenaopen? сделана на основе функции stoitligena 
Можете публиковать что угодно, где угодно и с каким угодно синтаксисом - никто же не запрещает.

**Comment by LEKALA** [comment]
Мне то никто не запрещает. А вот Вам помешать может только совесть... хотя похоже нечему.((( 
Я ещё сегодня увижу на mysettlers Ваши гениальные новые и очень востребованные тупыми юзерами команды? Или до завтра подождёте? А пока займётесь приведением к идеалу Ваших кривых команд - ЖдемПобеду и Ждем Генерала?

**Comment by ghost** [comment]
> Мне то никто не запрещает. А вот Вам помешать может только совесть... хотя похоже нечему.(((
> Я ещё сегодня увижу на mysettlers Ваши гениальные новые и очень востребованные тупыми юзерами команды? Или до завтра подождёте? А пока займётесь приведением к идеалу Ваших кривых команд - ЖдемПобеду и Ждем Генерала?

Вместо благодарности за помощь Вы мне еще и хамите?))) Пожалста покажите ссылку, где я бы опубликовал что-то чужое, и выдал за свое?)))) У Вас какая-то паранойя, то за Вами Биги следит за евродоллары от разработчиков, теперь я тырю Ваши гениальные идеи и публикую от своего имени))) Осень - пора обострений?)

**Comment by LEKALA** [comment]
Помощь заключалась в закрытии одного Ифа? Успешно выдали за своё Вы прямо в этом топике. А публикация украденного зависит не от Вас, а к счастью от Jemxx.
Я хамлю?!!! Вам?!!! Вы похоже не в себе... отдохните, расслабьтесь)
А Ваши кривые команды я перепишу с нуля, а пока заменил Вашу поделку (ЖдемГенерала) на исходник от автора бота... и да, лучше включать сортировку по имени, чем пользоваться результатом Вашего гениального кодирования.
А биги следит... Спорим, после моей публикации на mysettlers экзешника с моими командами, файл botanic.exe через пару месяцев будет забанен и в гугле и в микрософте за бабки юбисофт?)))

**Comment by ghost** [comment]
Как же с Вами тяжело, Вы уж определитесь или 

> Я ещё сегодня увижу на mysettlers Ваши гениальные новые и очень востребованные тупыми юзерами команды? Или до завтра подождёте?

или все же

> А публикация украденного зависит не от Вас, а к счастью от Jemxx.

> Успешно выдали за своё Вы прямо в этом топике. 

Что я выдал за свое? Полностью переписанный код с дружелюбным синтаксисом, который Вы не смогли сделать, т.к. сначала боялись запутаться, а потом признались, что не разобрались как это корректно сделать?))) И где я это все **уже**  опубликовал, кроме этого топика? Да еще и выдал за свое?)) По большому счету это все вообще автора оригинального бота. Я показал Вам, как можно и нужно было сделать корректно, не хотите пользоваться - не надо, хотите переименовывать и сортировать ген, дазарадибоха. На этом диспут считаю законченным.

**Comment by ghost** [comment]
Не забудьте еще не пользоваться командой НажатьКлавишу, а то она тоже сифовая)

**Comment by LEKALA** [comment]
Уже часа два считал его законченным. С чего это не пользоваться? Вам значит можно воровать, а мне пользоваться нельзя? Вы из высшей расы что-ли? Так ладошка и чешется, санкции ввести?)))

**Comment by ghost** [comment]
ну а как же Ваши принципы и мое кривое гениальное кодирование?)))

> А Ваши кривые команды я перепишу с нуля, а пока заменил Вашу поделку (ЖдемГенерала) на исходник от автора бота... и да, лучше включать сортировку по имени, чем пользоваться результатом Вашего гениального кодирования.

**Comment by LEKALA** [comment]
просто ещё не имел возможности поюзать эту Вашу команду... поэтому ничего ни плохого, ни хорошего сказать про неё не могу... но судя по коду, там всё норм д.б... Это первое. А второе - Вы улавливаете разницу между "отшлифовать команду ЖдемГенерала" и "кривые команды я перепишу с нуля" вместе с "заменил Вашу поделку (ЖдемГенерала) на исходник"?
Понимаете природу этой разницы? И причины, вызвавшие появление этой разницы? а также хронологию...
И последнее, Вы слышали что-то о дате создания файла? дате публикации? Я надеюсь Вам понятно, что всё это легко сравнить, даже если не читать, как Вы не вкуривали в 20 кликов и 200 секунд ожидания из моего первого топика...

**Comment by jemxx** [comment]
> после моей публикации на mysettlers экзешника с моими командами, файл botanic.exe

Плодить кучу экзешников это плохая идея, люди запутаются и ничего хорошего из этого не выйдет.
Вот представь ситуацию. Вы добавили какие то функции и выложили свой файл. Завтра другой человек добавляет свои функции и выкладывает тоже свой файл. Затем еще один. И что делать в такой ситуации пользователю которому нужны функции из всех трех файлов? По очереди их юзать чтоли? 
**То что сейчас начинается с выкладывание свои файлов это очень плохая практика**. Этот балаган даже начинать не стоит. Если вы написали функцию и считаете что она будет полезна другим пользователям всегда можно добавить в основную ветку Автобота. Это единственный правильный путь. **Иначе не стоит ничего выкладывать ни коды ни тем более собранные экзешники**.

**Comment by LEKALA** [comment]
**jemxx,**  я полностью разделяю Ваш подход к публикации релизов, поэтому обещаю воздерживаться от создания параллельной публикаци, пока **Marsik-A** будет воздерживаться от включения в Ваш релиз присвоенных им команд, которые были разработаны мной. Но такая ситуация не может продолжаться бесконечно долго, проблему нужно решать **взаимоприемлемо** и с пользой для конечного пользователя.

**Comment by ghost** [comment]
LEKALA, уймитесь уже!  Прежде чем обвинять, покажите **ГДЕ**, **ЧТО** и **КУДА** я включил? У Вас завышенное ЧСВ, Если на то пошло - Вы взяли коды автора оригинального бота и команду кликпокоординатам от Jemxx-а и слепили суррогатную подделку, я Вам указал где там неточность с обработкой одного if-а. А вы стали мне хамить. Потом я показал, как можно переделать предложенный Вами код, чтобы это было дружелюбно к пользователю, а не как у вас было - коры откуда, состав армы, коры куда. Можете миллион раз фоловить мой гитхаб - ничего Вы тут не увидите. Все что я включил, я включил в свою личную персональную версию автобота, которую пользую сам и никуда ничего не выкладываю. из-за таких дебилов как Вы вообще не хочется никому помогать.

**Comment by LEKALA** [comment]
Marsik-A, вот и опустился до оскорблений?((( Я собственно этим фактом нисколько не удивлён...(((
Вот и сидите со своим кодом. А мне придётся обратиться к **jemxx** для включения моих новых команд в релиз, чтобы ими смогли воспользоваться характеризуемые Вами, как "тупые юзеры" и "дебилы", просто обычные энтузиасты игры и бота.
И избави меня Бог от помощи таких "гениев", как Вы.

**Comment by ghost** [comment]
Оставьте свои фантазии при себе "тупые юзеры" это Ваше выражение, а не мое. И про дебила я лично к Вам, а не ко всем, потому как тот бред, который несете Вы, нормальный человек писать не будет. И тем более выдавать за свое ноухау, то что сляпано на коленке из чужих команд. 

Ни единого доказательства Ваших слов я так и не увидел, где я что опубликовал? Где я написал про "тупых юзеров"? Пруфы, неуважаемый

**Comment by LEKALA** [comment]
**jemxx,** могу ли я обратиться к Вам с просьбой удалить из этого топика всё говно, которое успел насрать тут малоуважаемый Marsik-A?

**Comment by LEKALA** [comment]
Marsik-A, Вашей одной извилине от фуражки доступна мысль, что фраза - "пока Marsik-A будет воздерживаться от включения в Ваш релиз присвоенных им команд, которые были разработаны мной." означает, что на данный момент Вам пока не удалось ничего из сворованного нигде опубликовать? Что Вам ещё нужно доказать?

**Comment by ghost** [comment]
Вы реально дебил? Разницы между "не хотел" и "не удалось" не понимаете да? ну оке, достали. Пусть Jemxx решает, чей код лучше)

**Comment by LEKALA** [comment]
Прекрасно понимаю разницу. И на данный момент Вам пока не удалось включить в релиз Ваш "синтаксический мод команды, разработанной LEKALA (ака Андрей)". Рекомендую Вам прекратить оскорбления, чтобы Вы не выглядели в глазах читателей этого репозитория, как полный ублюдок.

**Comment by ghost** [comment]
Итак почему я считаю этот фрагмент кода ошибочным 
```
				If $parametr[9] = "1" Then
					If haveimage("media\army_values\1.bmp", 20) = 1 Then
					zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
					zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
						Return 1
					Else
						While applyarmy($parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 2) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[2], $parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8])
						WEnd
						$gluksnaboromarmii = 0
						Return 1
					EndIf
				EndIf

```

потому что при йказании в типе армии 1, этот кода будет набирать  армию с указанным в команде составам - если "тупой юзер" (с) LEKALA забудет что тут должен быть четко прописан набор 1го юнита - а никак не с одним новом.



`applyarmy($parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16], $parametr[17], $parametr[18], $full, 2) <> 1
` 

должно быть 


`applyarmy(1, 0, 0, 0, 0, 0, 0, 0, 0, $full, 2) <> 1
`

Поэтому разработчик Вы наш, уймитесь уже

**Comment by LEKALA** [comment]
да. это может быть один лучник или один конь, в отличие от предложенных Вами нулей... это свобода маневра для "тупого юзера" (с) Vasuta.
