### ISSUE TITLE
Конфиг файл (specialist.json)

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#32]
Предлагаю переименовать specialists.json в config.json, раз там теперь не только спецы.
Еще ВК высказывали "мысль" что призрачный гена из-за его частичной прозрачности не будет виден боту: я проверил на тесте - все работает, у Призрака прозрачный только лагерь, а иконка вполне себе нормальная.
Оставлю пока задачу открытой - когда проверю, по крайней мере, все боевые бафы - но это уже после ивента. 
Пока проверил только бронзоподкову - все работает.

**Comment by jemxx** [comment]
Конечно же переименовать надо.  Переименовал.

**Comment by Marsik-A** [comment]
Проверил все бафы (кроме нубов), но нубов Вы наверное и сами проверили.

БольшаяКатапульта
Стрела
ЧернаяСтрела
Баллиста
Убийца
ГорящаяСтрела
МаленькаяКатапульта
ШокоСтрела

Стрельнуть=Бронзоподкова
Стрельнуть=Платиноподкова
Стрельнуть=Обсидиановая
Стрельнуть=Титаноподкова
Стрельнуть=Мистикподкова

В архиве картинки для Стрелы из черного дерева (которая в  Черном дереве) и Таинственной подковы (за золотые монеты в Эпичных) 
[media.zip](https://github.com/jemxx/autobot/files/5471688/media.zip)

Вот думаю, может еще воронку из дерева добавить?
