### ISSUE TITLE
Поздравляю с новым релизом! ))

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#33]
**jemxx,** я не увидел в этом релизе моих команд "НаборИотправкаПоКоординатам" и "ВыбратьПоКоординатамИотступить". Вы считаете, что данные команды не нужны пользователям бота и не интересны? Или в релиз попадает только то, что успел присвоить себе Marsik-A (ака васюта)? И зачем включать в релиз неработающую команду ЖдемВсехГенералов?
Если не трудно, прошу Вас пояснить свою позицию?)

**Comment by jemxx** [comment]
Позиция моя простая. В релиз я включаю только то, что сам протестил. Пока вы тут шашками махали и запрещали ваши наработки использовать, я добавил и протестировал наработки Marsik-A. Ваши команды я тоже добавил, и собирался их тестировать, но после вашего запрета был вынужден их убрать из публичной ветки.
За последние 3 дня я пробежался по всем добавленным изменениям и по-сколько они нареканий не вызвали, были включены в релиз. Замечу, что ваши команды тоже могли быть тут, но по выше описанным причинам их к большому сожалению нет.
Несомненно ваши команды интересны пользователям бота и даже я вижу некоторым из них применение в своих прохождениях поэтому я наверняка вернусь к ним и протестирую.


> И зачем включать в релиз неработающую команду ЖдемВсехГенералов?

Не надо дезинформировать народ. Все прекрасно работает. Ни один десяток приключений пройдено.

**Comment by LEKALA** [comment]
Понятно... только я не припомню, где запрещал публикацию своих команд, которые калякал для людей, для пользователей бота. 
Команда ЖдемВсехГенералов не работает должным образом.(( В команде есть только код для листания и абсолютно отсутствует логика - например, нужная цепочка генералов находится внизу любого экрана (часть открыта (находится на текущем экране), а часть скрыта (находится на следующем). Команда сделает ошибку. Очень досадную ошибку для пользователя. Есть ещё не столь частые, но не менее досадные варианты. например связанные с отъездом ген из обоймы... Я предлагал это к обсуждению, но был проигнорирован.
Повторяю третий раз, я не запрещал публикацию моих команд, а как раз наоборот - очень надеюсь, что они станут доступны для пользователей бота.

**Comment by jemxx** [comment]
Я же вам уже давал ссылку на ваше сообщение где вы запрещаете https://github.com/jemxx/autobot/issues/27#issuecomment-704410655

Что касается ЖдемВсехГенералов и описной вами ошибки. Ну придется под нее подстраиваться, потому как решить это очень проблематично. Жили же раньше с тем что генералы вообще не листались? Переименовывали их и жили. Вот и тут так. Ибо я не представляю ни какой здравой логики для решения этой проблемы. Это настолько редкая ситуация что городить искусственный интеллект не стоит. Сделать конечно можно. Но для этого надо научить для начала бота листать вверх и дальше что то думать. Но оно того не стоит ибо как я сказал выше эта очень редкая ситуация.

**Comment by LEKALA** [comment]
**jemxx,** я Вам тоже давал ссылку в ответ на вашу ссылку... и пояснения свои... они Вас не удовлетворили? В топике про команду "НаборИотправкаПоКоординатам" некто неколлега васюта два раза уклонялся от обсуждения представленной команды, вместо этого пытался насладиться собственным сиянием и пытался чмарить и унижать меня.
Повторяю второй раз, в том топике обсуждался факт воровства моих идей формирования команд, структуры кода и собственно результата для юзера. Васюта именно в этом топике объявил мои наработки своим достижением ещё по ходу и унижая меня... Я должен был утереться? Всё, что мне позволяет моя социальность и адекватность - это надеяться на Вашу порядочность, поэтому я и упомянул про факт издания не относящихся к топику команд в релиз....
И да, я же давал Вам пояснения по данному парадоксу.

**Comment by LEKALA** [comment]
Нет там ничего проблематичного. Просто бот сначала должен искать экран (листая допустим по две строки), на котором находятся: или активные и неактивные картинки, или только активные, или только не активные... Для этого можно написать микрофункции, а в кейсе лепить из них комбинацию. Найдя такой экран бот должен перестать тупо листать экраны, а ждать нужной юзеру комбинации... Я мечтал работать над этой задачей коллективно.... но не вышло((( пришлось задыхаца от вони нашего визави...

**Comment by LEKALA** [comment]
И это не редкая ситуация. Ибо простые (самые медленные из всех, соот должные уезжать первыми) и автобусы находятся как раз в конце списка всех ген... а если у Вас много, то туда попадут и нинзи и дракулы.... и Бог весть, кто ещё...
Данная проблема касается всех цикличных приклов, когда новый прикл начинает отправлять первыми или простых ген или автобусы... Он ждёт их возвращения из предыдущего прикла и отправляет по логике звезды...
Текущая версия обсуждаемой команды, в этом смысле, не годится никуда.(((
