### ISSUE TITLE
Параметр "НеЦентровать"

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#34]
Jemxx, а у Вас адекватно работает этот параметр, или Вы не пользуетесь?
У меня он очень странно работает, если его указать, то бот иногда все равно чуть подергивает вверх/вниз/вправо/влево карту.
А вот если не указыватЬ, то к примеру в команде НаМесте - я в Нордике через нее центрую карту, чтобы потом без проблем прокликать по корам ящики/бочки, у меня явно центрует с ошибкой. Я указываю центровку на 200 пикселей ниже !, а он центрует ровно напротив !.  А вот следом идет команда АтакаПоКоординатам без центровки - там центрует как надо - на 200 пикселей ниже!
Я уже и по коду посмотрел - код везде одинаковый.

**Comment by jemxx** [comment]
Я ей вообще не пользуюсь. Как то пытался разобраться для чего ее можно применить и забил на нее

**Comment by ghost** [comment]
По началу я ее юзал, чтобы бот меньше тратил времени на сдвиги карты, но как оказалось, что даже наличие этого параметра не избавляет от таких сдвигов. Более того, НеЦентровать даже усугубляет, т.к. бот все равно карту двигает, но более суетливо что ли. Не знаю как более понятно объяснить, как будто при этом параметре у бота задача попасть строго пиксель в пиксель, и он начинает мелко двигать карту вверх/вниз/вправо/влево, пока не достигнет своей цели.
Потом я понял, что такое непонятное поведение увеличивает время прохода и тоже забил на нее. Но вот сейчас в Нордике без такой центровки у меня не кликает на самый верхний ящик( Причем, если кликать на этот ящик 1м из 6ти, то не кликнет - унесет карту так, что ящик окажется за верхним краем экрана, а вот если последним - то кликнет. И никакие смещения если_вне_экрана_х, если_вне_экрана_у не работают. Уже проверял, может какие-то переменные не обнуляются - нет, все нормально. Очень странное поведение.

**Comment by ghost** [comment]
Вообще сама центровка работает не совсем адекватно, хоть с этим параметром хоть без него.

**Comment by jemxx** [comment]
Тут много чего не адвекватного)  Приходится мирится

**Comment by nubikkk** [comment]
5 копеек- если текстовик чужой, то хорошо бы знать под какое именно разрешение экрана он писался. Потому что такое бывает- на одном компе (правильней - экране!?) бот бегает без проблем, на другом тоже, а на 3-ем с ошибкой изредка. Я не программер, а просто юзер бота. Поэтому камнями не кидайтесь, просто из опыта.

**Comment by ghost** [comment]
Тут бывает, что на одном экране то бегает нормально 100500 штук, то затыкается на первом же)))
