### ISSUE TITLE
[ATTENTION!!] ЖдемВсехГенералов

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#35]
Не могу открыть старую задачу, поэтому напишу заново

На экран помещается 4 полных строки генералов, по крайней мере сейчас.
Можно в команде ЖдемВсехГенералов, чтобы избежать проблемы разноса ожидаемых ген по разным экранам, листать не на весь экран, а три раза по одной строке. Тем самым при таком листании последняя полная строка всегда будет самой верхней.
Единственная проблема в этом случае, которую я вижу - это ожидание всех генералов, если они растянутся на 3 строки, сейчас такое количество может быть только с мастерами боевых искусств. Можно решить переименованием, т.к. оно меняет порядок всех боевых ген или использовать ожидание по времени.

функция ozidanierasstanovki в globalfuncWAR.au3

```
Func ozidanierasstanovki($image, $image_NA, $yes)
; Ждем всех генералов
    ;writelog("=====ОЖИДАЕМ ПЕРЕСТАНОВКу " & $yes & @CRLF)
	Local $tx = 0, $ty = 0, $ii = 1, $i = 0, $fl = 0, $count_list = 5, $count_line = 4, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране при листании звезды (3 видимых строки по 9 ген в строке)
	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line))
	Sleep(500 * $tormoza)
	while 1 AND ($i < 900) ; макисмальное время ожидания в секундах (15 минут)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		$ii = 0
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) AND (_imagesearcharea($image_NA, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 0)  Then
				$fl = 1
				ExitLoop
			Else
                                sleep(500*tormoza)
				zvezdamovepolzunokdown(0)
                                sleep(500*tormoza)
				zvezdamovepolzunokdown(0)
                                sleep(500*tormoza)
				zvezdamovepolzunokdown(0)
				$ii = $ii + 1
				If $ii > $count_list Then ExitLoop
;~ 				If (zvezdamovepolzunokdown(0) = 0) then
;~ 					; zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
;~ 					ExitLoop
;~ 				EndIf
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(1000)
	Wend
	If ($fl = 1) and ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
	If $i = 900 Then
		writelog("=====ОШИБКА " & $i & @CRLF)
			Return 0
	EndIf
	writelog("=====УСПЕХ " & $i & @CRLF)
	Return 1
EndFunc
```

**Comment by ghost** [comment]
Ну и еще как вариант для параноиков, сделать доп необязательный пареметр у ЖдемВсехГенералов. например, построчно.
Формат ЖдемВсехГенералов=Простой,1,Построчно
При обработке команды ЖдемВсехГенералов проверять количество параметров, их будет или 2 (старый формат и поэкранное листание) или 3 (построчное листание), если три - то взводить флажок и листать звезду построчно. В этом случае, во-первых, никаких "разэкранов" не будет, а во-вторых, в случаях, где не нужно так сложно ждать, звезда будет листаться гораздо быстрее.
Но в этом случае надо будет аккуратно просчитать число листаний при построчном режиме.

**Comment by jemxx** [comment]
> Ну и еще как вариант для параноиков, сделать доп необязательный пареметр

В целом идея интересная, но насколько оно будет востребовано?

**Comment by ghost** [comment]
Построчное листание поможет избежать проблемы, когда при ожидании активные и неактивные гены разносятся по разным экранам, и команда работает неверно. Ситуация, каэшн, очень редкая, т.к. сейчас я вижу проблему только с мастерами боевых искусств - у меня они на три строки расползлись, а все остальные боевые прекрасно реогранизуются в нужном порядке переименованием. А ждать всех автобусов или простых не вижу причин.
Просто построчное листание решает бОльшую часть проблем:
- совместимость со старыми проходами 
- минимальные правки кода, но при этом максимально прозрачная логика
- даже если гены в звезде будут прыгать (приплывать/уплывать), код должен работать адекватно - он будет каждый раз листать построчно с самого верха.

С нужным числом листаний я тоже думал. Для тех, кто не гонится за каждой секундой, в ини файле по умолчанию можно оставить число ген равным 150 (4 полных экрана по 36 ген и округлим). 
А для торопыг число листаний будет 
количество ген - 27 (3 стоки по 9 ген). Это разницу делим на 9 (число ген в строке), определяя число строк, которые нужно пролистать  и округляем. Вроде нигде не ошибся в логике

**Comment by tester2121212121** [comment]
ЖдемВсехГенералов=Простой,1 
 в последней версии не работает. 
генералы на 2 строки расползлись, но на одном экране

**Comment by ghost** [comment]
Если на одном экране, то должно работать. Попробуйте перескринить картинки активного и неактивного гены, или увеличьте скорость в боте.

**Comment by jemxx** [comment]
> ЖдемВсехГенералов=Простой,1

Да вроди бы работает. Не одно приключение отбегал на последней версии. Хотя они у меня на одной строке.

**Comment by tester2121212121** [comment]
у меня на первом экране нет ген, после прокрутки, 2 в правом верхнем углу, 4 во второй строке слева. не видит ген, т.е. зацикливается, постоянно заходит и ждет

**Comment by ghost** [comment]
Перескриньте иконки активного (цветного) и неактивного (серого) простого генерала, назовите активного General.bmp, а неактивного NoGeneral.bmp. Поместите картинки в папку media. Других объяснений у меня нет

**Comment by tester2121212121** [comment]
да все версии кроме последней видят. убрал ЖдемВсехГенералов=Простой,1 и все отлично бегает. в прикле и отправка нет проблем

**Comment by ghost** [comment]
Эта функция не менялась с августовской версии, дело похоже в картинках генералов.

**Comment by ghost** [comment]
если с активной картинкой проблем нет (набирает/атакует из звезды, отправляет в прикл, ждет одного гену), то значит проблема с неактивной картинкой, NoGeneral.bmp

Еще вопрос - а у Вас долистывает при ожидании до простых ген? сколько у вас всего генералов, и сколько указано в ини файле?

**Comment by jemxx** [comment]
> Эта функция не менялась с августовской версии, дело похоже в картинках генералов.

Менялась.  https://github.com/jemxx/autobot/issues/4#issuecomment-709441469

**Comment by ghost** [comment]
да я уже вспомнил про оптимизацию листания, поэтому и уточнил про число генералов в ини файле

**Comment by tester2121212121** [comment]
да долистывает. помещаются на один экран. но в разных строках.
в приключениях много где ждет простых ген, работает идеально.

**Comment by tester2121212121** [comment]
методика ждать ген точно изменилась, раньше всех спецов листало

**Comment by ghost** [comment]
Изменилось количество листаний, но не принцип ожидания картинок.
Но вообще с игрой происходят странные вещи, периодически тоже не видит неактивную нусалу или картинку нордика в звезде.

**Comment by jemxx** [comment]
Да, действительно какая то хрень с ожиданием генералов на домашнем острове. В приклах все хорошо, а вот дома не ждет почему то.

**Comment by ghost** [comment]
Я не вижу в коде причин, чтобы не ждало. Можно вернуть старый вариант и проверить, он то был рабочим с августа.  

UPD. Как я и предполагал - дело в картинках неактивных ген. У меня Майор на 2й странице, тоже сначала при одном неактивном успешно всех "дождался", я перескринил картинку неактивного майора -  и все работает как и задумано, листает пока не найдет всех майоров. Видимо та же хрень с картинками для команды  ЖдемПобеду, перестали видеться скрины.

upd 2. Еще веселее - при попытке посмотреть исходную картинку неактивного майора в папке медиа - написали, что это не бмп, а png!!! С NoBoris и NoMajor такая фигня

**Comment by ghost** [comment]
По результатам обсуждения на Дискорде, выяснилось, что похоже некоторые скрины неактивных генералов нужно подрезать снизу. По каким-то причинам ждать всех генералов (когда нужно ждать пропадания серых/неактивных иконок) мешает появляющаяся полоска прогресса.
У человека, с которым это обнаружили, разрешение 1360х768
