### ISSUE TITLE
[NEED_TO_BE_TESTED] ЖдемПобеду

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#37]
Как бы мне не хотелось, но команду все же стоит убрать. Я так и не понял, как меняются эти всплывающие картинки. Перестало работать даже там, где работало - на домашнем ноуте.
Проще и надежнее реализовывать через ЖдемКартинку.

**Comment by jemxx** [comment]
Ок. Уберу.

**Comment by ghost** [comment]
**2 Jemxx**

Команда задумывалась и создавалась под одной причине  - избавиться от многочисленных скринов с всплывающими картинками-победами генералов. Тем более что у этого метода есть существенное ограничение: если включена обсерва (или будет какой-либо ивент) и у генерала на иконке появится звездочка, то нужно делать два скрина - со звездой и без, и помнить в каком текстовике какой вариант заложен. И второй момент -  меня не устраивала работа команды ЖдемКартинку, в случае если таймер истек, а картинки не появилось - бот вставал. 
Идея реализации была подсмотрена у автора альтернативного бота (из сообщества в ВК). Для программной реализации я ввел функцию  sleepwhile2, которая реализовывала проверку наличия на экране сразу двух картинок - иконки генерала и текста "генерал победил". Автор альтернативной версии в качестве картинок использовал скрины генералов из звезды, не знаю насколько это у него работало.  У меня они работали через раз, мы с Вами Jemxx это обсуждали в прошлом топике по этой команде. Дальше я нашел, что всплывающие сообщения имеют некую прозрачность, и надо перескринить иконки генералов с учетом этой прозрачности.  Что и было сделано, протестировано и вошло в один из прошлых релизов - иконки  всех ген получили имена со sp*
Дальше по отзывам на MySettlers (и по моему личному опыту) этот метод работал далеко не у всех. В частности у меня он отлично работал на физических машинах и не работал на виртуальной (реализованной через Hyper-V). После очередной обновы он перестал работать и у меня на том ноутбуке, на котором все это исходно разрабатывалось и тестировалась. Когда я стал разбираться, что произошло - получилась очень интересная вещь, иконки генералов с sp* перестали видеться ботом, зато иконки генералов из звезды - отлично распознавались, и команда стала работать как задумывалась. По этой причине я и создал этот issue и предложил убрать команду из релиза, из-за ее неоднозначности.
Плюс по отзыву на MySettlers было замечено, что при наличии у генерала навыка по захвату новиков, множественные всплывающие картинки тоже мешают адекватной работе этой команды. 
Но для меня загадкой остается такой парадокс - если дело в прозрачности или  еще в каких-то особенностях графики, то почему отскриненная больше года назад картинка с победой Сильваны прекрасно распознается ботом до сих пор безо всяких изменений и танцев с бубнами.
И второе - насколько я помню обсуждение с Jemxx, то он использует картинку со словами "Генерал одержал победу" и она тоже распознается несмотря на наличие прозрачности фона под текстом.
Другими словами, я сильно сомневаюсь, что дело только лишь в прозрачности всплывающего окошка.

Upd. Логика команды  sleepwhile2 работает - чтобы в этом убедиться, достаточно открыть в любом PictureViewer-e картинку с иконкой гены (sp*) и следом открыть картинку Gen_win.bmp, чтобы две картинки оказались одновременно на экране.

**Comment by ghost** [comment]
А почему тут 1й параметр у sleepwhile2 $generalData[0]? когда должно быть $generalData[3]?
```
		Case "ЖдемПобеду"
			$parametr = StringSplit($komanda[2], ",")
			$generalData = getGeneralData($parametr[1])
			Return sleepwhile2($generalData[0], $parametr[2], $parametr[3])

```

**Comment by ghost** [comment]
Заменил у себя, все пока работает. Но команда нуждается в тестировании на других разрешениях и на других компах.
и чтобы 2 раза не вставать - заменил sleepwhile2 на более изящную. If внутри while нужен для контроля срабатывания команды - если у других будет все ок, то его можно будет убрать из последующих релизов 

```
func sleepwhile2($img, $time, $flag)
	local $i = 0, $tolerance = 30, $fl_win = 0
	while ((haveimage($img, $tolerance) = 0) or (haveimage("media\Gen_win.bmp", $tolerance) = 0)) and ($i < ($time * 2))
		sleep(500)
		$i = $i + 1
		If (haveimage($img, $tolerance) = 1) and (haveimage("media\Gen_win.bmp", $tolerance) = 1) Then TrayTip("", "Генерал победил", 0)
	wend
	if ($i < ($time * 2)) or ($flag = 1) then
		Return 1
	else
		Return 0
	endif
endfunc

```

**Comment by jemxx** [comment]
> А почему тут 1й параметр у sleepwhile2 $generalData[0]? когда должно быть $generalData[3]?

Мне то откуда знать) Вы же ее делали)
Пока добавлю новый вариант. Если будут лучше варианты, заменим

Кстати зачем это нужно TrayTip("", "Генерал победил", 0) ? Меня например эти уведомления жутко бесят. Думаю я не один такой

**Comment by ghost** [comment]
Я уже понял почему. Я исходно планировал что не будет в конфиге прописываться имя файла из всплывающего окна, а будет к имени картинки в звезде дописываться принудительно "sp". Но Вы меня убедили, что это нехорошо) Поэтому у меня-то все в моем коде и работало, а вот в вышедшем релизе у других перестало, а я в этой части кода не проследил, а ковырял саму sleepwhile2. А вот потом я сам когда-то от своего кода перешел на работу с релизом, что и у меня перестало. 

> Кстати зачем это нужно TrayTip("", "Генерал победил", 0) ? Меня например эти уведомления жутко бесят. Думаю я не один такой

>  If внутри while нужен для контроля срабатывания команды - если у других будет все ок, то его можно будет убрать из последующих релизов
Он нужен для контроля - будет ли работать у других. Например, у Вас))  Иначе как узнать)

**Comment by jemxx** [comment]
Добавил в основную ветку. Тогда наверное пока можно прикрыть

**Comment by ghost** [comment]
Предлагаю оставить до результатов тестов, чтобы потом трайтип убрать, а то забудем

**Comment by jemxx** [comment]
Тогда их надо как то помечать. Переименовывать темы, добавлять какой то тег. Что то типа [ADDED] ЖдемПобеду

**Comment by ghost** [comment]
Я не нашел, как добавлять ярлыки. Может этот функционал доступен только Вам, как владельцу?
