### ISSUE TITLE
Конфиг файл

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#38]
Зря Вы задачу закрыли раньше времени, я хотел проверить раздел с бафами нового конфига (

Проверил все бафы (кроме нубов), но нубов Вы наверное и сами проверили.

БольшаяКатапульта
Стрела
ЧернаяСтрела
Баллиста
Убийца
ГорящаяСтрела
МаленькаяКатапульта
ШокоСтрела

Стрельнуть=Бронзоподкова
Стрельнуть=Платиноподкова
Стрельнуть=Обсидиановая
Стрельнуть=Титаноподкова
Стрельнуть=Мистикподкова

В архиве картинки для Стрелы из черного дерева (которая в Черном дереве) и Таинственной подковы (за золотые монеты в Эпичных)

[media.zip](https://github.com/jemxx/autobot/files/5471692/media.zip)

Вот думаю, может еще воронку из дерева добавить?

**Comment by jemxx** [comment]
> Зря Вы задачу закрыли раньше времени, я хотел проверить раздел с бафами нового конфига (

Я вобщем то тоже все бафы проверил и поэтом закрыл.

> Вот думаю, может еще воронку из дерева добавить?

Да, конечно нужно добавить. В подковы ее.  

> Стрельнуть=Обсидиановая

Может переименовать ее на Обсидподкова?

**Comment by ghost** [comment]
Можно, если я не путаю, это было в исходном боте такое название. Надо воронку отскринить и проверить, могу на тестовом проверить, и тогда сюда кину, добавите и закроете задачу.
Я не проверял ирмы, стейки и прочее, но думаю если работает стрельба по координатам, то и это должно работать, проблема может быть в картинках только. 

Upd
Проверил Ирму, НаноИрму, Стейк, логика работает, значит при добавлении картинок своих бафов все будет работать.
Проверил воронку, только она на вкладке "Разное". Скрин в приложении.
[voronka.zip](https://github.com/jemxx/autobot/files/5475586/voronka.zip)
