### ISSUE TITLE
Унаследованные "болячки" бота

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#39]
Вот пока ивент решил попробовать пролечить старые "болячки", который перешли в новую редакцию.
Из тех, которые заметил я 
1. При наборе армии в гену не всегда сбрасывает всех бойцов, а значит зацикливается при наборе.
Лечение пока тестирую, но сделал так
в globalfuncwar.au3 в двух функциях
applyarmy и apply_elitnoy_army

заменил строку

`zmemsmennuyukartinku("media\sbros.bmp", 50, "media\sbros_.bmp", 50)
`
на блок

```
While _imagesearch("media\sbros.bmp", 1, $tx, $ty, 50) = 1
		zmemsmennuyukartinku("media\sbros.bmp", 50, "media\sbros_.bmp", 50)
		sleep(500*$tormoza)
WEnd  
```
Пока тестирую 2й день, все бегает норм.

Кстати в этих же двух функциях у себя заметил, что осталось такое написание 
`
	$search = _imagesearch("media\0.bmp", 1, $tx, $ty, 20)
`

Не знаю, насколько это критично, но у себя заменил на 
`
	$search = _imagesearch("media\army_values\0.bmp", 1, $tx, $ty, 20)
`

2. При сборе элитной армии сбор идет от мечников до мастеров осады, в то время как при сборе обычной в обратном порядке - от пушкарей до новиков. Мне кажется, более целесообразно сбор элитной армии организовать аналогично.
В  globalfuncwar.au3 в функции sborostatkovarmii() заменил первый блок на следующий - переместил строки снизу наверх в обратном порядке

```
		If smena_armii($army_type) = 1 Then
			_imagesearch("media\mechnik.bmp", 1, $tx, $ty, 20)
			MouseClick("left", $tx + 332, $ty + 78, 1)
			MouseClick("left", $tx + 332, $ty + 24, 1)
			MouseClick("left", $tx + 208, $ty + 78, 1)
			MouseClick("left", $tx + 208, $ty + 24, 1)
			MouseClick("left", $tx + 83, $ty + 131, 1)
			MouseClick("left", $tx + 83, $ty + 78, 1)
			MouseClick("left", $tx + 83, $ty + 24, 1)
			Sleep(500 * $tormoza)
			Return okclose_elitnoy_gena(1)
		EndIf
``` 

3. Иногда после паузы (F9) бот начинает мазать мимо окошка для набора юнитов. Как итог - бот циклится, т.к. мажет мимо окошка, Как лечится - пока не знаю.

**Comment by jemxx** [comment]
С набором армии тут вобще полная жопа. Не так давно пытался разобраться с проблемой, когда юнитов не хватает до набора и бот зацикливается. Вопрос пока не решил, точнее знаю как его решить, но дошел до момента 

```
While apply_elitnoy_army($parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $full, 2) <> 1
						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
						openGenaOnpxp($userDIR & $parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16])
					WEnd

```

и задумался, а нафига везде в наборе нужен этот цикл? По факту в нем и проблема при наборе. Бот никогда не остановится, пока не наберет нужное количество. В идеале нужно сделать, что если бот не может набрать, то нужно останавливаться с ошибкой. Сейчас такого нет.

**Comment by ghost** [comment]
По набору, может внешний цикл прикрутить? Бот пробует набрать допустим 5 раз, если не набрал, то вылетает с ошибкой.
Кстати, проблема под номером три, если я не путаю, вылезает только при наборе простой армии.

Еще думал над командой "ДобавитьНовиков", не стрельнуть в гену, а докинуть арму новами. Например, я в Нордике воюю одним составом в Старшем (100 Ар, 95 ДЛ и новы), сейчас бот каждый раз набирает этот состав по новой, а так докидывал бы только новов - выигрыш по времени на мелких приклах. Сначала подумал добавить ко всем командам с набором армы еще параметр Н, кроме Э. П и 1, т.к. не хотелось плодить кучу команд, Но задумался, что аналогично надо будет делать с КМ, Рыц и мечниками. с КМ точно, например, я в Юном почти везде бью в Борисе одним составом 20 КМ и 175 КС. 
Что скажет? Функционал для этого частично есть - коры окошек при сборе армии. Сделать отдельную функцию из функции сбора с параметром, кого докидывать, которая будет щелкать по месту правее ползунка в нужном месте, добивая юнитов этого типа до максимума.

Кстати, проблема аналогичная описанной под номером 1 встречается при отправке в прикл с флагом 2. Не всегда Ок корректно нажимается, и бот стопается. Туда тоже надо бы прикруть while, как сделаю и проверю - скину сюда.

**Comment by ghost** [comment]
По пункту 2 поспешил, понадеявшись на логику автора - опять не совсем как нужно собирает элитную армию. Ивент закончился, постараюсь в ближайшие дни запостить сюда нужный порядок:  Осадники->КС->Броневики->Стрелки->Рыцари->КМ->Мечники 

UPD
Вот верный порядок при сборе остатков элитной армии

```
		If smena_armii($army_type) = 1 Then
			_imagesearch("media\mechnik.bmp", 1, $tx, $ty, 20)
			MouseClick("left", $tx + 83, $ty + 131, 1) ; мастера осады
			MouseClick("left", $tx + 332, $ty + 78, 1) ; конные стрелки
			MouseClick("left", $tx + 208, $ty + 78, 1) ; стрелки в броне
			MouseClick("left", $tx + 83, $ty + 78, 1)  ; стрелки
			MouseClick("left", $tx + 332, $ty + 24, 1) ; рыцари
			MouseClick("left", $tx + 208, $ty + 24, 1) ; конные мечники
			MouseClick("left", $tx + 83, $ty + 24, 1)  ; мечники
			Sleep(500 * $tormoza)
			Return okclose_elitnoy_gena(1)
		EndIf
```
