### ISSUE TITLE
ЖдемГенерала и ЖдемВсехГенералов

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#4]
Придумать, как минимизировать переоткрытие звезды при ожидании генерала

**Comment by ghost** [comment]
Частично вопрос решил - убрал закрытие звезды, когда уже некуда листать и увеличил тайминг до 30 сек. Потестирую такой вариант - если все будет норм, задачу закрою

**Comment by ghost** [comment]
Вроде все работает, залил за-pull-ил реквест в основную ветку.

**Comment by ghost** [comment]
Че там этот утырок **LEKALA (ака Андрей)** хотел славы?)) да легко. Поскольку программировать он тольком не умеет, но идеи выдвигает здравые, то я учел его пожелание не листать лишний раз звезду и не ждать лишних секунд, и модифицировал команды ЖдемГенерала и ЖдемВсехГенералов 

Теперь количество листаний звезды завязано на строку в ини-файле
`Всего_генералов=100 `

Т.е. расчитывается исходя из числа имеющихся у игрока генералов, число видимых строк. Команды будут ждать максимально 15 минут, если не дождутся - вылетят с ошибкой. Список ген прокручивается с задержкой в одну секунду
У меня 99 ген (с учетом экспедиционных, но они все равно перемешаны с основными, поэтому я их тоже учел), с таким количеством звезда листанется два раза + начальный экран, т.е. всего бот просмотрит три экрана с генами

функция ozidanierasstanovki2 в globalfuncWAR.au3 

```
Func ozidanierasstanovki2($image, $yes)
; Ждем одного генерала
    ;writelog("=====ОЖИДАЕМ ПЕРЕСТАНОВКу " & $yes & @CRLF)
	Local $tx = 0, $ty = 0, $ii = 1, $i = 0, $fl = 0, $count_list = 5, $count_line = 4, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране звезды (4 видимых строки по 9 ген в строке)
	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line))
	Sleep(500 * $tormoza)
	while ($i < 900) ; макисмальное время ожидания в секундах (15 минут)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		$ii = 1
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) Then
				$fl = 1
				ExitLoop
			Else
				zvezdamovepolzunokdown(1)
				$ii = $ii + 1
				If $ii > $count_list Then ExitLoop
;~ 				If (zvezdamovepolzunokdown(1) = 0) then
;~ 					; zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
;~ 					ExitLoop
;~ 				EndIf
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(1000)
	Wend
	If ($fl = 1) and ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
	If $i = 900 Then
		;writelog("=====ОШИБКА " & $i & @CRLF)
		Return 0
	EndIf
	;writelog("=====УСПЕХ " & $i & @CRLF)
	Return 1
EndFunc
```

функция ozidanierasstanovki в globalfuncWAR.au3 

```
Func ozidanierasstanovki($image, $image_NA, $yes)
; Ждем всех генералов
    ;writelog("=====ОЖИДАЕМ ПЕРЕСТАНОВКу " & $yes & @CRLF)
	Local $tx = 0, $ty = 0, $ii = 1, $i = 0, $fl = 0, $count_list = 5, $count_line = 4, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране звезды (4 видимых строки по 9 ген в строке)
	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line))
	Sleep(500 * $tormoza)
	while 1 AND ($i < 900) ; макисмальное время ожидания в секундах (15 минут)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		$ii = 1
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) AND (_imagesearcharea($image_NA, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 0)  Then
				$fl = 1
				ExitLoop
			Else
				zvezdamovepolzunokdown(1)
				$ii = $ii + 1
				If $ii > $count_list Then ExitLoop
;~ 				If (zvezdamovepolzunokdown(0) = 0) then
;~ 					; zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
;~ 					ExitLoop
;~ 				EndIf
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(1000)
	Wend
	If ($fl = 1) and ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
	If $i = 900 Then
		;writelog("=====ОШИБКА " & $i & @CRLF)
			Return 0
	EndIf
	;writelog("=====УСПЕХ " & $i & @CRLF)
	Return 1
EndFunc

```

Проверил - вроде работает, но еще погоняю

**Comment by LEKALA** [comment]
Ну вот реально забавно!)) Если взять за хибо и потрясти уклунка васюта, то можно получить не просто гнилую вонь) но и очень изящное решение по числу листания экранов в звезде! )) Разве не чудо?))

Теперь по делу. Функция ozidanierasstanovki2($image, $yes) в прикле работает абсолютно адекватно и не зависит от числа ген, указанных в autobot.ini  Это хорошо)
Что касается домашнего острова:
1. Если в autobot.ini указано 36 ген, то не увидев гену на первом экране, листает на второй экран (при 72 листает на третий) но на втором экране заданного гену не видит, даже если он там есть.
2. На втором экране видит заданного гену только,  если в autobot.ini указано количество ген 72 и более. При этом, не найдя гену на втором экране листает на 3-й экран 
3. Если нагрузить комп кучей открытых браузеров, то команда перестаёт находить гену при листании экранов. Думаю в начало петли, перед _imagesearcharea следует вставить Sleep(500 * $tormoza), из-за неуспевона проца компа или тырнета..
4. У меня сложилось впечатление, что при любом количестве генералов, указанном в autobot.ini, не кратном 36 функция не видит ген, даже если листнула экран и на новом экране гена присутствует...

**Comment by LEKALA** [comment]
И вот наконец о главном: если допустим у игрока заданный гена находится на 5-м экране и данная команда найдёт его там, и допустим выполняется следующий текст:
ЖдемГенерала=Скрытный,0
Набрать=Скрытный,1,Э,0,0,0,0,0,150,0,1
то команда Набрать снова кликнет во вкладку спецы и перекинет игрока на первый экран, откуда листая по одной строке начнёт искать заданного гену для набора.(( Судя по всему, нужно в функциях типа applyarmy предусмотреть проверку статуса активности вкладки спецы, и если она активна, то не кликать в неё.

**Comment by ghost** [comment]
На экран помещается 4 полных строки генералов, по крайней мере сейчас.
Можно в комагде ЖдемВсехГенералов, чтобы избежать проблемы разноса ожидаемых ген по разным экранам, листать не на весь экран, а три раза по одной строке. Тем самым при таком листании последняя полная строка всегда будет самой верхней.
Единственная проблема в этом случае, которую я вижу - это ожидание всех генералов, если они растянутся на 3 строки, т.е. их больше чем (9*2) + 1.
