### ISSUE TITLE
Поправка для функций НаборИАтакаПоКоординатам/НаборИПереносПоКоординатам  при наличии в генерале 1го юнита  

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#40]
По поводу ошибки при наборе/атаке по координатам с 1Н, я этот функционал не юзаю, поэтому не тестировал, там if надо в другом месте закрыть
Не после Return-a, а до него, 
т.е. заменить

```
    Return atakalageraotkritimgenoynoini()/perenosotkritimgenoynoini()
EndIf	

```
на 
```
EndIf	
Return atakalageraotkritimgenoynoini()/perenosotkritimgenoynoini()

```

**Comment by Marsik-A** [comment]
По поводу ошибки при наборе/атаке по координатам с 1Н, я этот функционал не юзаю, поэтому не тестировал, там if надо в другом месте закрыть
Не после Return-a, а до него, 
т.е. заменить

```
    Return atakalageraotkritimgenoynoini()/perenosotkritimgenoynoini()
EndIf	

```
на 
```
EndIf	
Return atakalageraotkritimgenoynoini()/perenosotkritimgenoynoini()

```

**Comment by Marsik-A** [comment]
Поскольку этот долбоклюй никак не угомонится, я вынужден откланяться. Jemxx, спасибо за сотрудничество 
http://prntscr.com/vmfbtw

**Comment by jemxx** [comment]
Даже интересно стало, где вы такую интересную беседу ведете?

**Comment by Marsik-A** [comment]
Человек явно болен и серьезно. Скрин с канала на дисмейле, оттуда я тоже вышел.

**Comment by jemxx** [comment]
В игнор бы отправили и да все. Видно же, что по другому проблему не решить.

**Comment by Marsik-A** [comment]
Тут нет игнора, а блок юзера (что давно сделано) не позволяет только комментировать его задачи, а беспочвенные, и тем более бредовые измышления мне читать надоело.

**Comment by jemxx** [comment]
Не обращайте внимание на разные звуки. Ведь нам остается всего то до нового года.. А дальше наверно все..

**Comment by jemxx** [comment]
В телеграм мне напишите

**Comment by Marsik-A** [comment]
Как Вас в телеге найти?

**Comment by jemxx** [comment]
Забыл, что там немного по другому @jemmxx

**Comment by Marsik-A** [comment]
Как я понимаю, надобность в телеге пока отпала)

**Comment by ghost** [comment]
Jemxx, поправьте это.
В том коде, что здесь на гитхабе поменять местами строки 425 и 426 для атаки
https://github.com/jemxx/autobot/blob/6c32369b44021392390b5b9e1af981ce38e73550/autobot.au3#L425
https://github.com/jemxx/autobot/blob/6c32369b44021392390b5b9e1af981ce38e73550/autobot.au3#L426

и строки 485 и 486 для переноса
https://github.com/jemxx/autobot/blob/6c32369b44021392390b5b9e1af981ce38e73550/autobot.au3#L485
https://github.com/jemxx/autobot/blob/6c32369b44021392390b5b9e1af981ce38e73550/autobot.au3#L486
