### ISSUE TITLE
в21 спецы не ищют приключения

### ISSUE THREAD

**Issue by tester2121212121** [jemxx/autobot#41]
20 видит, 21 не видит иконки poisk_prikla.bmp 
возможно нужно пересканировать, но хочется понять по какому принципу новый бот не видит шаблонов

**Comment by ghost** [comment]
Что такое 20 и 21? Версии? Конфиг проверьте, какие именно разведчики не ищут приклы? Каков формат строки поиска?

**Comment by tester2121212121** [comment]
ни какие не ищут, выше написал не видит иконки прикла. все одинаково, только версии ехе разные

**Comment by ghost** [comment]
Вот только что отправил - все кто надо ушли за приклами. Уверены, что все картинки одинаковые?  Вы обновляете весь каталог или только exe?

**Comment by tester2121212121** [comment]
на консоли работает, в виртуалке не видит ... странно
