### ISSUE TITLE
Бот и телеграм

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#42]
Интересен ли функционал отправки сообщения об ошибке в телеграм-бот?

**Comment by ghost** [comment]
Будет немного сумбурно и вставки в разные места.

Для начала в юнит глобалвар.ау3 добавляем две функции

```
Func _URIEncode($sData) ; https://www.autoitscript.com/forum/topic/95850-url-encoding/
    ; Prog@ndy
    Local $aData = StringSplit(BinaryToString(StringToBinary($sData,4),1),"")
    Local $nChar
    $sData=""
    For $i = 1 To $aData[0]
        $nChar = Asc($aData[$i])
        Switch $nChar
            Case 45, 46, 48 To 57, 65 To 90, 95, 97 To 122, 126
                $sData &= $aData[$i]
            Case 32
                $sData &= "+"
            Case Else
                $sData &= "%" & Hex($nChar,2)
        EndSwitch
    Next
    Return $sData
EndFunc

Func Telegram_bot($tgChatId, $Message)
	local $sText, $sBot_token  ;~ это token Телеграмм-бота
	$sText =  _URIEncode($Message)
	ConsoleWrite(InetRead('https://api.telegram.org/' & $sBot_token & '/sendMessage?chat_id=' & $tgChatId & '&text=' & $sText, 0))
EndFunc

```
Функции не мои, взял с форума по автоиту, чуть облагородил  и проверил на работоспособность. Зачем нужно декодирование, хз, но убирать его не рискнул.

Теперь правки в основной юнит.

Объявляем две глобальных переменных 

`$sreport = 0, $schat_id`

в ини файл добавляем две строки: 14ю и 15ю. В 13й у нас пока живет заголовок окна. 

```
Telegram_bot=0
chat_id=
```
chat_id - это идентификатор чата с ботом, берется из Телеграм-бота по определению ИД беседы
По умолчанию предлагаю задать Telegram_bot=0, а для отправки в телегу - юзер выставляет любое другое значение. Настройки для продвинутых, так что человек должен понимать, что он делает.
  
В основной массив обработки событий  вот после этих строк

```
If GUICtrlRead($alarmCheckBox) == $GUI_CHECKED Then
	$alarm = 1

```
добавляем проверку состояния флага - надо ли транслировать в телегу и если надо - проверяем не пуст ли $schat_id, хотя если пуст, то наш бот не стопнется, а будет слать сообщения в никуда

```
					If read_ini(14) <> 0 Then
						$schat_id = read_ini(15)
						If $schat_id = "" Then
							MsgBox(0, "Внимание!!!", "Вы выбрали режим трансляции ошибок телеграмм-боту, но не указали Chat_ID!")
							Exit
						Else
							$sreport = 1
						EndIf
					EndIf

```

Теперь добавляем собственно трансляцию в телеграм

Я выбрал три места 

1й случай  - прошли нужное число раз
в функции gogogogo при проверке сколько уже прошли заменил код на следующий

```
		If (GUICtrlRead($pass_cnt) = 0) Then ; кончились прохождения
				If $alarm = 1 Then alarmBeep()
				If $sreport = 1 Then Telegram_bot($schat_id, "Прошли нужное количество")
				MsgBox(0, "Закончили", "Прошли нужное количество")
				ExitLoop
		EndIf

```

2й случай  - бот стопнулся с ошибкой

ниже в этой же функции где считывается строка заменил код на следующий
На самом деле проще привязаться к проверке флага 
`			If $alarm = 1 Then alarmBeep()
`
после него добавил вызов функции посылки инфы в телегу 

```
		If komanda($delaem) = 1 Then
			printerror("Команда из " & $i & " строки." & @CR & @CR & "Делаем: " & $delaem & @CR & "С параметром: " & $komanda[2] & @CR & @CR & "ВЫПОЛНЕНА УСПЕШНО")
		Else
			If $alarm = 1 Then alarmBeep()
			If $sreport = 1 Then Telegram_bot($schat_id, "СТОП! Из строки " & $i &  " мы не смогли сделать " & $stroka)
			printerror("Команда из " & $i & " строки." & @CR & @CR & "Делаем: " & $delaem & @CR & "С параметром: " & $komanda[2] & @CR & @CR & "НЕ ВЫПОЛНЕНА. ОСТАНАВЛИВАЕМСЯ")
			MsgBox(0, "ВНИМАНИЕ!!!", "Из строки " & $i & @CR & "Мы не смогли сделать" & @CR & @CR & $stroka & @CR & @CR & "поэтому и остановились(((")
			GUICtrlSetData($file_gui2, $i)
			ExitLoop
		EndIf

```

3й случай (опционно, я себе добавил) - бот посылает сообщение на экран.

Код обработки команды "Сообщение" заменил на следующий

```
		Case "Сообщение"
			If $sreport = 1 Then Telegram_bot($schat_id, $komanda[2])
			MsgBox(0, "Сообщение", $komanda[2])
			Return 1

```

Вроде ничего не забыл.

Если все будет работать, то допишу инструкцию для файла помощи

**Comment by ghost** [comment]
Пардон, забыл один амперсенд в блоке, где ошибка выводится (2й случай), код в предыдущем сообщении поправил. Jemxx, если Вы уже вставили этот блок, замените пож-та.
Вот тут ошибся, после $i забыл еще конкатенацию сделать
`"СТОП! Из строки " & $i &  " мы не смогли сделать "`

**Comment by jemxx** [comment]
`If $schat_id = "" Then
							MsgBox(0, "Внимание!!!", "Вы выбрали режим трансляции ошибок телеграмм-боту, но не указали Chat_ID!")
							Exit
						Else`

Скажите, а для чего останавливать работу бота если не заполнено Chat_ID ? Просто не слать сообщение и все.

**Comment by jemxx** [comment]
Предлагаю просто сделать проверку. без остановки бота

```
$sBot_token = ReadINI("telegram", "telegram_bot_token", "")
$schat_id = ReadINI("telegram", "telegram_chat_id", "")
						
If $schat_id <> "" And $sBot_token <> "" Then
  $sreport = 1
EndIf`

**Comment by jemxx** [comment]
А еще лучше эти проверки делать в самой функции Telegram_bot

```
Func Telegram_bot($Message)
	Local $bot_token = ReadINI("telegram", "telegram_bot_token", "")
	Local $chat_id = ReadINI("telegram", "telegram_chat_id", "")

	If $chat_id <> "" And $bot_token <> "" Then
		ConsoleWrite(InetRead('https://api.telegram.org/' & $bot_token & '/sendMessage?chat_id=' & $chat_id & '&text=' & _URIEncode($Message), 0))
	EndIf
EndFunc
`

**Comment by ghost** [comment]
да на самом деле без разницы, где реализуете. Главное, чтобы эти проверки были. 
Пусть будут в теле бота. Остановку я делал на случай, если кому-то это сильно важно - трансляция в телегу, чтобы не забыли включить. А то будут удивляться, почему не транслирует. Это делается один раз и на всю жизнь)
Если без остановки бота - то пусть будет в теле, если с остановкой - то в теле плохо, т.к. бот стопнется по ходу исполнения, а это не всегда приятно.   

ЗЫ. По сути если поля пустые - то инфа уйдет в "мировой эфир" и ничего криминального не случится, а вот если игрок ждет инфы в телеге, а ее нет - то скорее он подумает, что тсо_бот неисправен, чем о своей забывчивости) Может так нелюбимый Вами TrayTip добавить?)

```
Func Telegram_bot($Message)
	Local $bot_token = ReadINI("telegram", "telegram_bot_token", "")
	Local $chat_id = ReadINI("telegram", "telegram_chat_id", "")

	If $chat_id <> "" And $bot_token <> "" Then
		ConsoleWrite(InetRead('https://api.telegram.org/' & $bot_token & '/sendMessage?chat_id=' & $chat_id & '&text=' & _URIEncode($Message), 0))
        Else
           TrayTip("", "Выбран режим трансляции ошибок телеграмм-боту, но не указан Token и/или Chat_ID!", 0)
	EndIf
EndFunc
```


ЗЫЫ Нужна инструкция как создавать бот в телеге и что за token и chat_id? или кому надо - итак знают?

**Comment by jemxx** [comment]
> ЗЫЫ Нужна инструкция как создавать бот в телеге и что за token и chat_id? или кому надо - итак знают?

Если напишите ее, лишней не будет.

>  Может так нелюбимый Вами TrayTip добавить?)

Думаю здесь это уместно.

> если кому-то это сильно важно - трансляция в телегу, чтобы не забыли включить

Согласитесь, если это важно, то не забудете. Поэтому стоп бота излишен.

**Comment by ghost** [comment]
> Согласитесь, если это важно, то не забудете. Поэтому стоп бота излишен.

Опыт общения с пользователями бота как раз показывает обратное, что гораздо чаще "бот не работает", чем "ой, я обсчитался с параметрами" или "я забыл".
Ок, напишу и добавлю сегодня к вечеру.

**Comment by ghost** [comment]
~Не увидел, как у Вас называется параметр в ini, который отвечает за вкл/выкл трансяции в телеграм-бот, чтобы добавить его в инструкцию.~ 
Все увидел в поправленном коде уже.

1. Регистрация своего  Telegram-бота
Для регистрации используем специального бота — @botfather.
Находим его и пишем ему /start. Далее создаем нового бота командой /newbot. Придумываем имя, которое должно заканчиваться на «bot». В случае успеха BotFather возвращает токен бота и ссылку для быстрого добавления бота в контакты. 
Добавляем созданного бота в контакт-лист и на всякий случай запускаем его командой /start. Полученный на этом этапе токен заносим в ini файл в поле "telegram_bot_token" 

2. Получение уникального chat_id
Для этого испльзуем другой бот - @getidsbot. Находим и пишем ему /start, в ответ получаем информацию о своем аккаунте, в том числе и уникальный id, который записываем в ini файл в поле "telegram_chat_id" 

3. Не забываем указать, что нужна трансляция в Telegram-бот, за это отвечает параметр "telegram_bot" в ini-файле: 0 - трансляция выключена, 1 - включена.

**Comment by jemxx** [comment]
Могу эту ишью закрыть?

**Comment by jemxx** [comment]
> TrayTip("", "Выбран режим трансляции ошибок телеграмм-боту, но не указан Token и/или Chat_ID!", 

Держу в уме. Следующем комитом добавлю

**Comment by ghost** [comment]
Если про ТрайТип не забудете - то да, можно закрыть. Но я бы оставил свою проверку на старте, а не в самой функции Telegram_bot, заменив стоп бота на вывод системного предупреждения.

**Comment by jemxx** [comment]
Добавил ТрайТип. На самом деле не важно где проверка, но лучше это делать в функции. Все работу должна делать функция. Вы же ее просто должны вызывать.
Ну и самый важный момент, что отправка в телегу будут работать только при включенной тревоги. Это так задумано? Тогда это в справке нужно отобразить. Но и в целом это верно

`If GUICtrlRead($alarmCheckBox) == $GUI_CHECKED Then`

**Comment by ghost** [comment]
Нет, не было задумано, но Вы мой код проверки переделали, когда взводить флаг $report - убрали проверку при запуске бота.. Теперь в новой версии кода этот флаг не нужен, напрямую читаем из ini значение параметра telegram_bot и обрабатываем: если telegram_bot = 1 то рапортуем с проверками двух других параметров

https://github.com/jemxx/autobot/commit/dfe69d9d89c7a4c659e81a725227cfa6f14af19d#r44916702

**Comment by jemxx** [comment]
Вообще то у вас изначально было так . Посмотрите что вы выкладывали выше

```
В основной массив обработки событий вот после этих строк

If GUICtrlRead($alarmCheckBox) == $GUI_CHECKED Then
	$alarm = 1

добавляем проверку состояния флага - надо ли транслировать в телегу и если надо - проверяем не пуст ли $schat_id, хотя если пуст, то наш бот не стопнется, а будет слать сообщения в никуда`

**Comment by jemxx** [comment]
`но Вы мой код проверки переделали, когда взводить флаг $report - убрали проверку при запуске бота`

Проверятся должно не посредственно когда это нужно. При запуске бота это совсем не нужно.

**Comment by ghost** [comment]
Там почему-то поехало форматирование и $alarm перенесся на новую строку, у Вас-то он в одну строчку и EndIf ему не нужен.

А в моем коде тоже поехало форматирование, но два if-а и два EndIf-a их их закрывающих. Но Вы один мой If убрали,  а EndIf-а оставили два.
```
If read_ini(14) <> 0 Then
	$schat_id = read_ini(15)
	If $schat_id = "" Then
		MsgBox(0, "Внимание!!!", "Вы выбрали режим трансляции ошибок телеграмм-боту, но не указали Chat_ID!")
		Exit
	Else
		$sreport = 1
	EndIf
EndIf
```

предлагаю оставить две строки с условиями, я там в коммите пометил

**Comment by ghost** [comment]
Прошу прощения, я понял свою ошибку.
Никак не могу привыкнуть, что однострочный оператор надо все равно заканчивать endif-ом, у меня чуть другой код, поэтому и накладка вышла.
проверка аларам отдельно, проверка на телеграм_репорт отдельно
