### ISSUE TITLE
ЖдемВсехГенералов с умным листанием

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#43]
В чём собственно состоит "умное листание"? Оно заключается в реализации такого подхода, при котором бот сначала находит экран, на котором расположены или **активные И неактивные**, или **только неактивные** картинки нужных ген, располагает эти картинки в трёх верхних строках, затем прекращает листание и начинает ждать исчезновения неактивных картинок. Когда все неактивные картинки исчезнут, бот фиксирует факт наличия только активных и закрывает функцию "УСПЕХОМ". 
Основное логическое ограничение - количество ген любого типа не может превышать 3 строки на любом из экранов.
Для реализации изложенного подхода были выделены 4 логических состояния картинок нужных генералов:

1. Видим активные И неактивные картинки
2. Видим только неактивные картинки
3. Не видим ни активных, ни неактивных картинок
4. Видим только активные картинки

Случай **"Видим активные И неактивные картинки"** контролирует площадь окошка в 4 строки. Если условие истинно, то:
Для звезды на домашнем острове - располагает даже одну ЛЮБУЮ картинку (активную или неактивную) в верхней строке экрана. Начинает ждать исчезновения неактивных картинок. Когда неактивные картинки исчезнут, условие перестаёт быть истинным.
Для звезды в приключении - видит отсутствие ползунка, поэтому просто ждёт исчезновения неактивных картинок. Когда неактивные картинки исчезнут, условие перестаёт быть истинным.

Случай **"Видим только неактивные картинки"** контролирует площадь окошка в 4 строки. Если условие истинно, то:
Для звезды на домашнем острове - располагает даже одну неактивную картинку в верхней строке экрана. Начинает ждать исчезновения неактивных картинок. Когда неактивные картинки исчезнут, условие перестаёт быть истинным.
Для звезды в приключении - видит отсутствие ползунка, поэтому просто ждёт исчезновения неактивных картинок. Когда неактивные картинки исчезнут, условие перестаёт быть истинным.

Случай **"Не видим ни активных, ни неактивных картинок"** контролирует площадь окошка в 3 строки. Если условие истинно, то:
Для звезды на домашнем острове - листает 3 строки, добавляет 1 к счётчику экранов. На следующем цикле, если опять ничего не найдено, снова листает 3 строки и опять добавляет 1 к счётчику экранов. И так далее, пока не исчерпаются экраны для листания. Количество экранов определяется по методу, предложенному **Marsik-A**, на основании количества генералов, указанного в **.ini** файле. Если на экране (три верхних строки) появляется активная или неактивная картинка нужного генерала, то условие перестаёт быть истинным. Если все экраны пролистаны, а условие по-прежнему истинно, то формируется +1 для счётчика большого цикла, в котором бот снова нажмёт вкладку "специалисты" и снова начнёт листать экраны по 3 строки. Если условие продолжает оставаться истинным, то формируется ОШИБКА бота - **Вы не владеете генералами указанного типа или указанный тип не отправлен в приключение, или указанный тип не вернулся из приключения.**
Для звезды в приключении - видит отсутствие ползунка, поэтому участвует только в формировании ОШИБКИ - **указанный тип генералов не отправлен в приключение**

Случай **"Видим только активные картинки"** контролирует площадь окошка в 3 строки. Этот случай выполняется только, если все три предыдущих случая не являются истинными. Если условие истинно, то:
Для звезды на домашнем острове - располагает даже одну активную картинку в верхней строке экрана. Проверяет наличие ТОЛЬКО АКТИВНЫХ картинок в первых трёх строках экрана. Если условие истинно, то выходит из большого цикла и далее функция закрывается "УСПЕХОМ"
Для звезды в приключении - никаких дополнительных действий не требуется.

**Ограничение для пользователя** - генералы должны быть переименованы таким образом, чтобы все генералы любого типа были бы расположены на экране звезды цепочкой - подряд, друг за другом, без разрывов.

**Теперь собственно код**
заменить код функции **ozidanierasstanovki($image, $image_NA, $yes)** на следующий:
```
Func ozidanierasstanovki($image, $image_NA, $yes)
	; Ждём всех генералов от LEKALA (ака Андрей)
	Local $tx = 0, $ty = 0, $i = 1, $ii = 0, $count_list = 5, $count_line = 3, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране звезды (3 верхних строки по 9 ген в строке) Идея и реализация от Marsik-A.
	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line))
	Sleep(500 * $tormoza)
	openzvezdap()
	while ($ii < 2)
		selecttabatzvezda("specialisti", 0)
		$i = 1
		sleep(500*tormoza)
		while ($i < $count_list)
			Select
				Case haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) = 1 AND haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) = 1	
					If (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) = 0 Then
						TrayTip("Отсутствует ползунок", "Нашли и активных, и пассивных на одном экране, ждём пропадания пассивных до 5 мин.", 5)
						sleepNOwhile($image_NA, 30, 300)
					EndIf					
					;Если условие выполняется на 4 строки, то проверяем выполнение условия в первой строке.
					while (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) <> 0
						TrayTip("Видим разных", "Нашли и активных, и пассивных, листаем по 1 строке до первой и ждём пропадания пассивных до 5 мин", 5)
						If (haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 1) OR (haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 1) Then
							sleepNOwhile($image_NA, 30, 300)
							ExitLoop 
						Else
							zvezdamovepolzunokdown(0)
						EndIf
					Wend
					$i = $i + 1
				Case haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) = 1 AND haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) = 0	
					If (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) = 0 Then
						TrayTip("Отсутствует ползунок", "Нашли только пассивных на одном экране, ждём пропадания пассивных до 5 мин.", 5)
						sleepNOwhile($image_NA, 30, 300)
					EndIf					
					;Если условие выполняется на 4 строки, то проверяем выполнение условия в первой строке.
					while (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) <> 0
						TrayTip("Видим только пассивных", "Нашли только пассивных, листаем по 1 строке до первой и ждём пропадания пассивных до 5 мин", 5)
						If (haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 1) AND (haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 0) Then
							sleepNOwhile($image_NA, 30, 300)
							ExitLoop
						Else
							zvezdamovepolzunokdown(0)
						EndIf
					Wend
					$i = $i + 1
				Case haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 82) = 0 AND haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 82) = 0
					If (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) = 0 Then
						TrayTip("Отсутствует ползунок", "Не нашли ни активных, ни пассивных на одном экране. Надо куда-то выйти", 5)
						ExitLoop
 					EndIf					
					TrayTip("Не видим никого", "Не нашли ни активных, ни пассивных, листаем 3 строки", 5)
					zvezdamovepolzunokdown(0)
					zvezdamovepolzunokdown(0)
					zvezdamovepolzunokdown(0)
					sleep(500*tormoza)
					$i = $i + 1
				Case Else
					If (haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 82) = 0) AND (haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 82) = 1) Then
						while (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) <> 0
							If (haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 0) AND (haveimageAREA($image, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 250) = 1) Then
								ExitLoop
							Else
								zvezdamovepolzunokdown(0)
							EndIf
						Wend
						TrayTip("Видим только активных", "Нашли только активных, выходим", 5)
						ExitLoop 2
					EndIf
			EndSelect		
		Wend
		$ii = $ii + 1
		If $i > $count_list Then ExitLoop	
	Wend
	If $ii = 2 Then
		TrayTip("ОШИБКА", "Не нашли ни одного из выбранных ген!", 5)
		Return 0
	EndIf
	If ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
		TrayTip("УСПЕХ", "Нашли только активных из выбранных ген!", 5)
	Return 1
EndFunc
```
**ВНИМАНИЕ!** Использование данной функции в текстах однозначно требует срочного изменения команд **"Набрать"** и **"Отправить"**
Попробуйте например выполнить следующий текст:
ЖдемВсехГенералов=Простой,0
Набрать=Простой,3,Э,0,0,0,0,0,1,0,1

**Comment by LEKALA** [comment]
5 суток прошло... комментов - ноль( Никто не заинтересован в наличии такой функции и в тестировании кода?

**Comment by jemxx** [comment]
Я от вас так и не дождался решения по команде ЖдемПобеду. Я могу ее удалить уже?

**Comment by LEKALA** [comment]
Извините, но я не восьмирукий семичлен. Я только на тестирование и отладку этой функции потратил полторы недели. Что касается Ждем Победу, то тут всё будет зависеть от Вашего решения.
В используемой в данный момент библиотеке Globalfunc.dll видимо отсутствует параметр $transparency (прозрачность) для функции _ImageSearchArea, поэтому использование такой вот графики: 
![gen_win](https://user-images.githubusercontent.com/70764669/99877856-c5375e00-2c09-11eb-8d4b-903bb9a9cf76.png)
для текста на прозрачном фоне пока не возможно.
Это можно будет использовать, если подгрузить в бота исправленную библиотеку, о которой прочитать можно вот здесь: 
https://www.autoitscript.com/forum/topic/148005-imagesearch-usage-explanation/page/3/?tab=comments#comment-1263796
или вот здесь: https://macroforge.wordpress.com/2019/06/08/using-image-search-in-autoit/
Сам код функции sleepwhile2 никакого интереса не представляет и его конечно можно удалить. Главное, чтобы Вы определились, включить ли новую исправленную библиотеку, и сохранили бы ссылки на графику ген в .json файле.

**Comment by jemxx** [comment]
Хорошо, почитаю сегодня что пишут.

**Comment by LEKALA** [comment]
https://github.com/jemxx/autobot/issues/37#issuecomment-719028445
Я так понял, что с командой ЖдемПобеду, по убедительному нытью неколлеги, покончено? 
jemxx, никаких новых библиотек Вы не собираетесь подвязывать к боту?
Стоит ли мне тогда заниматься кодом ЖдемГенерала с умным листанием и устранять кривокод в командах Набрать и Отправить? Или неколлега опять поскулит, и Вы с уважением к его авторитету, оставите в релизе весь его кривокод?

**Comment by jemxx** [comment]
Вы делаете какие то выводы основываясь непонятно на чем. Нужно посмотреть, если изменение библиотеки не потребует за собой правки всех функций то почему бы и не заменить.

**Comment by LEKALA** [comment]
Извините, но вывод напросился сам, после прочтения Вашей реплики, которая тут процитирована.
С Вашим подходом, не допускающим противоречий между библиотеками я полностью согласен.
Ну и основное - стоит ли мне продолжать работу над преодолением указанных мною выше проблем? Это востребовано?
Это имеет шансы на включение в релиз?

**Comment by jemxx** [comment]
> Ну и основное - стоит ли мне продолжать работу над преодолением указанных мною выше проблем? Это востребовано?
Это имеет шансы на включение в релиз?

Конечно продолжайте. Сегодня добавлю эту функцию в основную ветку. немного по тестировал. Единственное нужно убрать только TrayTip, бесят они постоянно выскакивая.

**Comment by LEKALA** [comment]
Да, TrayTip нужно убрать. Они были включены только с целью тестирования и отладки.

**Comment by jemxx** [comment]
Добавил в основную ветку.
