### ISSUE TITLE
Сброс номера строки и количества проходов при выборе нового файла из Комбо

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#44]
Приведенный ниже код нужно вставить вот сюда
http://prntscr.com/vn3t73

```
			Case $file_gui
				GUICtrlSetData($file_gui2, "1")
				GUICtrlSetData($pass_cnt, $max_repeat)

```
Правда есть  один нюанс - если из комбо будет выбран тот же файл, что там и был - эти два параметра тоже сбросятся, но элегантнее решения не нашел.

**Comment by jemxx** [comment]
Добавил.
