### ISSUE TITLE
Более логичный сбор элитной армии

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#47]
Вот этот функционал будет реализован, или это нужно только мне?

По пункту 2 поспешил, понадеявшись на логику автора - опять не совсем как нужно собирает элитную армию. Ивент закончился, постараюсь в ближайшие дни запостить сюда нужный порядок:  Осадники->КС->Броневики->Стрелки->Рыцари->КМ->Мечники 

UPD
Вот верный порядок при сборе остатков элитной армии

```
		If smena_armii($army_type) = 1 Then
			_imagesearch("media\mechnik.bmp", 1, $tx, $ty, 20)
			MouseClick("left", $tx + 83, $ty + 131, 1) ; мастера осады
			MouseClick("left", $tx + 332, $ty + 78, 1) ; конные стрелки
			MouseClick("left", $tx + 208, $ty + 78, 1) ; стрелки в броне
			MouseClick("left", $tx + 83, $ty + 78, 1)  ; стрелки
			MouseClick("left", $tx + 332, $ty + 24, 1) ; рыцари
			MouseClick("left", $tx + 208, $ty + 24, 1) ; конные мечники
			MouseClick("left", $tx + 83, $ty + 24, 1)  ; мечники
			Sleep(500 * $tormoza)
			Return okclose_elitnoy_gena(1)
		EndIf
```

_Originally posted by @Marsik-A in https://github.com/jemxx/autobot/issues/39#issuecomment-724211123_

**Comment by jemxx** [comment]
Как по мне, то совсем все равно в каком порядке оно собирает) Я то не вижу этого

**Comment by ghost** [comment]
На Майсетлерс был запрос - чтобы начинало собирать с более ценных войск (осадники, КС, броневики) к менее ценным (КМ, рыцари, мечники). Если вдруг вся арма не влезла, чтобы расходники шли своим ходом.
Именно так (возможно по чистой случайности канешн) организован сбор простой армы - от пушкарей до новиков.
Если этот функционал неактуален - закроем тему и не будем к ней возвращаться.

**Comment by jemxx** [comment]
В целом логика верная по сбору.  Добавить можно конечно же.

**Comment by jemxx** [comment]
Это уже готовый окончательный вариант? Добавлять его?

**Comment by ghost** [comment]
да
