### ISSUE TITLE
Рождественские спецы для будущего релиза 

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#48]
На тестовом уже выкатили рождество, есть новый Генерал Мороз и новый разведчик Снеговик.
Я могу их заскринить для будущего релиза, чтобы не добавлять потом отдельно.  Только пока неясно, как их локализаторы обзовут.

**Comment by jemxx** [comment]
Как угодно могут назвать) Можно пока назвать Мороз и Снеговик. Потом, если потребуется переименуем.

**Comment by ghost** [comment]
Генерал Frosty - это морозный, ледяной
Развед  Snowy - это снежный

[New_spec.zip](https://github.com/jemxx/autobot/files/5607511/New_spec.zip)

**Comment by jemxx** [comment]
Наверно подождем официальных названий. Торопится некуда.

**Comment by ghost** [comment]
Скорее всего, официальные будут за пару дней до запуска Рождественского события. Как-то стало традицией Дневники выкладывать почти накануне. 
Тогда и с релизом торопиться некуда.

**Comment by ghost** [comment]
Хотя вот Призрачного назвали же Призраком в конфиге. Почему бы и Фрости не назвать Морозом. Генерал Мороз очень по-российски)))

**Comment by jemxx** [comment]
Ну призрачный он и есть призрак) Коротко и ясно.  Мороз так Мороз.
