### ISSUE TITLE
Отправка группы генералов в прикл

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#5]
Придумать, как отправлять группу генералов в прикл, без учета количества имеющейся в них армы.
Примерный синтаксис ОтправитьГруппуВприключение=Нусала,Нусала,Борис,Малец,Малец,Малец
Отправит в прикл 2 Нусалы, Бориса и 3х младших.
Это команда сильно ускорит отправку большого числа генералов в прикл.

**Comment by ghost** [comment]
Пытался вчера прикрутить поэкранное (а не построчное как сейчас) листание по аналогии с листанием звезды - это уже бы ускорило отправку, Но в лоб не получилось. Скорее всего,налажал с определением где хранятся координаты окна отправки. Там аж 4 или 5 областей.

А про отправку пачкой думал так - передавать в функцию массив имен ген. А в функции завести еще такой же размерности массив с флагами-признаками отправили или нет. И тогда останется только в имеющуюся функцию поиска гены на экране добавить фор по числу ген в массиве. Если нашли нужного, то проверяем у него флаг - если уже взведен под отправку (флаг 1), то пропускаем, если не взведен - взводим. И на новую итерацию перебора. Как разобрать на имена параметры, вроде понятно - через сплит. А как получить количество для цикла?

Нашел как пересчитать число ген из команды. Так что можно пробовать

**Comment by jemxx** [comment]
UBound считает количество. Тот же StringSplit первый элемент содержит количество возвращённых строк. А вообще посмотрите пример в функции rungeolog

**Comment by ghost** [comment]
Да нашел уже  в помощи, спасибо.

**Comment by jemxx** [comment]
Как продвигается? У меня немного времени появилось, могу тоже поковыряться.

**Comment by ghost** [comment]
Пока никак, я ивент ковырял, и думу думал. Посмотрел я сорсы, там как-то очень криво сделано листание ген, построчно. Я попытался тупо воткнуть листание от звезды, но не прошло - не листает. Надо, скорее всего, переписывать. Если можно будет листать поэкранно - это прилично ускорит отправку. Ну а про группу, я жду, когда вернусь к нормальному интернету, и тогда можно будет уже более предметно ковырять.

**Comment by ghost** [comment]
Появилось свободное время, да и ивент будет ненапряжным, поэтому есть мысли как можно ускорить стандартную отправку ген в прикл.
Надеюсь, что в ближайшее время оформлю и проверю

**Comment by jemxx** [comment]
Я же делаю, медленно, но делаю) Времени пока нет. То школа сейчас начинается, то на работе завал небольшой

**Comment by ghost** [comment]
Вы группу делаете, как я понял, я хочу простую отправку ускорить) Которая имени и числу армии
Я посмотрел, там 4 поля поиска - первая строка по два гены слева и справа, и центральная строка два гены - слева и справа, и построчное листание. Поэтому все так долго, т.к. фактически кроме самой первой отправки ищет только в средней строке.
Я хочу сделать поиск сразу во всех 6ти полях - 1я строка право и лево, 2я и 3я право и лево, вчера значения для этого уже есть в коде, и листать поэкранно, а не построчно. 
И до кучи оптимизировать код - свернуть 4 однотипных ифа (разница только в ареа_поиске) до одного, но в цикле и со свичем - переключением ареа, тогда возможно будет проще в будущем интегрировать Вашу группу)

**Comment by ghost** [comment]
Я ускорил отправку и оптимизировал код, как и планировал: упаковал 4 однотипных иф-а в for и swich.
Теперь окно отправки пролистывается не на одну строку, а на две. Я подумал и решил не делать скролл на три строки, т.е. на целый экран. Во-первых, нижняя строка ген захватывается неполностью - нижний край обрезан, а во-вторых и в главных, мало ли глюканет скролл и привет(
Погоняю и выложу код, и на этом уже наверное совсем все, ну только спецов и в конфиг флажок для поиска приклов добавьте) Как раз будет символичный 20й релиз)

**Comment by ghost** [comment]
Вот погонял и выкладываю. 
Аналогично отправке разведов оптимизировал код на отправку ген через for и Switch

в юните globalwar.au3

```
; Новая функция отправки ген в прикл
Func otpravkagenvprikl($prikl, $gena, $shtuk, $imya)
	Local $tx = 0, $ty = 0, $i = 0, $generalov = 0, $ax = 0, $ay = 0, $search = 0, $error_otpravka = 0
	Local $for_i, $area_tmp_top_x, $area_tmp_top_y, $area_tmp_bottom_x, $area_tmp_bottom_y
	chatoff()
	drugioff()
	While 1
		If openotpravkagen($userDIR & $prikl) = 1 Then
			While ($generalov <> $shtuk) AND ($i < (read_ini(4) / 2))
				If haveimagearea("media\error_otpravka.bmp", 40, $area0_top_x, $area0_top_y, $area0_bottom_x, $area0_bottom_y) = 1 Then
					$error_otpravka = $error_otpravka + 1
					If $error_otpravka = 5 Then ExitLoop
				EndIf
				; цикл по области поиска генералов
				For $for_i = 1 To 4 Step 1
					; задаем площадь для поиска иконки гены
					Switch $for_i
						Case 1
							$area_tmp_top_x = $area1_top_x
							$area_tmp_top_y = $area1_top_y
							$area_tmp_bottom_x = $area1_bottom_x
							$area_tmp_bottom_y = $area1_bottom_y
						Case 2
							$area_tmp_top_x = $area2_top_x
							$area_tmp_top_y = $area2_top_y
							$area_tmp_bottom_x = $area2_bottom_x
							$area_tmp_bottom_y = $area2_bottom_y
						Case 3
							$area_tmp_top_x = $area3_top_x
							$area_tmp_top_y = $area3_top_y
							$area_tmp_bottom_x = $area3_bottom_x
							$area_tmp_bottom_y = $area3_bottom_y
						Case 4
							$area_tmp_top_x = $area4_top_x
							$area_tmp_top_y = $area4_top_y
							$area_tmp_bottom_x = $area4_bottom_x
							$area_tmp_bottom_y = $area4_bottom_y
					EndSwitch
					; ищем гену
					If _imagesearcharea($gena, 1, $area_tmp_top_x, $area_tmp_top_y, $area_tmp_bottom_x, $area_tmp_bottom_y, $tx, $ty, 20) = 1 Then
						If _imagesearcharea("media\Gena_plus.bmp", 1, $area_tmp_top_x, $area_tmp_top_y, $area_tmp_bottom_x, $area_tmp_bottom_y, $tx, $ty, 20) = 1 Then
							While _imagesearcharea("media\Gena_plus_yes.bmp", 1, $area_tmp_top_x, $area_tmp_top_y, $area_tmp_bottom_x, $area_tmp_bottom_y, $ax, $ay, 20) <> 1
								If haveimagearea("media\error_otpravka.bmp", 40, $area0_top_x, $area0_top_y, $area0_bottom_x, $area0_bottom_y) = 1 Then
									$error_otpravka = $error_otpravka + 1
									If $error_otpravka = 5 Then ExitLoop 3
								EndIf
								If $imya = "-" Then
									; листаем 1й раз отправку
									MouseMove($tx, $ty, 10 * $tormoza)
									Sleep(100 * $tormoza)
									MouseClick("left", $tx + Random(0, 2, 1), $ty + Random(0, 2, 1), 1)
									Sleep(100 * $tormoza)
									removemouse(300, 0, 300)
								Else
									If skolko_voisk_v_gene($imya, $area_tmp_top_x, $area_tmp_top_y, $area_tmp_bottom_x, $area_tmp_bottom_y) = 0 Then
										$generalov = $generalov - 1
										ExitLoop
									Else
										MouseMove($tx, $ty, 10 * $tormoza)
										Sleep(100 * $tormoza)
										MouseClick("left", $tx + Random(0, 2, 1), $ty + Random(0, 2, 1), 1)
										Sleep(100 * $tormoza)
										removemouse(300, 0, 300)
									EndIf
								EndIf
							WEnd
							go5()
							$generalov = $generalov + 1
							If $generalov = $shtuk Then ExitLoop 2
						EndIf
					EndIf
				Next
				$search = _imagesearcharea("media\otppravka_vniz.bmp", 1, 500, 100, @DesktopWidth - 200, @DesktopHeight, $tx, $ty, 90)
				MouseMove($tx, $ty, 10 * $tormoza)
				Sleep(100 * $tormoza)
				; листаем окно отправки 1й раз
				MouseClick("left", $tx + Random(0, 2, 1), $ty + Random(0, 2, 1), 1)
				Sleep(1000 * $tormoza)
				; листаем окно отправки 2й раз
				MouseClick("left", $tx + Random(0, 2, 1), $ty + Random(0, 2, 1), 1)
				Sleep(500 * $tormoza)
				removemouse(300, 0, 300)
				$i = $i + 1
			WEnd
			If $generalov = $shtuk Then
				zmemsmennuyukartinku("media\otpravka_ok.bmp", 30, "media\otpravka_ok_.bmp", 30)
				Return 1
			EndIf
			zmemsmennuyukartinku("media\closegena.bmp", 90, "media\closegena_.bmp", 90)
			$generalov = 0
			$error_otpravka = 0
			$i = 0
		EndIf
	WEnd
EndFunc

```

и еще вот в тоже юните в этой функции 
```
Func openotpravkagen($kartinka)
	WinActivate("The Settlers Онлайн")
	;writelog("=====ОТПРАВКА ГЕНЕРАЛОВ " & $kartinka & @CRLF)
	Local $search = 0, $i = 0, $tx = 0, $ty = 0
	If findclickoncenterandwaitresult($kartinka, "media\otpravit.bmp", 20, 50, 2, 5, 1, -300, -100) = 1 Then
		If findclickoncenterandwaitresult("media\otpravit.bmp", "media\otpravka_no.bmp", 50, 20, 2, 5, 1, 0, -100) = 1 Then
			Sleep(2000 * $tormoza)
			sleepwhile("media\otppravka_vniz.bmp", 100, 5)
			If _imagesearcharea("media\otpravka_no.bmp", 1, 500, 100, @DesktopWidth - 200, @DesktopHeight, $tx, $ty, 40) = 0 Then Return 0
			$area0_top_x = $tx - 305
			$area0_top_y = $ty - 144
			$area0_bottom_x = $tx - 46
			$area0_bottom_y = $ty - 80
			$area1_top_x = $tx - 305
			$area1_top_y = $ty - 316
			$area1_bottom_x = $tx - 46
			$area1_bottom_y = $ty - 228
			$area2_top_x = $tx - 46
			$area2_top_y = $ty - 305
			$area2_bottom_x = $tx + 216
			$area2_bottom_y = $ty - 228
			$area3_top_x = $tx - 305
			$area3_top_y = $ty - 228
			$area3_bottom_x = $tx - 46
			$area3_bottom_y = $ty - 144
			$area4_top_x = $tx - 46
			$area4_top_y = $ty - 228
			$area4_bottom_x = $tx + 216
			$area4_bottom_y = $ty - 144
			Return 1
		Else
			$search = 0
		EndIf
	EndIf
	Return 0
EndFunc

```

последние 4 строки где были area5, заменил на area0 и перенес в начало - area0 - это координаты всего окна отправки ген, но это как хотите. Я все-таки планирую попробовать искать сразу во всех трех строках - это сильно ускорит отправку, но пока боюсь - как бы не увеличило лаги. 
Если не менять - то значит в функции отправки ген заменить area0 на area5

**Comment by ghost** [comment]
> последние 4 строки где были area5, заменил на area0 и перенес в начало - area0 - это координаты всего окна отправки ген, но это как хотите. Я все-таки планирую попробовать искать сразу во всех трех строках - это сильно ускорит отправку, но пока боюсь - как бы не увеличило лаги.

Я попробовал сегодня искать морды ген во всех 6ти зонах, и окончательно отказался от этой идеи. В окне отправки гены нижняя область - две нижних морды ген попадают неполностью, самое паршивое, что "съедается" арма в гене, а значит отправка по количеству нитов будет отрабатываться некорректно.
