### ISSUE TITLE
Исправление недостатков команд "Набрать" и "ОтправитьДомой"

### ISSUE THREAD

**Issue by LEKALA** [jemxx/autobot#51]
После включения в код бота новых команд с умным листанием **ЖдемВсехГенералов** и **ЖдемГенерала** я столкнулся с очень серьёзными проблемами в работе текущих версий команд **Набрать** и **ОтправитьДомой**.
Для звезды на домашнем острове и экранов в ней более одного, проблема с командой **Набрать** выглядит так:
На видео исполняется следующий текст:

ЖдемВсехГенералов=Интендант,0
Набрать=Интендант,2,Э,0,0,0,0,0,1,0,1

https://c2n.me/4abbhN3.avi      
Это видеоролик 3.7МБ
Что мы видим? 
1. После успешного поиска интендантов бот настырно нажимает на вкладку "специалисты" и возвращает нас на первый экран звезды.
2. Бот снова начинает листать по две строки, пытаясь найти хотя бы одну картинку интенданта. Находит первого в правом углу нижней строки, но поскольку не видит второго интенданта, то вылетает с ошибкой.

Нажатие вкладки "специалисты" происходит из-за выполнения в кейсе **"Набрать"** файла **autobot.au3** вот этой строки:

`If selecttabatzvezda("specialisti", 0) = 1 Then`

Исправить очень легко. Надо заменить эту строку на следующую:

`If selecttabatzvezda("specialisti", 1) = 1 Then`

Т.е. заменить ноль на единицу для аргумента в скобках.
Ошибку с листанием можно исправить, если после успешного поиска картинки гены поднять её на экране до второй строки сверху (большое количество ген одного типа, более 11, будет полностью размещено в трёх нижних строках).
Для этого нужно в файле **globalfuncWAR.au3**, в функции **Func generali($general, $nomergenerala)** заменить кусок кода, ответственный за листание:
```
      Sleep(1000 * $tormoza)
	Local $ty = 0, $tx = 0, $search = 0, $i = 0, $t = 0, $ii = 0
	Local $general1x = 0, $general1y = 0, $general2x = 0, $general2y = 0

	;If _imagesearch($general, 1, $tx, $ty, 20) = 0 Then Return 0
	While 1
		If _imagesearcharea($general, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 30) = 1 Then ExitLoop

		$ii = $ii + 1
		zvezdamovepolzunokdown(0)
		zvezdamovepolzunokdown(0)

		Sleep(Random(500, 1000, 1) * $tormoza)
		If $ii > 5 Then
			If haveimagearea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 70, $zvezda_area[0] + 385, $zvezda_area[1] + 200, $zvezda_area[2] + 25, $zvezda_area[3] + 25) = 0 Then
				Return 1
			EndIf
		EndIf
	WEnd
```
На следующий:
```
Sleep(500 * $tormoza)
	Local $ty = 0, $tx = 0, $search = 0, $i = 0, $t = 0, $ii = 0, $count_list = 1, $count_line = 1, $count_gen_in_line = 9
	Local $general1x = 0, $general1y = 0, $general2x = 0, $general2y = 0
	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 4
	;Если на открывщемся экране нет гены, то нажимаем вкладку "специалисты", и если снова гены нет, то листаем по 1 строке
	;Листаем пока не найдём гену или до последнего экрана с генералами пока есть ползунок. Если не нашли гену, выходим с ошибкой.
	;Если нашли гену на экране в 4 строки, то поднимаем первую картинку гены во вторую строку сверху.
	While 1
		If (haveimageAREA($general, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) = 0) Then
			selecttabatzvezda("specialisti", 0)
			while (_imagesearcharea("media\zvezda_polzunok_ewe_mojno_vniz.bmp", 1, 300, 300, @DesktopWidth-200, @DesktopHeight, $tx, $ty, 45)) <> 0 AND ($ii < $count_list)
				If (haveimageAREA($general, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3] - 165) = 1) Then
					ExitLoop
				Else
					zvezdamovepolzunokdown(0)
					$ii = $ii + 1
				EndIf
			Wend
			If $ii >= $count_list Then 
				TrayTip("ОШИБКА", "Не нашли ни одного из выбранных ген!", 5)
				Return 0
			EndIf
		ElseIf _imagesearcharea($general, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 30) = 1 Then
			ExitLoop
		EndIf
	WEnd
```
Теперь выше приведённый текст выполняется вот так:
https://c2n.me/4abbnL7.avi
Это видеоролик 4.0МБ
Для случая без ожидания появления всех ген (если пользователь уверен, что все гены нужного типа находятся на домашнем острове и их можно сразу набирать);

Набрать=Интендант,2,Э,0,0,0,0,0,1,0,1

https://c2n.me/4abbr8M.avi
Это видеоролик 3.5МБ
Комментарии в новом куске кода можно удалить в случае включения в релиз, если они не нужны.

**Comment by LEKALA** [comment]
### **Теперь о недостатках команды "ОтправитьДомой".**
Проблемное поведение этой команды почти полностью идентично поведению команды **"Набрать"**, кроме одного мелкого отличия - функция не выдаёт ошибку, когда не видит гену с номером, отличным от 1, а вместо этого начинает заново бесконечно листать ген.
На видео исполняется аналогичный текст:

ЖдемВсехГенералов=Интендант,0
ОтправитьДомой=Интендант,2

https://c2n.me/4acUsDp.avi
Это видео 11.0МБ
Лечение также аналогично, но в данном случае все проблемы скрыты в функции **Func otpravitgenu($general, $nomergenerala)** файла **globalfuncWAR.au3**.
 Противоречащее логике нажимание вкладки "Специалисты" после успешного поиска (ожидания) ген связано с той же строкой:
`If selecttabatzvezda("specialisti", 0) = 1 Then`

которую надо заменить на строку с аргументом 1 в скобках:

`If selecttabatzvezda("specialisti", 1) = 1 Then`

Правильность листания до нужного нам генерала уже обеспечивается исправленной функцией **Func generali($general, $nomergenerala)** из файла **globalfuncWAR.au3**.
Однако, я лично несколько раз сталкивался с проблемой, вытекающей вот из этих двух строк в функции **Func otpravitgenu($general, $nomergenerala)**:
```
zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
```
Проблема заключается в том, что табличка подтверждения отправки **nubook.bmp** из-за глюков флэша не успевала вовремя появится (медленно выходила из фадинга), что не позволяло команде отработать правильно и бот просто зависал на этом месте без какой-либо ошибки. Чтобы исключить такую неприятность, предлагаю включить в код функции **Func otpravitgenu($general, $nomergenerala)** строку с ожиданием появления картинки **nubook.bmp**.
Выглядеть это должно вот так:
```
zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
sleepwhile("media\nubook.bmp", 30, 10)
zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
```
Я себе в своём релизе однозначно оставлю такую строку с ожиданием.
Редактировать код функции **Func otpravitgenu($general, $nomergenerala)**  в файле **globalfuncWAR.au3** можно и построчно (при условии, что функция **Func generali($general, $nomergenerala)** уже исправлена), но я предлагаю просто заменить код на следующий:
```
Func otpravitgenu($general, $nomergenerala)
	openzvezdap()
	While haveimage("media\zadacha_geni.bmp", 30) = 0
		If openzvezdap() = 1 Then
			If selecttabatzvezda("specialisti", 1) = 1 Then
				generali($general, $nomergenerala)
				Sleep(500 * $tormoza)
				sleepwhile("media\zadacha_geni.bmp", 30, 10)
			EndIf
		EndIf
	WEnd
	zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
	sleepwhile("media\nubook.bmp", 30, 10)
	zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
	Return 1
EndFunc
```
Теперь функция работает должным образом:
https://c2n.me/4acVwEL.avi
Это видео 2.0МБ.

На этом с функцией **Func otpravitgenu($general, $nomergenerala)** можно закончить, однако пока я разбирался с командой **Набрать**, то заметил в кейсе **"Набрать"** файла  **autobot.au3** кусок кода, содержащий две вышеописанных строки:
```
If $parametr[13] = 2 Then
	zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
	zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
EndIf
```
Поэтому предлагаю добавить строку с ожиданием картинки **nubook.bmp** и записать этот блок вот так:
```
If $parametr[13] = 2 Then
	zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
        sleepwhile("media\nubook.bmp", 30, 10)
	zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
EndIf
```

**Comment by LEKALA** [comment]
### **Еще один маленький, но очень важный нюанс.**
Копание в коде команды **Набрать** заставило меня рыться в коде всех функций, задействованных в работе, как самого кейса "Набрать", так и функций, вызываемых внутри исполняемых функций. И вот что я нашёл:
в коде функции **Func setarmy($kogo, $skolko, $gena)** где-то почти в середине присутствует вот такая строка:

`If findclickoncenterandwaitresult1("media\search_button_OK_enabled.bmp", "media\zdem.bmp", 30, 20, 3, 5, 1, -100, 1) = 1 Then`

Судя по всему, это строка обеспечивает ожидание появления картинки **search_button_OK_enabled.bmp** после ИСЧЕЗНОВЕНИЯ картинки **media\zdem.bmp**. Правильная работа этой строки, возможно,  должна была обеспечивать то, на отсутствие чего жаловались некоторые пользователи - "ранее, когда при наборе гены очень долго крутились часы, бот выжидал некоторое время, потом закрывал окно набора генерала и заново начинал поиск и набор... а теперь типа этого нет( часы крутятся, а бот ничего не делает...(("
Нюанс заключается в том, что в папке **media** отсутствует картинка **zdem.bmp**
Я нашёл у себя эту картинку в очень старых версиях бота (в папке army_values\)) Вот она:
https://c2n.me/4acYjIm.bmp
Эту картинку необходимо добавить в папку **media** и тестерам, которые часто и много ходят в приклы желательно бы проверить возобновление функционала функции **Func setarmy($kogo, $skolko, $gena)**, задуманного автором нашего бота.)
На этом пока считаю работу по устранению недостатков последнего релиза законченной)) И могу наконец-то приступить к созданию новых команд - **ЗапуститьФорпост, ЗапуститьОбсю, ЗапуститьПогоду)**. Буду очень стараться, чтобы успеть до публикации нового релиза.

**Comment by jemxx** [comment]
Добавил ваши изменения по командам Набрать и ОтправитьДомой. 

> И могу наконец-то приступить к созданию новых команд - ЗапуститьФорпост, ЗапуститьОбсю, ЗапуститьПогоду). Буду очень стараться, чтобы успеть до публикации нового релиза.

Это нужные команды, но к релизу наверное не успеете. Релиз будет в субботу потому как в понедельник уже ивент. Все изменения предложенные после четверга в ближайший релиз добавлены не будут. 
Только командам давайте нормальное название) ЗапуститьОбсю -> ЗапуститьОбсерваторию. Букв что ли жалко?))

**Comment by LEKALA** [comment]
Типа да)) Экономлю буквы)
Например в своём кругу в игре использую много сокращений) Так быстрее и проще печатать в чатах)
жеша - железная шахта
меша - медная шахта
плапла - плавилка платины
тимечи (тиша, платя - титановые исходники) - дамасские мечи))
плажа - плавилка железа...
Помните моё предложение назвать геншу Стойкую - Чикой?)) Это растёт из тех же корней, и на мой взгляд - сразу запоминаемо и ассоциируемо) Есть ещё один момент - латинские транскрипции русских прилагательных...
Стойкая = Stoikaya, а вот Чика = Chika...
я уже молчу про прилагательные во множественном числе... сейчас, как раз придумываю имена для картинок в форпостах и обсях)) и например пишу пока так: необходимые = neobhodimy, полезные = polezny... Согласитесь, что это юзабельнее, чем необходимые = neobhodimyie ?) Но в релиз буду предлагать именно ЗапуститьОбсеваторию.)

И плевать, что все проблемы из консерватории!))

Жаль, что до четверга не успею... Реал стал неимоверно плотным. Но я напишу! И пусть тогда лежит пока до следующего релиза. Код на форпост уже написал, тестирую... тестирую адекватный выход с ошибками... правлю по ходу.
Хотел спросить Вашего совета. Допустим форпост, запуск которого включён в текст, не готов к запуску (не истекло время ожидания рестарта), и пользователь должен иметь право выбора - указать в тексте флаг "игнорировать ошибку команды" и продолжить выполнение текста, или "принять ошибку" и остановить бота? На мой взгляд это осмысленно в отношении форпоста. А вот в отношении обси и погоды это скорее всего лишнее, поскольку не имеет смысла выполнять текст, который написан именно в расчёте на работу этих зонных бафов? Или таки оставить для пользователя опцию - "игнорировать ошибку команды" на всякий случай... на будущее... и вообще из соображений ценностей понятия - свобода?)

Добавлено
Да. и ещё момент! Я намерен включить функции запуска баф-будок в файл **globalfuncWAR.au3**, или это рациональнее включить в **globalfunc.au3**?

**Comment by jemxx** [comment]
> Допустим форпост, запуск которого включён в текст, не готов к запуску (не истекло время ожидания рестарта), и пользователь должен иметь право выбора - указать в тексте флаг "игнорировать ошибку команды" и продолжить выполнение текста, или "принять ошибку" и остановить бота? На мой взгляд это осмысленно в отношении форпоста. А вот в отношении обси и погоды это скорее всего лишнее, поскольку не имеет смысла выполнять текст, который написан именно в расчёте на работу этих зонных бафов?

Все правило, но поскольку ботом пользуются разные люди и кейсы использования у всех тоже разные желательно будет сделать опцию. 

Практически все команды находятся в globalfuncWAR.au3, но я бы добавил эти функции наверное в globalfunc.au3. Вообще нет разницы куда добавлять.
