### ISSUE TITLE
Песочные часы  и ошибка с набором армии

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#52]
Создал тему, но потом задумался - с одной стороны  LEKALA  прав - картинка zdem.bmp потерялась, и ее, безусловно,  надо вернуть в папку media. Но с другой - решит ли это проблему с неуспешным набором элитной армии, т.к. за это отвечает функция set_elitnoy_army и там тоже условие ожидания этой самой картинки "серого" новика, а для элитной армии этого события не произойдет никогда.
Я отсканил "серого" мечника, поправлю код и потестирую.  Возможно, так можно будет решить проблему с бесконечными песочными часами и ошибкой набора.

 
### **Еще один маленький, но очень важный нюанс.**
Копание в коде команды **Набрать** заставило меня рыться в коде всех функций, задействованных в работе, как самого кейса "Набрать", так и функций, вызываемых внутри исполняемых функций. И вот что я нашёл:
в коде функции **Func setarmy($kogo, $skolko, $gena)** где-то почти в середине присутствует вот такая строка:

`If findclickoncenterandwaitresult1("media\search_button_OK_enabled.bmp", "media\zdem.bmp", 30, 20, 3, 5, 1, -100, 1) = 1 Then`

Судя по всему, это строка обеспечивает ожидание появления картинки **search_button_OK_enabled.bmp** после ИСЧЕЗНОВЕНИЯ картинки **media\zdem.bmp**. Правильная работа этой строки, возможно,  должна была обеспечивать то, на отсутствие чего жаловались некоторые пользователи - "ранее, когда при наборе гены очень долго крутились часы, бот выжидал некоторое время, потом закрывал окно набора генерала и заново начинал поиск и набор... а теперь типа этого нет( часы крутятся, а бот ничего не делает...(("
Нюанс заключается в том, что в папке **media** отсутствует картинка **zdem.bmp**
Я нашёл у себя эту картинку в очень старых версиях бота (в папке army_values\)) Вот она:
https://c2n.me/4acYjIm.bmp
Эту картинку необходимо добавить в папку **media** и тестерам, которые часто и много ходят в приклы желательно бы проверить возобновление функционала функции **Func setarmy($kogo, $skolko, $gena)**, задуманного автором нашего бота.)
На этом пока считаю работу по устранению недостатков последнего релиза законченной)) И могу наконец-то приступить к созданию новых команд - **ЗапуститьФорпост, ЗапуститьОбсю, ЗапуститьПогоду)**. Буду очень стараться, чтобы успеть до публикации нового релиза.

_Originally posted by @LEKALA in https://github.com/jemxx/autobot/issues/51#issuecomment-744044028_

**Comment by ghost** [comment]
Пытался понять логику автора оригинального бота, но неасилил((
Вот функция setarmy 

Выделенная функция findclickoncenterandwaitresult1 вложена внутрь условия if $skolko = 3000, значит если набираем не технический максимум, она выполняться не будет. Значит за бесконечные песочные часы при нормальном наборе армии (поюнитно) отвечает не этот кусок текста.

```
Func setarmy($kogo, $skolko, $gena)
	Local $ty = 0, $tx = 0, $search = 0, $fullGenaImg = 0, $i = 0
	;writelog("| SA " & $kogo & "," & $skolko & "," & $gena & " | ")
	If $skolko = 0 Then
		;writelog("0" & @CRLF)
		Return 1
	EndIf
	$fullGenaImg = getFullGeneralImg($gena)
	If $skolko = 3000 Then
		viborarmii($kogo)
		$i = 0
		$search = 0
		While ($i < 10) AND ($search = 0)
			MouseMove($maxx, $maxy, 10 * $tormoza)
			MouseClick("left", $maxx, $maxy, 2)
			$search = _imagesearch($fullGenaImg, 1, $tx, $ty, 30)
			Sleep(500 * $tormoza)
			$i = $i + 1
		WEnd
		If $i < 9 Then
			$i = 0
			$search = 0
			Return 1
			If findclickoncenterandwaitresult1("media\search_button_OK_enabled.bmp", "media\zdem.bmp", 30, 20, 3, 5, 1, -100, 1) = 1 Then
				While ($i < 30 * $tormoza) AND ($search = 0)
					Sleep(500 * $tormoza)
					$i = $i + 1
					$search = _imagesearch("media\nub_gena.bmp", 1, $tx, $ty, 20)
				WEnd
				If $i < 20 Then
					Return 1
				EndIf
			Else
				TrayTip("", "Ошибка: Не нажали Ок", 0)
				Return 0
			EndIf
		Else
			TrayTip("", "Ошибка: Не набрали войска", 0)
			Return 0
		EndIf
	Else
		viborarmii($kogo)
		$skolkokartinka = "media\army_values\" & $diffarmy & ".bmp"
		While vvodzifr($skolko) <> 1
			MouseMove($minx, $miny, 10 * $tormoza)
			MouseClick("left", $minx, $miny, 2)
		WEnd
		Return 1
	EndIf
	Return 0
EndFunc
 
```

и дополню

```
			$i = 0
			$search = 0
			Return 1

```

Вот этот Return 1 не означает ли, что кусок кода за ним вообще никогда выполняться не будет.

**Comment by jemxx** [comment]
> Вот этот Return 1 не означает ли, что кусок кода за ним вообще никогда выполняться не будет.

Именно это он и означает. По какой то причине автор решил что все что ниже лишнее.

**Comment by jemxx** [comment]
Я тоже пытался разобраться с набором и забил на него. проще с нуля видимо написать.

**Comment by ghost** [comment]
> > Вот этот Return 1 не означает ли, что кусок кода за ним вообще никогда выполняться не будет.
> 
> Именно это он и означает. По какой то причине автор решил что все что ниже лишнее.

Т.е. правильно ли я понимаю, что оператор Return немедленно прекратит работу функции аналогично Exit-у, но с возможностью вернуть какое-то значение. 
И тогда получается, что наличие/отсутствие картинки zdem.bmp на выполнение кода никак не влияет. 
Я потихоньку чищу код от лишнего и не теряю надежды все же разобраться.

**Comment by Marsik-A** [comment]
Думаю, что задачу можно закрыть, т.к. это оказался тупиковый путь.

**Comment by ghost** [comment]
две функции 
`Func okclosegena($yes)` и `Func okclose_elitnoy_gena($yes)`

отвечают за окейность набора армы  в гену.

Там почему-то в обеих функциях в однотипных while-ах как минимум лишнее умножение на $tormoza,  как мне кажется 
`		While ($i < 6 * $tormoza) AND ($search = 0)
`

Убрал - проверю

**Comment by ghost** [comment]
Если моя догадка про ошибку с лишним умножением верна, то понятно зачем подобные while-ы - они отвечают за повторный набор, если зависли часы

> С набором армии тут вобще полная жопа. Не так давно пытался разобраться с проблемой, когда юнитов не хватает до набора и бот зацикливается. Вопрос пока не решил, точнее знаю как его решить, но дошел до момента 
> 
> ```
> While apply_elitnoy_army($parametr[3], $parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $full, 2) <> 1
> 						zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
> 						openGenaOnpxp($userDIR & $parametr[10], $parametr[11], $parametr[12], $parametr[13], $parametr[14], $parametr[15], $parametr[16])
> 					WEnd
> 
> ```
> 
> и задумался, а нафига везде в наборе нужен этот цикл? По факту в нем и проблема при наборе. Бот никогда не остановится, пока не наберет нужное количество. В идеале нужно сделать, что если бот не может набрать, то нужно останавливаться с ошибкой. Сейчас такого нет.

_Originally posted by @jemxx in https://github.com/jemxx/autobot/issues/39#issuecomment-720324852_ 
>

**Comment by jemxx** [comment]
> Т.е. правильно ли я понимаю, что оператор Return немедленно прекратит работу функции аналогично Exit-у, но с возможностью вернуть какое-то значение.

Именно так. 

> И тогда получается, что наличие/отсутствие картинки zdem.bmp на выполнение кода никак не влияет.

Получается так.

Я вспомнил, что я хотел сделать. Пытался разобраться с проблемой бесконечного набора войск если их не хватает. Хотел останавливать бота после некоторого количества попыток, но бросил это дело так ка это бы потребовало переписать все команды где есть набор. Возможно позже вернусь к этому.

**Comment by ghost** [comment]
Я переписал, но код не работал, поскольку закрытие гены обрабатывалось некорректно при значении параметра скорости < 1, т.к. по условию, что я привел выше i было почти всегда меньше 6ти, а значит набор считался успешным. Буду тестировать после моей поправки.

```
$ii = 0
While apply_elitnoy_army($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $full, $parametr[11]) <> 1
	zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
	openzvezdap()
	selecttabatzvezda("specialisti", 1)
	generali($gena, $parametr[2])
	$ii = $ii + 1
	if $ii > 5 Then Return 0
WEnd

``` 

Но проблему бесконечного набора при нехватке нужных бойцов эти правки не решают.

**Comment by ghost** [comment]
Случайно сейчас застал ситуацию, когда игра зависла на крутящихся песочных часах, бот выдал ТрайТипс, что войска не набраны, закрыл гену и набрал его по-новой. Речь о простой армии, но думаю, с элитной ситуация будет аналогичной

**Comment by jemxx** [comment]
Мистика какая то. И что по вашему на это повлияло?

**Comment by ghost** [comment]
я же написал что, в проверке 
` While ($i < 6 * $tormoza) AND ($search = 0) `
лишнее умножение на $tormoza. Если не менять скорость прохода, т.е. $tormoza = 1, то все работает как задумано, но если $tormoza < 1, то дальше идет условие `If $i < 6 Then`, а значит оно никогда не выполнится, и часть кода, которая обрабатывает затянувшиеся часы, не сработает.
 

> две функции
> `Func okclosegena($yes)` и `Func okclose_elitnoy_gena($yes)`
> 
> отвечают за окейность набора армы в гену.
> 
> Там почему-то в обеих функциях в однотипных while-ах как минимум лишнее умножение на $tormoza, как мне кажется
> ` While ($i < 6 * $tormoza) AND ($search = 0) `
> 
> Убрал - проверю

А вот этот весь кусок он просто лишний
 ```
If findclickoncenterandwaitresult1("media\search_button_OK_enabled.bmp", "media\zdem.bmp", 30, 20, 3, 5, 1, -100, 1) = 1 Then
 	While ($i < 30) AND ($search = 0)
 		Sleep(500 * $tormoza)
 		$i = $i + 1
 		$search = _imagesearch("media\nub_gena.bmp", 1, $tx, $ty, 20)
 	WEnd
 	If $i < 20 Then
 		Return 1
 	EndIf
 Else
 	TrayTip("", "Ошибка: Не нажали Ок", 0)
 	Return 0
 EndIf

```
т.к. стоит после Return 1 и никогда до него очередь не дойдет

**Comment by jemxx** [comment]
> А вот этот весь кусок он просто лишний

Он не то что бы лишний, просто по какой то причине обрублен. Предполагаю, что дело в том, что судя по картинке nub_gena этот код связан с простыми солдатами и автору видимо было лень писать код для элиток он просто рубанул его.

**Comment by ghost** [comment]
> Он не то что бы лишний, просто по какой то причине обрублен. Предполагаю, что дело в том, что судя по картинке nub_gena этот код связан с простыми солдатами и автору видимо было лень писать код для элиток он просто рубанул его.

лишний именно в том месте. Не знаю, но у меня если с 1го раза мазанул мимо фуллюнитов (параметр 3000), то со 2го обычно все гуд.  
Для элитки код тоже как бы есть - слово в слово такой же с ожиданием серого нуба. Видимо была какая-то задумка, но потом она "передумалась"

Вот в этих двух строках надо, как минимум, убрать умножение на параметр скорости
https://github.com/jemxx/autobot/blob/c380ba94bed298afee05777f16d04a767bfe27a3/globalfuncWAR.au3#L1265
и
https://github.com/jemxx/autobot/blob/c380ba94bed298afee05777f16d04a767bfe27a3/globalfuncWAR.au3#L2357

и оставить  просто
`While ($i < 6) AND ($search = 0) `

**Comment by ghost** [comment]
> Я вспомнил, что я хотел сделать. Пытался разобраться с проблемой бесконечного набора войск если их не хватает. Хотел останавливать бота после некоторого количества попыток, но бросил это дело так ка это бы потребовало переписать все команды где есть набор. Возможно позже вернусь к этому.

В юните globalWAR.au3 есть функция, отвечающая за ввод цифр в окошки набора юнитов - `vvodzifr()`
В случае успешного набора она вернет 1, неуспешного - 0. Неуспешных вариантов у нее два - когда в нее передается или пустая строка или недопустимый символ.
Вот в ней и надо еще обрабатывать вариант с неуспешным набором в случае нехватки юнитов. Вчера придумал, но попробовать не успел, т.к. техи(
Если до вечера починят, и что-то нарою - запощу сюда, может успете в релиз добавить.

**Comment by ghost** [comment]
и вот еще, не стал плодить задачи

Начиная вот с этой строки
https://github.com/jemxx/autobot/blob/c380ba94bed298afee05777f16d04a767bfe27a3/globalfuncWAR.au3#L1233

весь кусок кода лишний. Он остался от функционала отката версии, который Вы частично  убрали.
```
	Else
		$i = $i + 5
		MouseMove($polezifrx, $polezifry, 10 * $tormoza)
		MouseClick("left", $polezifrx, $polezifry, 2)
		Sleep(300 * $tormoza)
		Send($skolko)
		Sleep(1000 * $tormoza)
		While (haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) <> 1) AND ($i > 0)
			MouseMove($strelkax, $strelkay, 10 * $tormoza)
			MouseClick("left", $strelkax, $strelkay, 1)
			Sleep(2000 * $tormoza)
			MouseMove($strelkax, $strelkay - 15, 1 * $tormoza)
			MouseClick("left", $strelkax, $strelkay - 15, 1)
			$i = $i - 1
		WEnd
		If haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) = 1 Then
			Return 1
		EndIf
```

Вот, судите сами

Исходный кусок кода
```
	$i = 0
	$error = 0
 	If read_ini(5) = 1 Then
 		While StringInStr($skolko, "0") <> 0
 			$skolko = $skolko - 1
 			$i = $i + 1
 		WEnd
 	EndIf
	If $i = 0 Then
		MouseMove($polezifrx, $polezifry, 10 * $tormoza)
		MouseClick("left", $polezifrx, $polezifry, 2)
		Sleep(300 * $tormoza)
		Send($skolko)
		Sleep(1000 * $tormoza)
		If haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) = 1 Then
			Return 1
		EndIf
	Else
		$i = $i + 5
		MouseMove($polezifrx, $polezifry, 10 * $tormoza)
		MouseClick("left", $polezifrx, $polezifry, 2)
		Sleep(300 * $tormoza)
		Send($skolko)
		Sleep(1000 * $tormoza)
		While (haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) <> 1) AND ($i > 0)
			MouseMove($strelkax, $strelkay, 10 * $tormoza)
			MouseClick("left", $strelkax, $strelkay, 1)
			Sleep(2000 * $tormoza)
			MouseMove($strelkax, $strelkay - 15, 1 * $tormoza)
			MouseClick("left", $strelkax, $strelkay - 15, 1)
			$i = $i - 1
		WEnd
		If haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) = 1 Then
			Return 1
		EndIf
	EndIf

```

5й параметр в ини отвечал за альтернативный ввод цифр. В новой версии условие `If read_ini(5) = 1 Then` никогда не выполнится, а значит счетчик $i **никогда на нарастится**. И, следовательно, альтернативная ветка в условии `If $i = 0 ... Else  ` никогда не выполнится. 

Upd. Код я подправил, как только запустят игру - проверю и выложу, если все ok.

**Comment by jemxx** [comment]
Там еще глубже проблема. Я был на этом шаге. Она вернет 1 или 0 в While а цикл будет крутится пока не придет 1 из этой функции. Вот и получаем зацикленный набор. 

```
While vvodzifr($skolko) <> 1
			MouseMove($minx, $miny, 10 * $tormoza)
			MouseClick("left", $minx, $miny, 2)
		WEnd
		Return 1

**Comment by jemxx** [comment]
А затем если идти дальше и взять любую команду с набором войск приходим к примерно такому коду

```
While apply_elitnoy_army($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $full, $parametr[11]) <> 1
								zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
								openzvezdap()
								selecttabatzvezda("specialisti", 1)
								generali($gena, $parametr[2])
							WEnd
```

И тут уже вопрос, а нафига во всех наборах нужен while??

Короче все это циклит набор и тут я остановился.

**Comment by ghost** [comment]
Я уже сделал код, но его надо проверить. Вот смотрите

```
Func vvodzifr($skolko)
	If naborgenarea() = 0 Then Return 0
	If $skolko = "" Then
		MsgBox(0, "ОШИБКА", "Количество армии пустое")
		Return 0
	EndIf
	Local $i = 0, $error = 0, $symbol
	While $i < StringLen($skolko)
		$symbol = StringMid($skolko, $i + 1, 1)
		If StringInStr("0123456789", $symbol) <> 0 Then
			$error = $error + 1
		EndIf
		$i = $i + 1
	WEnd
	If $error <> StringLen($skolko) Then
		MsgBox(0, "ОШИБКА", "Недопустимые символы в количестве войск")
		Return 0
	EndIf
	$i = 0
	While ($i < 5)
		MouseMove($polezifrx, $polezifry, 10 * $tormoza)
		MouseClick("left", $polezifrx, $polezifry, 2)
		Sleep(300 * $tormoza)
		Send($skolko)
		Sleep(1000 * $tormoza)
		If haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) = 1 Then
			Return 1
		EndIf
		$i = $i + 1
	WEnd
	MsgBox(0, "ОШИБКА", "Недостаточно юнитов для набора")
	Return 0
EndFunc
```

Бот попытается ввести цифры 6 раз, и если попытка будет успешной, то он вернет 1 по вот этому условию
```
If haveimagearea($skolkokartinka, 20, $zifri_area[0], $zifri_area[1], $zifri_area[2], $zifri_area[3]) = 1 Then
			Return 1
		EndIf

```

А если ему этого не удастся сделать, то он дойдет до конца и вернет 0. И этот 0 уже можно обрабатывать будет дальше

**Comment by ghost** [comment]
> А затем если идти дальше и взять любую команду с набором войск приходим к примерно такому коду
> 
> ```
> While apply_elitnoy_army($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $full, $parametr[11]) <> 1
> 								zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
> 								openzvezdap()
> 								selecttabatzvezda("specialisti", 1)
> 								generali($gena, $parametr[2])
> 							WEnd
> ```
> 
> И тут уже вопрос, а нафига во всех наборах нужен while??
> 
> Короче все это циклит набор и тут я остановился.

эти куски я же расциклил, о чем и писал Вам выше. во всех подобных случаях поставил счетчики 

> 
> Я переписал, но код не работал, поскольку закрытие гены обрабатывалось некорректно при значении параметра скорости < 1, т.к. по условию, что я привел выше i было почти всегда меньше 6ти, а значит набор считался успешным. Буду тестировать после моей поправки.
> 
> $ii = 0
> While apply_elitnoy_army($parametr[4], $parametr[5], $parametr[6], $parametr[7], $parametr[8], $parametr[9], $parametr[10], $full, $parametr[11]) <> 1
> 	zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
> 	openzvezdap()
> 	selecttabatzvezda("specialisti", 1)
> 	generali($gena, $parametr[2])
> 	$ii = $ii + 1
> 	if $ii > 5 Then Return 0
> WEnd
> 
> Но проблему бесконечного набора при нехватке нужных бойцов эти правки не решают.

Но вот теперь есть решение и с нехваткой войск, надо только потом ко коду еще корректно обработать упомянутый While

Upd. Кстати, этот код решит проблему зацикливания не только если войск мало, но и наоборот - если пользователь ошибся в расчетах, и хочет впихнуть невпихуемое, т.е.  загрузить в гену юнитов больше, чем гена вмещает.

**Comment by ghost** [comment]
Вот кусок, который меняем в двух местах в setarmy() и set_elitnoy_army()

```
$i = 0		
While vvodzifr($skolko) <> 1
	;writelog("+" & $skolko)
	MouseMove($minx, $miny, 10 * $tormoza)
	MouseClick("left", $minx, $miny, 2)
	$i = $i + 1
        if $i > 5 Then Return 0			
WEnd

```

Это все проверяется по 1 минуте на каждый тип армы, если все сработает, я выложу подчищенные коды для setarmy() и set_elitnoy_army() без лишних кусков и обнулений разных счетчиков, чтобы потомки были нам потом благодарны))
Все-таки продираться через все костыли, которые подпирают код со всех сторон ппц как тяжело(
