### ISSUE TITLE
Баг при листании генералов

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#55]
Не знаю, может никому кроме меня неактуально, но я часто играю сам, пока бот проходит и прерываюсь на какие-то сообщения в личку, пока гены едут например ,или переезжают.
И часто забываю свернуть обратно чат. И тогда при поиске ген листаться начинает чат, а не звезда.
Если в этих строках 

https://github.com/jemxx/autobot/blob/c380ba94bed298afee05777f16d04a767bfe27a3/globalfunc.au3#L486

https://github.com/jemxx/autobot/blob/c380ba94bed298afee05777f16d04a767bfe27a3/globalfunc.au3#L475

(и во всех подобных случаях в функциях LEKALA) заменить область поиска со всего экрана 

`300, 300, @DesktopWidth-200, @DesktopHeight`

на окно звезды 

`$zvezda_area[0] + 385, $zvezda_area[1] + 200, $zvezda_area[2] + 25, $zvezda_area[3] + 25`

- этой "ошибки" не будет

**Comment by jemxx** [comment]
Тоже заметил такое поведение, но не придал значения. А оно вот в чем дело.

**Comment by ghost** [comment]
ну по коду посмотрите, ползунок ищется по всему экрану, а нафига? если листается звезда? тем более что при отправке разведов и геологов этот функционал - искать в области звезды - реализован. 
Прямо доктор Джекилл и мистер Хайд какие-то)) то толковый код, а то как у первоклассника
