### ISSUE TITLE
Поправленный сбор коллекций

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#57]
Поскольку Сиррис обновил подсветку, выложу подправленный сбор коллекций.

в юните globalfunc.au3 меняем функцию сбора коллекций на следующую

```
Func collectwarikiatprikl($gde)
	Local $ciklov = 0
	;TrayTip("", "Собираем шарики ... ", 0)
	Local $hWnd
	Opt("WinTitleMatchMode",2)
	$hWnd = WinWait($WinTitle)
 	WinActivate($hWnd)
;	WinActivate("The Settlers Онлайн")
	;Return 1
	While (haveimage("media\warik.bmp", 50) = 1) AND ($ciklov < 50)
		If $gde = 0 Then
			findclickoncenterandwaitresult("media\warik.bmp", "media\warik_label_collected_doma.bmp", 50, 10, 2, 10, 0, 50, 50)
		Else
			findclickoncenterandwaitresult("media\warik.bmp", "media\warik_label_collected_prikl.bmp", 50, 10, 2, 10, 0, 50, 50)
		EndIf
		Sleep(3000 * $tormoza)
		$ciklov = $ciklov + 1
	WEnd
EndFunc

``` 
У функции появился параметр $gde, задает место сбора - дома (0) или в прикле (любое другое значение).  Зачем это надо? в разных локациях разное сплеш-сообщение, появление которого ждет бот - за сообщения отвечают картинки warik_label_collected_doma.bmp и warik_label_collected_prikl.bmp. 

В юните globalfuncWAR.au3 ищем вхождения функции collectwarikiatprikl() и меняем на collectwarikiatprikl(1) для прикла, я нашел в двух местах Func podgotovka() и в gotopriclanosleep($kartinka). Но во втором случае это лишнее, я у себя закмоентал.

В основном юните autobot.au3 в обработке команды СборКоллекций меняем collectwarikiatprikl() на collectwarikiatprikl(0)

Ну и главное - под себя надо настроить сплошной цвет пузырька подсветки - я выбрал Magenta, заскринить кусочек и спасти под именем warik.bmp. С дефолтной градиентной подсветкой работает плохо. И если когда-то заработает pinki подсветка, то ничего уже менять будет не надо. 
Все нужные картинки в архиве.
[items.zip](https://github.com/jemxx/autobot/files/5726836/items.zip)

  
Не панацея, но что-то на домашнем острове да собирает,

**Comment by jemxx** [comment]
Может лучше файл warik.bmp поместить в media\users ? Так более логично ведь эту картинку можно менять под себя.

**Comment by jemxx** [comment]
Хотя, это излишне. Пусть остается все как есть.

**Comment by ghost** [comment]
я сильно рекомендую сплошной цвет маджента, если вдруг починят пинки.

**Comment by jemxx** [comment]
А у вас тоже медленно собирает?

**Comment by ghost** [comment]
дома? да, и далеко не все ,к сожалению. Так что это не 100% панацея

**Comment by jemxx** [comment]
Тоже медленно и не все. Для дома быстрее руками конечно же)

**Comment by ghost** [comment]
> Тоже медленно и не все. Для дома быстрее руками конечно же)

Ну я воткнул к утренней отправке разведов, пока завтрак-кофе, что-то собрал. Лучше у твинов, где застройка не такая плотная
