### ISSUE TITLE
ВАЖНО!!! Ошибки релиза 0.22

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#58]
Исправлено!

~~Ошибка так и осталась - и вводит в заблуждение пользователей!!~~

> и в файле _chagelog.tmp когда-то мной была допущена ошибка, так и осталась - убрать слово "генералов"
> 
> v.0.18 (09.08.2020)
> ВАЖНО!!! начиная с этой версии
> Все рабочие картинки находятся в папке media, значения для набора армы (0-3000) в папке media\army_values. Все пользовательские картинки (скрины генералов, приклов и точек привязки) помещать в папку media\users

**Comment by ghost** [comment]
Исправлено!

"batonСегодня, в 22:39
~~набрал в ini в последней версии speed=0.4 бот не реагирует. похоже в последней версии сломали ускорялку. разведов теперь отправлеяет чуть ли не по 10 мин
пока вернулся на версию 0.20"~~

Я предполагаю, что у пользователя стоит региональный разделитель запятая, а функция readINI не умеет распознавать региональный настройки, и не может распознать как число такую строку.
Я с таким уже сталкивался в других средах. Надо принудительно менять "," на "." при чтении из ини и по флагу Скорость. 

Upd. Да так и есть, разделитель запятая, пишет что без возможности смены https://clip2net.com/s/4akHjy1

**Comment by jemxx** [comment]
С ini есть ряд проблема которые на тесте не были отловлены. Некоторые проблемы исправил, чуть позже выгружу исправления. Возможно это решит и вашу проблему.

**Comment by jemxx** [comment]
В файле то я и не поменял. Зато в релизах изменил. Вообще я думаю, что _chagelog.tmp лишний и наверное стоит его убрать, ведь все сделанные изменения публикуются в релизах

**Comment by ghost** [comment]
Ну или убрать тогда его совсем, т.к. там есть вводящая в заблуждение информация. Это по ченжлогу. Но далеко не все качают релизы с гитхаба, а значит не видят изменений.

А по запятой, проблема не моя, но предполагаю, что она будет у многих. У меня во всех системах всегда стоит точка, т.к. я этот прикол знаю. И когда кодил прогу для одного прибора на продажу, с этим тоже столкнулся, и принудительно менял запятую на точку для своих внутренних расчетов. Поэтому так быстро и удалось отловить проблему.

Ну и еще раз прошу проверить проблему с потерей фокуса у бота для exe-клиента.  
Я ее описывал тут https://github.com/jemxx/autobot/issues/31#issuecomment-748460378_

**Comment by jemxx** [comment]
> Но далеко не все качают релизы с гитхаба, а значит не видят изменений.

А должны качать с гитхаба. Это и безопасней и для общего развития полезно)

> А по запятой, проблема не моя, но предполагаю, что она будет у многих.

Ну посмотрим как оно будет после исправления. Чуть позже выгружу на гитхаб

**Comment by ghost** [comment]
> А должны качать с гитхаба. Это и безопасней и для общего развития полезно)

Ну как вариант перестаньте выкладывать в облако мейл-ру)))) Посмотрим, чем закончится эта идея)

И чтобы не множить темы, я тут думал еще вот о чем:
сейчас процесс отладки скриптов для бота очень неудобный, если чекнуть "Выводить предупреждения", то очень скоро это начинает подбешивать, что каждая команда требует нажатия ОК, и выключаешь все.
А как Вам идея вместо меседжбокса выводить эту же инфу в так ненавистные вам ТрайТипы? Из плюсов я вижу следующие:
- проход не прерывается
- если записывать видео первого прохода, всегда можно увидеть, где будет затык
- и опять же по видео можно потом оптимизировать и сам проход и тайминги ожидания.

Руки  пока не дошли, но мне эта идея кажется вполне неплохой. Не думаю, что это потребует сильного изменения кода.

Upd. 
Сделал, в юните autoit.au3, в функции printerror($text)
заменить строку 
`	MsgBox(0, "!!!", $text)
`	

на строку 
` TrayTip("", $text, 2, 1)
`
2 -  это время отображения в секундах, 1 - иконка "информация". Как убрать противный звук - не нашел(

**Comment by jemxx** [comment]
Добавлю до кучи. Обратил внимание что не отрабатывает флаг 1 в команде Набрать=Бородотряс,1,Э,0,0,0,0,0,0,0,0,0,1 в прикле. На дом острове не знаю. Причем такое поведение было и на прошлой версии.

**Comment by ghost** [comment]
Не знаю - проверю при случае, я Бороду не разгружаю

**Comment by jemxx** [comment]
Ну до бороды у меня там варгус был и проблема аналогичная.

**Comment by jemxx** [comment]
> А как Вам идея вместо меседжбокса выводить эту же инфу в так ненавистные вам ТрайТипы?

Почему бы и нет. Возникла идея модернизировать команду Сообщение добавив флаг 1 сообщение в MsgBox, а флаг 2 сообщение в TrayTip. Думаю полезно будет

**Comment by ghost** [comment]
> Ну до бороды у меня там варгус был и проблема аналогичная.

Плохо что проблема вариабельная(

**Comment by jemxx** [comment]
> А по запятой, проблема не моя, но предполагаю, что она будет у многих.

Скомпилировал с новыми изменениями, пусть проверят проблему эту

**Comment by ghost** [comment]
Написал в дискорде про новый релиз, ждем

**Comment by Marsik-A** [comment]
> > А по запятой, проблема не моя, но предполагаю, что она будет у многих.
> 
> Скомпилировал с новыми изменениями, пусть проверят проблему эту

Проблема не по запятой, а по невидению папки с прохождениями осталась. Не видит папку + вчера забыл рассказать, у него еще и в ини стоит число повторов 1, а бот упорно где-то берет 99. В дискорде есть видео, где все это показано.

**Comment by ghost** [comment]
проблема с невидением папок решилась просто - почему-то сбилась кодировка в ини файле.
Вернул в ЮТФ8 без БОМ и все решилось. 
Кодировку меняет стандартный виндовый Блокнот.

**Comment by ReReAleks** [comment]
Добрый день, не работают команды ЖдемГенерала И ЖдемВсехГенералов ни когда они серые ни когда они уже приехали на остров, бот кликает два раза мышкой на вкладку с генами и выскакивает ошибка

https://user-images.githubusercontent.com/76568527/103102929-81cc7700-462f-11eb-99dd-5782ddf3bc2a.mp4

https://user-images.githubusercontent.com/76568527/103103105-6ada5480-4630-11eb-9fda-eb04531d256d.mp4


Отправляет и воюет просто замечательно!

**Comment by jemxx** [comment]
Это очень странно. Дело то в том, что я и сам хожу в приключения и много где использую эту команду, но такой проблемы нет. Версия Автобота сегодняшняя у вас? Покажите, что у вас в autobot.ini написано.

**Comment by ReReAleks** [comment]
> Это очень странно. Дело то в том, что я и сам хожу в приключения и много где использую эту команду, но такой проблемы нет. Версия Автобота сегодняшняя у вас? Покажите, что у вас в autobot.ini написано.

`[main]
;Графика_сектора
sector_graphics=70
;Графика_имени_генерала
general_name_graphics=100
;Текстовик по-умолчанию
favorite_file=1 разбойник
;Всего_генералов
total_generals=50
;Cкорость
speed=1
;ПроверкаСвязи
check_connection=0
;Папка_для_прохождений
passages_folder=FFF
;Повторять_текстовик
total_cycles=1
;Название_окна
window_title=TSO Game Client


[telegram]
;Включение отправки сообщений в телеграм 0 не шлем 1 шлем
telegram_bot=0
;Токен бота
telegram_bot_token=
;ID чата
telegram_chat_id=`

**Comment by jemxx** [comment]
А чем редактируете данный файл?

**Comment by jemxx** [comment]
Автобот сегодня качали? Я там делали некоторые исправления связанные с этим файлом.

**Comment by ReReAleks** [comment]
> Автобот сегодня качали? Я там делали некоторые исправления связанные с этим файлом.

сегодня, с мейла, про utf и кириллицу в курсе, у приклов тоже кодировку проверил
пример ожидания варгуса на острове, картинки все заменил и активного и серого, клиент сириса


https://user-images.githubusercontent.com/76568527/103107129-7fc4e100-464c-11eb-9b37-659b6b3f95ae.mp4

**Comment by jemxx** [comment]
Завтра по разбираюсь в чем может быть дело.

**Comment by ReReAleks** [comment]
Снял с чистым свежескачанным клиентом https://yadi.sk/d/lBTG5jACbDBqjw

**Comment by jemxx** [comment]
Проблема определенно есть и проявляется она судя по всему по разному. Опытным путем установлено, что у меня данная команда прекрасно ждет генералов которые расположены на первых 3-х строчках, а если ниже, то не видит их.

Далее. Проведя исследование проблемы установил, что проблема возникает вот в этой строчке
```
$count_list = int(ReadINI("main", "total_generals", "50")/($count_line * $count_gen_in_line))
```
Ее комментирую и начинает видеть всех генералов. 

Что бы развеять все сомнения относительно чтения параметра из файла такая замена 

```
$count_list = int(50/($count_line * $count_gen_in_line))
```
проблему ни как не исправляет.

**Comment by ghost** [comment]
А какое значение в count_list? И зачем брать его целую часть? Там же не for цикл, а while со строгим условием. Может int отрабатывает некорректно.
Скорее всего count_list = 0, и сразу срабатывает этот блок, и в цикл while ни разу не заходит.
```
$i = 1
While ($i < $count_list)

```
И причем тут 3 строчки? На экран звезды помещается 4 полных строки + половина 5й. 
Вот этот код ищет в пределах всей звезды, а не в первых трех строках! т.е. во всех 4,5 строках - если отскринить только верхушки ген.

`haveimageAREA($image_NA, 20, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3]) 	
`					`					

Координаты области звезды определяются вот этой строкой 
`Global $Zvezda_area[4] = [$tx - 520, $ty, $tx, $ty + 340]` 
в функции openzvezdaP() юнита globalfunc.au3

$ty, $tx - это координаты значка лупы (картинка zvezda_is_displayed.bmp) в верхнем правом углу. 520 и 340 это размер области инвентаря в звезде.

Т.е. если гена есть на первом экране, который виден сразу при открытии звезды, что нам и показал ReReAleks - бот должен его увидеть.  

Три верхних строки взялись вот откуда - когда я писал свою версию команд ожидания, я руководствовался тем, что если гена "прибавится" или "убавится" за счет задержек при переходах между зонами, то листаем звезду на три строки вниз построчно с тем, чтобы был запас в одну строку на случай прыжков. Но далеко не все умеют читать код и думать, поэтому просто бездумно это все переписали.

Upd
Прикольно, у меня тоже стоит int, но при этом все листает же
`	$count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 1`

Upd2.
Ну и в порядке бреда - Jemxx - а у Вас какой разделитель целой и дробной частей в системе? Запятая?

**Comment by jemxx** [comment]
> Upd2.
Ну и в порядке бреда - Jemxx - а у Вас какой разделитель целой и дробной частей в системе? Запятая?

Вообще запятая. Я так понял она у всех по умолчанию стоит и мало кто ее меняет.

> А какое значение в count_list? И зачем брать его целую часть? Там же не for цикл, а while со строгим условием. Может int отрабатывает некорректно.

Я не смотрел, что в count_list, надо будет глянуть. Может тут лучше сделать деление без остатка или округлять. Хотя int делает ровно тоже самое. Отсекает дробную часть.

> Скорее всего count_list = 0, и сразу срабатывает этот блок, и в цикл while ни разу не заходит.

Может он конечно и ноль, вечером проверю, но почему на первых -строках он не ноль. Вот это большой вопрос. Вообще тогда тут с логикой проблемы. Если генералов мало указано в autobot.ini, то почти всегда он будет 0. Если генералов меньше чем 9 * на 3 строки, то будет 0. Поэтому нужно округлять в большую сторону, а не отсекать дробную часть

**Comment by ghost** [comment]
Ну что с логикой проблемы - это очевидно, и я не знаю зачем Вы повелись на этот бред кодирования с кейсами непонятными условиями!!!! 
С запятой тоже не все очевидно, я скачал этот релиз и проверил у себя, у меня-то точка стоят. Клауса на 5м экране эта версия тоже не нашла.
Не надо там ничего округлять - это будут лишние листания. Зачем нужен каунт_лист - чтобы узнать, сколько раз листать звезду, так? Счетчик листаний = 3 строки (почему три а не 4? ведь видимых строк именно 4, и 5я частично, а мордочки ген ищутся по всей звезде) * 9 иконок генерала = 27. 50 делим на 27 =1.85. Команда int должна отбросить дробную часть, т.е. каунт_лист = 1.
Смотрим код! это гениально в своей тупости
итак каунт_лист равен 1, так?

Смотрим код
```
$i = 1
While ($i < $count_list)
```

Как Вы думаете, вот в этот Вайл зайдет бот когда-нить?? И после этого Вы еще планируете включать в релизы логику этого недоучки??

**Comment by ghost** [comment]
> Может он конечно и ноль, вечером проверю, но почему на первых -строках он не ноль. Вот это большой вопрос. Вообще тогда тут с логикой проблемы. Если генералов мало указано в autobot.ini, то почти всегда он будет 0. Если генералов меньше чем 9 * на 3 строки, то будет 0. Поэтому нужно округлять в большую сторону, а не отсекать дробную часть

Если генералов меньше 50, т.е. эначит что листать звезду **НЕ нужно**, все генералы будут  на первом экране, там и только там - т.е. сразу должны увидеться при открытии звезды! Вот такая логика  у здорового программиста.

**Comment by ghost** [comment]
Я могу быть миллион раз напыщенным индюком и ублюдком, но ошибку нашел я, а не автор этих чудных команд. 
Но написать я хотел не это - при количестве генералов, равным 100, этот чудо-код тоже не работает. Если моих слов недостаточно, я готов предоставить видеодоказательства этого.

**Comment by ghost** [comment]
_**Достает попкорн**_

```
$count_list = int(ReadINI("main", "total_generals", "50")/($count_line * $count_gen_in_line)) - 4
```
Поясните эту логику в функции generali тут отнимается 4 но сюда еще нужно плюсануть 27

_Originally posted by @jemxx in https://github.com/jemxx/autobot/issues/59#issuecomment-751382914_

50 делим на 3 *9 = 1.85, берем целую часть от 1.85 = 1, отнимаем 4 - тадаааааам **-3**

Jemxx, поражаюсь Вашему терпению))))

**Comment by jemxx** [comment]
Ну я сначала тоже подумал как и вы, что получается -3. Но там $count_line = 1, $count_gen_in_line = 9

**Comment by ghost** [comment]
> Ну я сначала тоже подумал как и вы, что получается -3. Но там $count_line = 1, $count_gen_in_line = 9

Придумать функцию, под которую надо будет подстраивать ini файл  - это гениальная идея) слов нет, снимаю шляпу))) Можно пойти дальше и за небольшую сумму денег высылать правильные настройки в ини файле))

А серьезно - если $count_line = 1, то мы приходим к построчному листанию)) т.е. к тому за что я изрядно был вымазан дерьмом еще пару месяцев назад) Удачи Вам, Jemxx, и терпения)))
