### ISSUE TITLE
ЖдемГенерала и ЖдемВсехГенералов с нормальной логикой

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#60]
Ниже две функции, которые работают независимо от того, сколько исходно в ини файле указано генералов. Как и должен работать любой нормальный код.
Ждем одного  любого генерала

```
Func ozidanierasstanovki2($image, $yes)
; Ждем одного генерала
    ;writelog("=====ОЖИДАЕМ ПЕРЕСТАНОВКу " & $yes & @CRLF)
	Local $tx = 0, $ty = 0, $ii = 1, $i = 0, $fl = 0, $count_line = 4, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране звезды (4 видимых строки по 9 ген в строке) минус один. Листаний на одно меньше чем экранов, т.к. первый экран виден всегда при открытии звезды  
	Local $count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 1
	Sleep(500 * $tormoza)
	while ($i < 900) ; макисмальное время ожидания в секундах (15 минут)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		$ii = 0
		selecttabatzvezda("specialisti", 0)
		while 1
			Sleep(500 * $tormoza)
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) Then
				$fl = 1
				ExitLoop
			Else
				zvezdamovepolzunokdown(1)
				$ii = $ii + 1
				If $ii > $count_list Then ExitLoop
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(1000)
	Wend
	If ($fl = 1) and ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
	If $i = 900 Then
		;writelog("=====ОШИБКА " & $i & @CRLF)
		Return 0
	EndIf
	;writelog("=====УСПЕХ " & $i & @CRLF)
	Return 1
EndFunc

```

Upd ЖдемВсехГенералов - вернул поэкранное листание как самое надежное

```
Func ozidanierasstanovki($image, $image_NA, $yes)
; Ждем всех генералов
    ;writelog("=====ОЖИДАЕМ ПЕРЕСТАНОВКу " & $yes & @CRLF)
	Local $tx = 0, $ty = 0, $ii = 1, $i = 0, $fl = 0, $count_line = 4, $count_gen_in_line = 9
	; $count_list - задаем количество листаний звезды - число ген из ини файла делим на количество ген на одном экране при листании звезды (3 видимых строки по 9 ген в строке) минус один 
	Local $count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 1
	Sleep(500 * $tormoza)
	while 1 AND ($i < 900) ; макисмальное время ожидания в секундах (15 минут)
		If openzvezdap() = 0 Then
			Return 0
		EndIf
		$ii = 0
		selecttabatzvezda("specialisti", 0)
		while 1
			If (_imagesearcharea($image, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 1) AND (_imagesearcharea($image_NA, 1, $zvezda_area[0], $zvezda_area[1], $zvezda_area[2], $zvezda_area[3], $tx, $ty, 20) = 0)  Then
				$fl = 1
				ExitLoop
			Else
				zvezdamovepolzunokdown(1)
				$ii = $ii + 1
				If $ii > $count_list Then ExitLoop
			EndIf
		WEnd
		If ($fl = 1) Then ExitLoop
		$i = $i + 1
		Sleep(1000)
	Wend
	If ($fl = 1) and ($yes = 1) Then
		zmemsmennuyukartinku("media\close-zv.bmp", 90, "media\close-zv_.bmp", 90)
	EndIf
	If $i = 900 Then
		; writelog("=====ОШИБКА " & $i & @CRLF)
			Return 0
	EndIf
	; writelog("=====УСПЕХ " & $i & @CRLF)
	Return 1
EndFunc
```

@jemxx, если надумаете включить нормальный рабочий код без сакральных камланий над ини и танцев с бубном, обратите внимание, что тут старый формат чтения из ини-файла.
И второй момент - у функции ЖдемВсехГенералов есть ограничение - ожидаемые генералы должны помещаться на один экран при перелистывании. Это легко доработать, как я предлагал пару месяцев назад тут (_Originally posted by @Marsik-A in https://github.com/jemxx/autobot/issues/35#issuecomment-716504861_), но получив в ответ исключительно негатив от отдельных одаренных кодеров, не стал этим заниматься углубленно. Мне проще переименовать ген таким образом, чтобы в домашней зоне они все были на одном (первом) экране, а медленных, которые уходят на 3й экран (автобусы, клаусы и простые) я на домашнем острове всех не жду, хожу 2мя составами.

Ниже видео, что команда ЖдемГенерала работает со всеми тремя экранами звезды и находит генерала в каждой строке на каждом экране

https://user-images.githubusercontent.com/64967268/103234878-d0d91b80-4951-11eb-9918-525ec6278f81.mp4

Upd. Забыл! В функциях нет прямой "защиты от дурака" для тех случаев, когда в качестве параметра у ЖдемГенерала или ЖдемВсехГенералов задан отсутствующий в наличии специалист. Если за 15 минут (900 секунд) генерал(ы) не отыщется(утся) - функции вылетят с ошибкой. 15 минут взято из соображений - быстрые не качаны на навигацию, простые 30ти минутные качаны. Время задается в виде счетчика $i в цикле while, внутри которого стоит 1000 мс sleep.

Upd2. Обновил функцию ожидания всех генералов

Upd3. Вернул обратно поэкранное листание

**Comment by jemxx** [comment]
Эти функции, остались в боте, я их не удалял. В целом сама идея LEKALA в плане ожидания мне понравилась, но пока там есть проблемы с логикой. Мне уже стало интересно допилить. Но я думаю пока будем допиливать верну ваши функции по типу как было раньше с откатом версии через настройку в ini. Кому что больше нравится то пусть и использует. Будет и ваш вариант и вариант LEKALA

**Comment by ghost** [comment]
Я у себя нашел и подправил мелкие логические ошибки в коде, и выложил уже исправленное. Но без листания на три строки, т.к. не пользуюсь этим. Могу посмотреть и заменить.

И если Вы хотите оставить  текст LEKALA, то позволю себе такое замечание 
отдельно проверять наличие ползунка на экране не нужно, с этим отлично справляется команда zvezdamovepolzunokdown(), там уже вшита такая проверка  

~~Вечером аккуратно просчитаю число листаний в ЖдемВсехГенералов для пролистывания трех строк, а не полного экрана и заменю~~ Обновил

Upd. Отменить коммит не получится, т.к. там старый вариант чтения из ини, или нет?

**Comment by jemxx** [comment]
Конфликт конечно будет, автоматически не отменится. Проще наверно новым коммитом сделать

Upd. Похоже это присваивание лишнее $count_list = 5. Можно так например
`
Local $count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 1
`

**Comment by ghost** [comment]
> Upd. Похоже это присваивание лишнее $count_list = 5. 

Можно и так, я просто привык к олдскульному стилю, когда все переменные объявляются в самом начале. Поэтому оптимизация кода вся на Ваше усмотрение.

> В целом сама идея LEKALA в плане ожидания мне понравилась

Идея отличная, с точки зрения человеческой логики, человек именно так и будет делать. Останется на нужном экране и будет ждать прибытия генералов. Но я вижу проблемы в ее формализации и реализации в текущем варианте игры из-за "походов" ген по домашнему острову до склада при отправке в прикл, когда иконка сначала сереет и только потом пропадает. Если остров застроен не сильно, и ген не так много, то они высаживаются недалеко от складов, и эти задержки, связанные с немгновенным пропадаем гены  из звезды, не так заметны. А вот если ген на острове много, а места для них мало - задержки могут быть более существенными, и тогда "зависание" бота на одном экране может привести к тому, что при выполнении команды бот зафиксирует экран еще при "сером" генерале (который уплывает в прикл раньше, но пока еще идет по домашнему острову), а потом когда генерал уплывет, то самая верхняя строка с нужным уже в текущей команде генералом может сдвинуться и генерал попадет на предыдущий, уже невидимый, экран. Этот случай очень сложно смоделировать, чтобы отследить и обработать. Именно  поэтому я и предлагал листать с самого сначала.

Но я не это хотел написать, по результатам трепа на Дискорде возник запрос на ожидание только активных генералов, игнорируя мертвых. Сейчас  это функционала нет. Мне идея показалась интересной, начал уже думать, как это можно сделать. Что скажете?

**Comment by jemxx** [comment]
> Можно и так, я просто привык к олдскульному стилю, когда все переменные объявляются в самом начале. Поэтому оптимизация кода вся на Ваше усмотрение.

В любом случае, где не объяви ее присваивание 5 там лишнее) 

>возник запрос на ожидание только активных генералов, игнорируя мертвых. Сейчас это функционала нет. Мне идея показалась интересной, начал уже думать, как это можно сделать. Что скажете?

Вполне себе здравая идея.

**Comment by ghost** [comment]
> Конфликт конечно будет, автоматически не отменится. Проще наверно новым коммитом сделать
> 
> Upd. Похоже это присваивание лишнее $count_list = 5. Можно так например
> `Local $count_list = int(read_ini(4)/($count_line * $count_gen_in_line)) - 1`

Когда будете делать это определение и присваивание, не забудьте перенести определение $count_list **ПОСЛЕ** определения $count_line и $count_gen_in_line, а то опять там нули могут оказаться)

потому как сейчас эта переменная определяется до своих составляющих
`	Local ... $count_list = 5, $count_line = 3, $count_gen_in_line = 9
`

**Comment by ghost** [comment]
Начал тестировать листание в ЖдемВсехГенералов на три строки и сразу же наткнулся у себя на вариант, когда команда сработает неверно.

![image](https://user-images.githubusercontent.com/64967268/103298285-0c83ec00-4a0b-11eb-866f-83310adff46e.png)

Например, вот в таком случае с Защитниками, когда генералы расползутся на 2 экрана - полная 4я строка и кусочки 5й, бот не видит в 4й строке серых Защитников, видит только активных и считает, что дождался их всех.
Поэтому поправил свой код с учетом обрезания области поиска на 82 пикселя, рассчитанного @LEKALA, до верхних трех строк. 


и снова нашел случай, когда команда сработает неверно
![image](https://user-images.githubusercontent.com/64967268/103299997-ed875900-4a0e-11eb-8e21-572184360e33.png)

Вот мои каратисты, расползшиеся на 3ю и 4ю строки. Для бота они есть в 3й строке, а значит даже если в 4й строке будут неактивные каратисты, бот их не увидит, т.к. область 4й строки исключена из поиска из соображений, указанных в предыдущем случае (пример с Защитниками), но! бот пролистнет три строки и 1 строка с каратистами (3я строка на видимо экране) уедет за пределы видимости, а значит снова бот сработает неправильно.
  
**Итог!**
т.е. получается, что ничего точнее поэкранного листания при ожидании всех ген я придумать не могу. Этот случай должен быть универсальным, но он требует некоторой реорганизации своих генералов один раз.
Вернул функцию ожидания всех ген к варианту с поэкранным листанием
