### ISSUE TITLE
Функции, в которые нужно добавить активацию окна

### ISSUE THREAD

**Issue by BasilMas** [jemxx/autobot#64]
Для корректной работы бота с 2мя и более клиентами на одном компьютере (без использования VM) необходимо добавить активацию окна в следующие функции

Юнит globalfuncWar.au3
func gotopriclanosleep()
https://github.com/jemxx/autobot/blob/5d96f5be65e6c549efcdb7e66385e32bfe2d88e6/globalfuncWAR.au3#L1789

func gotohome()
https://github.com/jemxx/autobot/blob/5d96f5be65e6c549efcdb7e66385e32bfe2d88e6/globalfuncWAR.au3#L1808

func endpricla()
https://github.com/jemxx/autobot/blob/5d96f5be65e6c549efcdb7e66385e32bfe2d88e6/globalfuncWAR.au3#L1831

**Comment by jemxx** [comment]
Добавил
