### ISSUE TITLE
.24

### ISSUE THREAD

**Issue by tester2121212121** [jemxx/autobot#67]
находит вирус fuerboos

**Comment by jemxx** [comment]
Кто находит? Где находит? Все исходники доступны

**Comment by tester2121212121** [comment]
https://www.virustotal.com/gui/file/b1b7c8c347ae62dbe5cdbd21ffff60752de182117d00666d46f08a3ece6b418e/detection

**Comment by jemxx** [comment]
Ну на autoit всегда ругались некоторые антивирусы, так как он умеет выполнять различные автоматические действия. В любом случае исходники доступны, вы можете самостоятельно собрать exe, проверить его там же и получить тот же результат.
