### ISSUE TITLE
НабратьИотправить

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#7]
Реализовать команду НабратьИОтправить, которая будет набирать арму и сразу отсылать гену в прикл, минуя иконку приключения.
Можно модифицировать команду Отправить, добавив еще одно значение флага Закрыть.
Закрыть - 1 (закрывает меню набора войск), 0 (не закрывает меню набора войск) после успешного набора, 2 (отправляет в открытый прикл). 
Реализацию данного функционала можно посмотреть в функции otpravitgenu, там две команды жмем картинку

	zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
	zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)

Будет работать только в случае, если активен только один прикл, ускорит отправку гены в прикл. Очень актуально для автобусов, т.к. они находятся в конце списка отправки и чтобы долистать до них - боту нужно приличное время

**Comment by jemxx** [comment]
Я думал над такой командой, но пока решил от нее отказаться, так как все это реализуется через ОтправитьДомой. Интуитивно не понятно, но после набора сразу можно отправить в прикл. Эта команда отправляет из прикла и как это не странно, но и в прикл. Картинка то ведь одна.
Посмотрите на прохождения Андрея, у него там так и реализовано. У него и подсмотрел эту идею. Можно конечно добавить, хуже не будет.

**Comment by ghost** [comment]
О, спасибо про через отправить домой я как-то даже не думал, я у Андрея видел давно в Нордике что ли через жмем картинку, и делаю так
Набрать=Генеральша,...
ЖмемКартинку=domoy1.bmp,20,domoy2.bmp,20
ЖмемКартинку=galka1.bmp,30,galka2.bmp,30   

Я склоняюсь все же к еще одному значению флага Закрыть для минимизации кликов мыши и лишних открытий/закрытий звезды.  

UPD. Полностью запутался в логике автора с флагами, и хз как это сделать.

**Comment by ghost** [comment]
Я вспомнил какая логика была у меня для этой команды - допустим у нас есть два набора для максимально быстрого прохода прикла. И дома я для скорости загружаю, к примеру, в Старшего арму сразу на 1ю атаку. Если использовать сочетание команд
Набрать=Генерал,1...
ОтправитьДомой=Генерал,1...
То если между этими двумя командами придет гена из прикла и сдвинет картинку нужного гены правее, то команда ОтправитьДомой может отослать не того гену. А если мы это все будем делать одной командой, то этого "сдвига" не случится никогда. 

Upd. Все, разобрался с логикой бота, сделал по флагу 2 отправку в прикл и обратно. Потестирую и если все ОК, то залью в свою ветку.
