### ISSUE TITLE
Модификация команды Клиент

### ISSUE THREAD

**Issue by BasilMas** [jemxx/autobot#76]
Сиррис вернул ник в заголовок окна, выглядит так
https://prnt.sc/25utcb1

Upd. Чекбокс из GUI можно и нужно убрать, а вот команду Клиент пока оставить. Но с этой версией клиента пока есть проблемы с другими утилками. Пусть пока задача повисит.

**Comment by jemxx** [comment]
Хорошо. Нет ни какой проблемы отменить коммит удаляющий данную команду.

**Comment by BasilMas** [comment]
Там с чекбоксом, который определяет заголовок окна - надо убрать, т.к. TSO Client-а в заголовке больше нет, а вот саму команду 
`Клиент=имя_пользователя `
оставить. Наверное так. Но пока эта модификация клиента кривовато работает

**Comment by jemxx** [comment]
Я понял. Чекбокс был удален отдельным коммитом, а команда другим. Тогда напишешь как вопрос прояснится, верну.

**Comment by BasilMas** [comment]
Команда Клиент работает без нареканий. С запуском самого клиента есть момент, при запуске 2й копии вылезает ошибка о невозможности записи блаблабла, но это не мешает запускать любое число копий клиента. Можно вернуть команду обратно.

**Comment by jemxx** [comment]
Вернул
