### ISSUE TITLE
Join my activity

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#8]
Теперь нужно слить Ваше и мое, чтобы я мог дальше двигаться.

**Comment by jemxx** [comment]
Завтра постараюсь это сделать. Немного на основной работе занят.

**Comment by ghost** [comment]
Ок, спасибо

**Comment by jemxx** [comment]
Сейчас как раз занимаюсь решением конфликтов. Пока не забыл, сразу скажу, что бы вы больше не меняли ниже приведенную функцию. В ней картинки должны быть именно в media\army_values\. В этой же папки лежать числа для набора армий. Тут подставляется число максимальной вместимости генерала. А то будем менять ее постоянно. Вы удалять army_values а я добавлять)

```
Func getFullGeneralImg($max)
	Local $fullGenaImg = 0
	
	If FileExists("media\army_values\" & $max & ".bmp") Then
		$fullGenaImg = "media\army_values\" & $max & ".bmp"
	EndIf

	Return $fullGenaImg
EndFunc
```

**Comment by ghost** [comment]
Давай(те) уже на ты перейдем. 
Ну я как заменил пару недель назад контекстом все вхождения media\army_values\ на media\ кроме набора армии так больше и не трогал ниче. В каждое вхождение вникать - голова опухнет. Там очень кривая для меня местами логика( Ясно теперь, почему у меня не набирает по значению 1000 просто не видит нужных картинок. Ну это скорее всего единственный конфликт. 

Я исходил из логики - все служебные в папке медиа, а все пользовательское в папку media\users. Т.к. значения армы (0-3000) дофигища файлов, то оставил их в отдельной папке, чтобы проще было искать другие служебные картинки, если вдруг что-то надо перескринивать. А то запаришься листать, пока доберешься до нужного.

**Comment by ghost** [comment]
Если мои архивы media и media1 видны в моей ветке, то там полностью рабочая папка медиа, я неделю гонял разные приклы проверял, вроде ничего лишнего не вычистил. Может что-то лишнее оставил, но основной мусор выкинул.

**Comment by Marsik-A** [comment]
Вот эту команду еще дополнил и протестил, флаг 2 в команде Набрать отсылает в открытый прикл.

`Func okclosegena($yes)
	writelog("==OKG | ")
	Local $ty = 0, $tx = 0, $search = 0, $i = 0
	$search = _imagesearch("media\nub_gena.bmp", 1, $tx, $ty, 20)
	If $search = 0 Then
		writelog(" Генерал закрыт ")
		Return 1
	Else
		$i = 0
		$search = 0
		zmemsmennuyukartinku("media\search_button_OK_enabled.bmp", 20, "media\search_button_OK_enabled_.bmp", 20)
		While ($i < 6 * $tormoza) AND ($search = 0)
			Sleep(1000 * $tormoza)
			$i = $i + 1
			sleepwhile("media\nub_gena.bmp", 20, 10)
			$search = _imagesearch("media\nub_gena.bmp", 1, $tx, $ty, 20)
		WEnd
		If $i < 6 Then
			If $yes = 0 Then
				$gluksnaboromarmii = $gluksnaboromarmii + 1
				Return 1
			EndIf
			$gluksnaboromarmii = $gluksnaboromarmii + 1
			If $yes = 1 Then
				zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
			EndIf
			If $yes = 2 Then
				zmemsmennuyukartinku("media\gohome.bmp", 30, "media\gohome_.bmp", 30)
				zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
			EndIf
			writelog(" Успешно ")
			Return 1
		Else
			zmemsmennuyukartinku("media\closegena.bmp", 30, "media\closegena_.bmp", 30)
			TrayTip("", "Ошибка: Не назначили войска", 0)
			writelog(" ОШИБКА ")
			Return 0
		EndIf
	EndIf
	writelog(" ОШИБКА !0! ")
	Return 0
EndFunc
`

**Comment by jemxx** [comment]
Смерджил ветку, надеюсь ничего не забыл. Пришлось вручную изменения вносить. Почему то конфликт был на все файлы целиком.

**Comment by ghost** [comment]
Ок, заберу и погоняю

**Comment by ghost** [comment]
Глянул релиз в облаке. В архиве папка media далеко не полная, поэтому с последними изменениями в путях к рабочим файлам бот работать не будет. Надо это как-то пофиксить
