### ISSUE TITLE
Сбор почты

### ISSUE THREAD

**Issue by BasilMas** [jemxx/autobot#80]
случайно выяснилось, что на каком-то этапе из media пропал файл, и Сбор почты перестал работать
[sunduk_po4ta.zip](https://github.com/jemxx/autobot/files/8002650/sunduk_po4ta.zip)

**Comment by BasilMas** [comment]
У меня вообще криво работает сбор почты: если в видимой области в начале списка письмо с баффом/отчетом о сражении, то бот пытается пролистнуть список, но попадает по все время по самому ползунку

**Comment by jemxx** [comment]
Разве Сбор Почты еще актуален?

**Comment by BasilMas** [comment]
В боте он есть, и он работает некорректно. Возник вопрос, как ПринятьПРиглашение будет работать, если разведы принесли сокровища, и письмо с пригласом ушло на 2й экран. Гипотетически такой вариант возможен.
Тут или чинить сбор почты, или учить бота листать почтовый ящик.

**Comment by jemxx** [comment]
Его не чинить надо, а переделывать на массовый сбор, а не поштучно как сейчас

**Comment by BasilMas** [comment]
в любом случае в текущем виде эта команда не работает как надо
