### ISSUE TITLE
Ошибка в функции close_prikla

### ISSUE THREAD

**Issue by BasilMas** [jemxx/autobot#82]
https://github.com/jemxx/autobot/blob/860d431c081f05450706cef339bba043443c4751/globalfuncWAR.au3#L2590

Из--за появления у бота локализации ошибка в этой функции
должно быть так с учетом русского интерфейса
```
Func close_pricla($kartinka)
	Opt("WinTitleMatchMode",2)
	WinActivate(WinWait($windowTitle))
	If haveimage($kartinka, 30) = 0 Then
		Return 1
	Else
		If findclickoncenterandwaitresult($kartinka, "media\" & $lang & "\posetit.bmp", 20, 50, 2, 5, 1, -300, -100) = 1 Then
			If findclickoncenterandwaitresult("media\" & $lang & "\posetit.bmp","media\" & $lang & "\perehod_v_zonu.bmp", 50, 20, 2, 5, 1, 0, -100) = 1 Then
				sleepwhile("media\" & $lang & "\prikl_error.bmp", 30, 30)
				sleep(500 * $tormoza)
				zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
				Return 1
			EndIf
		EndIf
	EndIf
	Return 0
EndFunc 

```
Файл prikl_error.bmp должен лежать в папке media\ru, т.к. он содержит надписи на русском языке

**Comment by BasilMas** [comment]
Функция закрытия ошибочного прикла за неделю ивента у меня работает нестабильно, мне показалось что такой вариант более устойчив к сбоям

```
Func close_pricla($kartinka)
	Opt("WinTitleMatchMode",2)
	WinActivate(WinWait($windowTitle))
	If haveimage($kartinka, 30) = 0 Then
		Return 1
	Else
		If findclickoncenterandwaitresult($kartinka, "media\" & $lang & "\posetit.bmp", 20, 50, 2, 5, 1, -300, -100) = 1 Then
			If findclickoncenterandwaitresult("media\" & $lang & "\posetit.bmp","media\" & $lang & "\prikl_error.bmp", 50, 20, 2, 5, 1, 0, -100) = 1 Then
				sleep(500 * $tormoza)
				zmemsmennuyukartinku("media\nubook.bmp", 30, "media\nubook_.bmp", 30)
				Return 1
			EndIf
		EndIf
	EndIf
	Return 0
EndFunc 
```
и слегка подрезал prikl_error.bmp, которую нужно поместить в папку media\ru

[prikl_error.zip](https://github.com/jemxx/autobot/files/8103915/prikl_error.zip)

**Comment by jemxx** [comment]
Хорошо, что сразу не добавил) Может еще подождать?)

**Comment by BasilMas** [comment]
скобку одну забыл открывающую, поправил уже. А так больше суток отработало без сбоев  

Кстати
https://github.com/jemxx/autobot/blob/860d431c081f05450706cef339bba043443c4751/globalfuncWAR.au3#L2563

po4ta_prig.bmp и po4ta_prig1.bmp тоже должны лежать в папке локализации
