### ISSUE TITLE
ЖдемПобеду

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#9]
Планирую сделать команду ЖдемПобеду=Генерал,время,флаг
Будет ждать победы указанного гены указанное число секунд, флаг будет определять что делать: 1 - продолжает работу после истечения времени, 0 - останавливает бот.

**Comment by jemxx** [comment]
А для чего? Все это легко реализуется с помощью ЖдемКартинку

**Comment by ghost** [comment]
Для ЖдемКартинку надо наскринить картинки побед всех ген, И если картинку не дождемся, то бот встанет. А картинка победы может не висит постоянно, как задание выполнено, к примеру. Но чета моя логика хромает. Не пойму почему не работает.

**Comment by jemxx** [comment]
А здесь как планируете сделать без скрина побед всех генералов? Тогда логично картинки побед ген сразу прописывать в specialists.json
Оно получится, скорее всего, точно также как и предложенный мной вариант. Я просто заскринил надпись Генерал одержал победу и использую ее через ЖдемКартинку. Я то знаю какой генерал и когда одержал победу. Если не победил, логично бот остановить) Как мне кажется кроме ЖдемКартинку ничего не нужно.

**Comment by ghost** [comment]
Планирую скрин гены он уже есть + скрин текста Гена победил. Вот тестирую

Ну это вам логично, а мне нет) Я к примеру ЖдуПобеды чтобы время не терять, например, в Юном. Длинные атаки справа, у меня там три атаки, Борис + Бабка + Сильвана. И каждый из ген может победить, ведь так? А мне надо засечь победу последней Сильваны, чтобы начать переносить других ген дальше. Но Юный фигня, там пара минут экономится, а вот в 3м разбойнике есть сектор с подлиннее переходами

**Comment by ghost** [comment]
Если Гена не победил, а слился, бот и так встанет, т.к. или армы не хватит или гена неживой
Ну и если важно победить зачем-то, я флаги делаю - остановиться или дальше идти. А то может гена проиграл, а пойдут атаки и перехваты. Вы посмотрите что Андрей пишет - он под обсерву с таймером все атаки сидит на тестовом выверяет, а можно же гораздо проще все делать!  

Upd Ну в общем я сделал, теперь потестить надо в реальных условиях.

**Comment by Marsik-A** [comment]
Ну в общем я сделал, теперь потестить надо в реальных условиях.

**Comment by ghost** [comment]
Ждем победу проверил на Ведьме, благо ивент вовремя подоспел. Все работает. Думаю, можно уже в таком виде релизить.
Я смерджил вчера обе ветки и добавил новый флаг для Набрать и ЖдемПобеду.   Надеюсь, конфликтов не будет.
На всякий случай проверьте, будет ли после мерджа файл gen_win.bmp в папке media

**Comment by jemxx** [comment]
Этим я завтра займусь, сейчас убегаю уже. Новую версию v0.17 с последними всеми изменениями за неделю залил в облако. Сейчас комент на сайте оставлю.

Пока вспомнил. Просмотрите еще функции ozidanierasstanovki2() и ozidanierasstanovki(), в частности вот эту строчку Sleep(30000 * $tormoza). Мне кажется тут тормоза не нужны.

**Comment by ghost** [comment]
возможно, я по аналогии со старыми добавлял, т.к. логики слип так и не понял. Сейчас обе команды Ждем... работают почти мгновенно, поэтому пусть пока будут. При случае уберу и потестю. Я в отпуске сейчас, а тут очень нестабильный вайфай, отваливается, через пару недель вернусь домой к нормальной связи, и можно будет уже все отладить в нормальных условиях, а не через ж...

**Comment by ghost** [comment]
Не спешите с заливкой, я думаю один день ничего не решит, завтра уже фулл релиз и сделаете. Тем более я справку вроде расширил и подправил. Разве только надо проверить везде ли техническая 1000 заменена на 3000. Чета я забыл про это совсем. В одном месте, в Набрать, вроде только поправил

**Comment by jemxx** [comment]
Я техническое изменил везде

**Comment by ghost** [comment]
в справке? я про справку, а  не в сорсах

**Comment by jemxx** [comment]
И в справке тоже. Там 3 раза всего
